{*******************************************************}
{                                                       }
{  Copyright (c) 1997-2001 Altium Limited               }
{                                                       }
{  http://www.dream-com.com                             }
{  contact@dream-com.com                                }
{                                                       }
{*******************************************************}
program makediff;

uses
  Unit1 in '..\Unit1.pas' {Form1};

{$R *.RES}

begin
  mainproc;
end.
