{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit FR_BarC_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  Menus,
  frBarcod,
  FR_Class,
  ExtCtrls,
  FR_Ctrls,
  FR_BarC;
function ConvertTfrBarCodeRecToVariant(var R : TfrBarCodeRec) : OleVariant;
function ConvertVariantToTfrBarCodeRec(const V : OleVariant) : TfrBarCodeRec;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TfrBarCodeRec__Wrapper = class(TDCRecordWrapper)
private
fR : TfrBarCodeRec;
public
function GetRecordPtr : pointer; override;
published
procedure setcCheckSum(const val : Boolean);
function getcCheckSum : Boolean;
property cCheckSum : Boolean read getcCheckSum write setcCheckSum;
procedure setcShowText(const val : Boolean);
function getcShowText : Boolean;
property cShowText : Boolean read getcShowText write setcShowText;
procedure setcCadr(const val : Boolean);
function getcCadr : Boolean;
property cCadr : Boolean read getcCadr write setcCadr;
procedure setcBarType(const val : TfrBarcodeType);
function getcBarType : TfrBarcodeType;
property cBarType : TfrBarcodeType read getcBarType write setcBarType;
procedure setcModul(const val : Integer);
function getcModul : Integer;
property cModul : Integer read getcModul write setcModul;
procedure setcRatio(const val : Double);
function getcRatio : Double;
property cRatio : Double read getcRatio write setcRatio;
procedure setcAngle(const val : Double);
function getcAngle : Double;
property cAngle : Double read getcAngle write setcAngle;
end;
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = _T0;

function __TfrBarCodeRec__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TfrBarCodeRec__Wrapper.setcCheckSum(const val : Boolean);
begin
TfrBarCodeRec(GetRecordPtr^).cCheckSum := val;
end;
function __TfrBarCodeRec__Wrapper.getcCheckSum : Boolean;
begin
result := TfrBarCodeRec(GetRecordPtr^).cCheckSum;
end;
procedure __TfrBarCodeRec__Wrapper.setcShowText(const val : Boolean);
begin
TfrBarCodeRec(GetRecordPtr^).cShowText := val;
end;
function __TfrBarCodeRec__Wrapper.getcShowText : Boolean;
begin
result := TfrBarCodeRec(GetRecordPtr^).cShowText;
end;
procedure __TfrBarCodeRec__Wrapper.setcCadr(const val : Boolean);
begin
TfrBarCodeRec(GetRecordPtr^).cCadr := val;
end;
function __TfrBarCodeRec__Wrapper.getcCadr : Boolean;
begin
result := TfrBarCodeRec(GetRecordPtr^).cCadr;
end;
procedure __TfrBarCodeRec__Wrapper.setcBarType(const val : TfrBarcodeType);
begin
TfrBarCodeRec(GetRecordPtr^).cBarType := val;
end;
function __TfrBarCodeRec__Wrapper.getcBarType : TfrBarcodeType;
begin
result := TfrBarCodeRec(GetRecordPtr^).cBarType;
end;
procedure __TfrBarCodeRec__Wrapper.setcModul(const val : Integer);
begin
TfrBarCodeRec(GetRecordPtr^).cModul := val;
end;
function __TfrBarCodeRec__Wrapper.getcModul : Integer;
begin
result := TfrBarCodeRec(GetRecordPtr^).cModul;
end;
procedure __TfrBarCodeRec__Wrapper.setcRatio(const val : Double);
begin
TfrBarCodeRec(GetRecordPtr^).cRatio := val;
end;
function __TfrBarCodeRec__Wrapper.getcRatio : Double;
begin
result := TfrBarCodeRec(GetRecordPtr^).cRatio;
end;
procedure __TfrBarCodeRec__Wrapper.setcAngle(const val : Double);
begin
TfrBarCodeRec(GetRecordPtr^).cAngle := val;
end;
function __TfrBarCodeRec__Wrapper.getcAngle : Double;
begin
result := TfrBarCodeRec(GetRecordPtr^).cAngle;
end;
function _TfrBarCodeRec_ : IDispatch;
begin
  result := __TfrBarCodeRec__Wrapper.Create;
end;

type __TfrBarCodeRec__Wrapper__ = class(__TfrBarCodeRec__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TfrBarCodeRec__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTfrBarCodeRecToVariant(var R : TfrBarCodeRec) : OleVariant;
var
__rw : __TfrBarCodeRec__Wrapper__;
begin
__rw := __TfrBarCodeRec__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTfrBarCodeRec(const V : OleVariant) : TfrBarCodeRec;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TfrBarCodeRec((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..2] of TClass = (
TfrBarCodeForm,
TfrBarCodeObject,
TfrBarCodeView
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..0] of string = (
'TfrBarCodeRec'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
__RegisteredMethods.Add(RegisterRWProc(MethodNames[0],Addr(_TfrBarCodeRec_)));
RegRegisterMethod(TfrBarCodeForm,'FormCreate',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrBarCodeForm.FormCreate));

RegRegisterMethod(TfrBarCodeForm,'bOkClick',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrBarCodeForm.bOkClick));

RegRegisterMethod(TfrBarCodeForm,'FormActivate',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrBarCodeForm.FormActivate));

RegRegisterMethod(TfrBarCodeForm,'ExprBtnClick',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TfrBarCodeForm.ExprBtnClick));

RegRegisterMethod(TfrBarCodeForm,'frSpeedButton1Click',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TfrBarCodeForm.frSpeedButton1Click));

RegRegisterMethod(TfrBarCodeForm,'frSpeedButton2Click',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TfrBarCodeForm.frSpeedButton2Click));

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
