{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit FR_DSET_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  SysUtils,
  Windows,
  Messages,
  Classes,
  FR_DSet;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = function : Boolean of object;

function __DC__GetTfrDataset__RangeBegin(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TfrDataset(Instance).RangeBegin;
end;

procedure __DC__SetTfrDataset__RangeBegin(Instance : TObject; Params : PVariantArgList);
begin
TfrDataset(Instance).RangeBegin:=OleVariant(Params^[0]);
end;

function __DC__GetTfrDataset__RangeEnd(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TfrDataset(Instance).RangeEnd;
end;

procedure __DC__SetTfrDataset__RangeEnd(Instance : TObject; Params : PVariantArgList);
begin
TfrDataset(Instance).RangeEnd:=OleVariant(Params^[0]);
end;

function __DC__GetTfrDataset__RangeEndCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TfrDataset(Instance).RangeEndCount;
end;

procedure __DC__SetTfrDataset__RangeEndCount(Instance : TObject; Params : PVariantArgList);
begin
TfrDataset(Instance).RangeEndCount:=OleVariant(Params^[0]);
end;

function __DC__GetTfrDataset__RecNo(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TfrDataset(Instance).RecNo;
end;

procedure __RegisterProps;
begin
RegisterProperty(TfrDataset,'RangeBegin',__DC__GetTfrDataset__RangeBegin,__DC__SetTfrDataset__RangeBegin);
RegisterProperty(TfrDataset,'RangeEnd',__DC__GetTfrDataset__RangeEnd,__DC__SetTfrDataset__RangeEnd);
RegisterProperty(TfrDataset,'RangeEndCount',__DC__GetTfrDataset__RangeEndCount,__DC__SetTfrDataset__RangeEndCount);
RegisterProperty(TfrDataset,'RecNo',__DC__GetTfrDataset__RecNo,nil);
end;

const __ConstNames0 : array[0..4] of string = (
'rbFirst'
,'rbCurrent'
,'reLast'
,'reCurrent'
,'reCount'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,rbFirst));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,rbCurrent));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,reLast));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,reCurrent));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,reCount));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..1] of TClass = (
TfrDataset,
TfrUserDataset
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrDataset,'Init',TypeInfo(_T0),NoParams, pointer(48));

RegRegisterMethod(TfrDataset,'Exit',TypeInfo(_T1),NoParams, pointer(52));

RegRegisterMethod(TfrDataset,'First',TypeInfo(_T2),NoParams, pointer(56));

RegRegisterMethod(TfrDataset,'Next',TypeInfo(_T3),NoParams, pointer(60));

RegRegisterMethod(TfrDataset,'Prior',TypeInfo(_T4),NoParams, pointer(64));

RegRegisterMethod(TfrDataset,'Eof',TypeInfo(_T5),[TypeInfo(Boolean)], pointer(68));

end;
initialization
_mreg_0;
RegisterEvent(TypeInfo(TCheckEOFEvent),[
TypeInfo(TObject),
TypeInfo(Boolean)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
