{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit FR_Flds1_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Types,
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  ExtCtrls,
  FR_Flds1;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TRect__Wrapper = class(TDCRecordWrapper)
private
fR : TRect;
public
function GetRecordPtr : pointer; override;
published
procedure setLeft(const val : Longint);
function getLeft : Longint;
property Left : Longint read getLeft write setLeft;
procedure setTop(const val : Longint);
function getTop : Longint;
property Top : Longint read getTop write setTop;
procedure setRight(const val : Longint);
function getRight : Longint;
property Right : Longint read getRight write setRight;
procedure setBottom(const val : Longint);
function getBottom : Longint;
property Bottom : Longint read getBottom write setBottom;
end;
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = procedure (p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState) of object;

_T4 = _T0;

_T5 = _T0;

_T6 = procedure (p0 : TObject;
var p1 : TCloseAction) of object;

_T7 = procedure (p0 : TObject;
var p1 : TDragObject) of object;

_T8 = procedure (p0 : TObject;
p1 : TMouseButton;
p2 : TShiftState;
p3 : Integer;
p4 : Integer) of object;

_T9 = procedure (p0 : TObject;
p1 : TShiftState;
p2 : Integer;
p3 : Integer) of object;

_T10 = _T8;

_T11 = procedure  of object;

_T12 = _T11;

function __TRect__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TRect__Wrapper.setLeft(const val : Longint);
begin
TRect(GetRecordPtr^).Left := val;
end;
function __TRect__Wrapper.getLeft : Longint;
begin
result := TRect(GetRecordPtr^).Left;
end;
procedure __TRect__Wrapper.setTop(const val : Longint);
begin
TRect(GetRecordPtr^).Top := val;
end;
function __TRect__Wrapper.getTop : Longint;
begin
result := TRect(GetRecordPtr^).Top;
end;
procedure __TRect__Wrapper.setRight(const val : Longint);
begin
TRect(GetRecordPtr^).Right := val;
end;
function __TRect__Wrapper.getRight : Longint;
begin
result := TRect(GetRecordPtr^).Right;
end;
procedure __TRect__Wrapper.setBottom(const val : Longint);
begin
TRect(GetRecordPtr^).Bottom := val;
end;
function __TRect__Wrapper.getBottom : Longint;
begin
result := TRect(GetRecordPtr^).Bottom;
end;
procedure __TfrInsFieldsForm__DatasetsLBDrawItem__Wrapper(__Instance : TfrInsFieldsForm;
p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState);
var
__p2 : ^TRect;
__i2 : IDispatch;
begin
if p2 = nil then exit;
__p2 := (p2 as IDCRecordWrapper).GetRecordPtr;
TfrInsFieldsForm(__Instance).DatasetsLBDrawItem(p0,p1,__p2^,p3);
end;


type __TRect__Wrapper__ = class(__TRect__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TRect__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
var
__rw : __TRect__Wrapper__;
begin
__rw := __TRect__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TRect((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

function __DC__GetFR_Flds1__frFieldsDialog(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(FR_Flds1.frFieldsDialog);
end;

procedure __DC__SetFR_Flds1__frFieldsDialog(Instance : TObject; Params : PVariantArgList);
begin
TObject(FR_Flds1.frFieldsDialog):=(VarToObject(OleVariant(Params^[0])));
end;

var __RegisteredVars : TList;
procedure __RegisterVars;
begin
__RegisteredVars := TList.Create;
__RegisteredVars.Add(RegisterVar('frFieldsDialog',__DC__GetFR_Flds1__frFieldsDialog,__DC__SetFR_Flds1__frFieldsDialog));
end;

procedure __UnregisterVars;
begin
__RegisteredVars.Free;
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TfrInsFieldsForm
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrInsFieldsForm,'FormCreate',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrInsFieldsForm.FormCreate));

RegRegisterMethod(TfrInsFieldsForm,'FieldsLBDblClick',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrInsFieldsForm.FieldsLBDblClick));

RegRegisterMethod(TfrInsFieldsForm,'DatasetsLBClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrInsFieldsForm.DatasetsLBClick));

RegRegisterMethod(TfrInsFieldsForm,'DatasetsLBDrawItem',TypeInfo(_T3),[
TypeInfo(TWinControl),
TypeInfo(Integer),
TypeInfo(IDispatch),
TypeInfo(TOwnerDrawState)],Addr(__TfrInsFieldsForm__DatasetsLBDrawItem__Wrapper));

RegRegisterMethod(TfrInsFieldsForm,'FormShow',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TfrInsFieldsForm.FormShow));

RegRegisterMethod(TfrInsFieldsForm,'FormHide',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TfrInsFieldsForm.FormHide));

RegRegisterMethod(TfrInsFieldsForm,'FormClose',TypeInfo(_T6),[
TypeInfo(TObject),
TypeInfo(TCloseAction)],Addr(TfrInsFieldsForm.FormClose));

RegRegisterMethod(TfrInsFieldsForm,'FieldsLBStartDrag',TypeInfo(_T7),[
TypeInfo(TObject),
TypeInfo(TDragObject)],Addr(TfrInsFieldsForm.FieldsLBStartDrag));

RegRegisterMethod(TfrInsFieldsForm,'SplitterMouseDown',TypeInfo(_T8),[
TypeInfo(TObject),
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrInsFieldsForm.SplitterMouseDown));

RegRegisterMethod(TfrInsFieldsForm,'SplitterMouseMove',TypeInfo(_T9),[
TypeInfo(TObject),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrInsFieldsForm.SplitterMouseMove));

RegRegisterMethod(TfrInsFieldsForm,'SplitterMouseUp',TypeInfo(_T10),[
TypeInfo(TObject),
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrInsFieldsForm.SplitterMouseUp));

RegRegisterMethod(TfrInsFieldsForm,'Grow',TypeInfo(_T11),NoParams,Addr(TfrInsFieldsForm.Grow));

RegRegisterMethod(TfrInsFieldsForm,'RefreshData',TypeInfo(_T12),NoParams,Addr(TfrInsFieldsForm.RefreshData));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
__RegisterVars;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnRegisterVars;
end.
