{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit FR_Insp_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Types,
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  ExtCtrls,
  StdCtrls,
  Buttons,
  FR_Class,
  FR_Ctrls,
  FR_Pars,
  FR_PopupLB,
  FR_Insp;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TRect__Wrapper = class(TDCRecordWrapper)
private
fR : TRect;
public
function GetRecordPtr : pointer; override;
published
procedure setLeft(const val : Longint);
function getLeft : Longint;
property Left : Longint read getLeft write setLeft;
procedure setTop(const val : Longint);
function getTop : Longint;
property Top : Longint read getTop write setTop;
procedure setRight(const val : Longint);
function getRight : Longint;
property Right : Longint read getRight write setRight;
procedure setBottom(const val : Longint);
function getBottom : Longint;
property Bottom : Longint read getBottom write setBottom;
end;
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = procedure (p0 : TObject;
p1 : TMouseButton;
p2 : TShiftState;
p3 : Integer;
p4 : Integer) of object;

_T3 = procedure (p0 : TObject;
var p1 : Word;
p2 : TShiftState) of object;

_T4 = _T0;

_T5 = _T0;

_T6 = _T0;

_T7 = _T0;

_T8 = procedure (p0 : TObject;
var p1 : Char) of object;

_T9 = _T0;

_T10 = _T0;

_T11 = _T0;

_T12 = _T0;

_T13 = procedure (p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState) of object;

_T14 = _T0;

_T15 = _T0;

_T16 = _T2;

_T17 = _T0;

_T18 = procedure (p0 : TObject;
p1 : TShiftState;
p2 : Integer;
p3 : Integer) of object;

_T19 = _T2;

_T20 = procedure  of object;

{_T21 = procedure (p0 : String;
p1 : Variant;
p2 : TfrDataTypes;
p3 : TStringList;
p4 : Variant;
p5 : TNotifyEvent) of object;}

_T22 = _T20;

_T23 = _T20;

{_T24 = procedure (p0 : Variant;
p1 : TfrDataTypes;
p2 : TStringList;
p3 : Variant;
p4 : TNotifyEvent) of object;}

function __TRect__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TRect__Wrapper.setLeft(const val : Longint);
begin
TRect(GetRecordPtr^).Left := val;
end;
function __TRect__Wrapper.getLeft : Longint;
begin
result := TRect(GetRecordPtr^).Left;
end;
procedure __TRect__Wrapper.setTop(const val : Longint);
begin
TRect(GetRecordPtr^).Top := val;
end;
function __TRect__Wrapper.getTop : Longint;
begin
result := TRect(GetRecordPtr^).Top;
end;
procedure __TRect__Wrapper.setRight(const val : Longint);
begin
TRect(GetRecordPtr^).Right := val;
end;
function __TRect__Wrapper.getRight : Longint;
begin
result := TRect(GetRecordPtr^).Right;
end;
procedure __TRect__Wrapper.setBottom(const val : Longint);
begin
TRect(GetRecordPtr^).Bottom := val;
end;
function __TRect__Wrapper.getBottom : Longint;
begin
result := TRect(GetRecordPtr^).Bottom;
end;
procedure __TfrInspForm__CB1DrawItem__Wrapper(__Instance : TfrInspForm;
p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState);
var
__p2 : ^TRect;
__i2 : IDispatch;
begin
if p2 = nil then exit;
__p2 := (p2 as IDCRecordWrapper).GetRecordPtr;
TfrInspForm(__Instance).CB1DrawItem(p0,p1,__p2^,p3);
end;


type __TRect__Wrapper__ = class(__TRect__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TRect__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
var
__rw : __TRect__Wrapper__;
begin
__rw := __TRect__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TRect((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
function __DC__GetTfrInspForm__PropValue(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TfrInspForm(Instance).PropValue[OleVariant(Params^[0])];
end;

procedure __DC__SetTfrInspForm__PropValue(Instance : TObject; Params : PVariantArgList);
begin
TfrInspForm(Instance).PropValue[OleVariant(Params^[1])]:=OleVariant(Params^[0]);
end;

function __DC__GetTfrInspForm__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TfrInspForm(Instance).Items);
end;

procedure __DC__SetTfrInspForm__Items(Instance : TObject; Params : PVariantArgList);
begin
TfrInspForm(Instance).Items:=TStringList(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTfrInspForm__ItemIndex(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TfrInspForm(Instance).ItemIndex;
end;

procedure __DC__SetTfrInspForm__ItemIndex(Instance : TObject; Params : PVariantArgList);
begin
TfrInspForm(Instance).ItemIndex:=OleVariant(Params^[0]);
end;

function __DC__GetTfrInspForm__Count(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TfrInspForm(Instance).Count;
end;

function __DC__GetTfrInspForm__SplitterPos(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TfrInspForm(Instance).SplitterPos;
end;

procedure __DC__SetTfrInspForm__SplitterPos(Instance : TObject; Params : PVariantArgList);
begin
TfrInspForm(Instance).SplitterPos:=OleVariant(Params^[0]);
end;

function __DC__GetTProp__Value(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TProp(Instance).Value;
end;

procedure __DC__SetTProp__Value(Instance : TObject; Params : PVariantArgList);
begin
TProp(Instance).Value:=OleVariant(Params^[0]);
end;

procedure __RegisterProps;
begin
RegisterIndexedProperty(TfrInspForm,'PropValue',1,False,__DC__GetTfrInspForm__PropValue,__DC__SetTfrInspForm__PropValue);
RegisterProperty(TfrInspForm,'Items',__DC__GetTfrInspForm__Items,__DC__SetTfrInspForm__Items);
RegisterProperty(TfrInspForm,'ItemIndex',__DC__GetTfrInspForm__ItemIndex,__DC__SetTfrInspForm__ItemIndex);
RegisterProperty(TfrInspForm,'Count',__DC__GetTfrInspForm__Count,nil);
RegisterProperty(TfrInspForm,'SplitterPos',__DC__GetTfrInspForm__SplitterPos,__DC__SetTfrInspForm__SplitterPos);
RegisterProperty(TProp,'Value',__DC__GetTProp__Value,__DC__SetTProp__Value);
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..1] of TClass = (
TfrInspForm,
TProp
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrInspForm,'PaintBox1Paint',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrInspForm.PaintBox1Paint));

RegRegisterMethod(TfrInspForm,'FormCreate',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrInspForm.FormCreate));

RegRegisterMethod(TfrInspForm,'PaintBox1MouseDown',TypeInfo(_T2),[
TypeInfo(TObject),
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrInspForm.PaintBox1MouseDown));

RegRegisterMethod(TfrInspForm,'Edit1KeyDown',TypeInfo(_T3),[
TypeInfo(TObject),
TypeInfo(Word),
TypeInfo(TShiftState)],Addr(TfrInspForm.Edit1KeyDown));

RegRegisterMethod(TfrInspForm,'EditBtnClick',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TfrInspForm.EditBtnClick));

RegRegisterMethod(TfrInspForm,'FormDeactivate',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TfrInspForm.FormDeactivate));

RegRegisterMethod(TfrInspForm,'FormDestroy',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TfrInspForm.FormDestroy));

RegRegisterMethod(TfrInspForm,'Edit1DblClick',TypeInfo(_T7),[
TypeInfo(TObject)],Addr(TfrInspForm.Edit1DblClick));

RegRegisterMethod(TfrInspForm,'Edit1KeyPress',TypeInfo(_T8),[
TypeInfo(TObject),
TypeInfo(Char)],Addr(TfrInspForm.Edit1KeyPress));

RegRegisterMethod(TfrInspForm,'FormResize',TypeInfo(_T9),[
TypeInfo(TObject)],Addr(TfrInspForm.FormResize));

RegRegisterMethod(TfrInspForm,'FormActivate',TypeInfo(_T10),[
TypeInfo(TObject)],Addr(TfrInspForm.FormActivate));

RegRegisterMethod(TfrInspForm,'CB1DropDown',TypeInfo(_T11),[
TypeInfo(TObject)],Addr(TfrInspForm.CB1DropDown));

RegRegisterMethod(TfrInspForm,'CB1Click',TypeInfo(_T12),[
TypeInfo(TObject)],Addr(TfrInspForm.CB1Click));

RegRegisterMethod(TfrInspForm,'CB1DrawItem',TypeInfo(_T13),[
TypeInfo(TWinControl),
TypeInfo(Integer),
TypeInfo(IDispatch),
TypeInfo(TOwnerDrawState)],Addr(__TfrInspForm__CB1DrawItem__Wrapper));

RegRegisterMethod(TfrInspForm,'ComboBtnClick',TypeInfo(_T14),[
TypeInfo(TObject)],Addr(TfrInspForm.ComboBtnClick));

RegRegisterMethod(TfrInspForm,'LB1Click',TypeInfo(_T15),[
TypeInfo(TObject)],Addr(TfrInspForm.LB1Click));

RegRegisterMethod(TfrInspForm,'Edit1MouseDown',TypeInfo(_T16),[
TypeInfo(TObject),
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrInspForm.Edit1MouseDown));

RegRegisterMethod(TfrInspForm,'FormShow',TypeInfo(_T17),[
TypeInfo(TObject)],Addr(TfrInspForm.FormShow));

RegRegisterMethod(TfrInspForm,'PaintBox1MouseMove',TypeInfo(_T18),[
TypeInfo(TObject),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrInspForm.PaintBox1MouseMove));

RegRegisterMethod(TfrInspForm,'PaintBox1MouseUp',TypeInfo(_T19),[
TypeInfo(TObject),
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrInspForm.PaintBox1MouseUp));

RegRegisterMethod(TfrInspForm,'ClearProperties',TypeInfo(_T20),NoParams,Addr(TfrInspForm.ClearProperties));

RegRegisterMethod(TfrInspForm,'ItemsChanged',TypeInfo(_T22),NoParams,Addr(TfrInspForm.ItemsChanged));

RegRegisterMethod(TfrInspForm,'Grow',TypeInfo(_T23),NoParams,Addr(TfrInspForm.Grow));

end;
initialization
_mreg_0;
{RegRegisterMethod(TfrInspForm,'AddProperty',TypeInfo(_T21),[
TypeInfo(String),
TypeInfo(Variant),
TypeInfo(TfrDataTypes),
TypeInfo(TStringList),
TypeInfo(Variant),
TypeInfo(TNotifyEvent)],Addr(TfrInspForm.AddProperty))}

{RegisterProc(TProp,'Create',mtConstructor,TypeInfo(_T24),[
TypeInfo(Variant),
TypeInfo(TfrDataTypes),
TypeInfo(TStringList),
TypeInfo(Variant),
TypeInfo(TNotifyEvent)], pointer(0),cRegister)}

RegisterEvent(TypeInfo(TGetObjectsEvent),[
TypeInfo(TStrings)]);

RegisterEvent(TypeInfo(TModifyEvent),[
TypeInfo(Integer)]);

RegisterEvent(TypeInfo(TSelectionChangedEvent),[
TypeInfo(String)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
