{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit FR_OLE_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  OleCtnrs,
  StdCtrls,
  ExtCtrls,
  FR_DBRel,
  FR_Class,
  ActiveX,
  FR_OLE;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TOleContainer;
p1 : TOleContainer) of object;

_T1 = procedure (p0 : TObject) of object;

_T2 = _T1;

_T3 = _T1;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..2] of TClass = (
TfrOleForm,
TfrOLEObject,
TfrOLEView
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..0] of string = (
'AssignOle'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TOleContainer),
TypeInfo(TOleContainer)],Addr(AssignOle),cRegister);

RegRegisterMethod(TfrOleForm,'Button1Click',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrOleForm.Button1Click));

RegRegisterMethod(TfrOleForm,'Button2Click',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrOleForm.Button2Click));

RegRegisterMethod(TfrOleForm,'FormShow',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TfrOleForm.FormShow));

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
