{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit FR_Utils_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Types,
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  SysUtils,
  Windows,
  Messages,
  Classes,
  Graphics,
  Controls,
  FR_DBRel,
  Forms,
  StdCtrls,
  Menus,
  FR_Utils;
function ConvertTPointToVariant(var R : TPoint) : OleVariant;
function ConvertVariantToTPoint(const V : OleVariant) : TPoint;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TPoint__Wrapper = class(TDCRecordWrapper)
private
fR : TPoint;
public
function GetRecordPtr : pointer; override;
published
procedure setX(const val : Longint);
function getX : Longint;
property X : Longint read getX write setX;
procedure setY(const val : Longint);
function getY : Longint;
property Y : Longint read getY write setY;
end;
type
_T0 = procedure (p0 : TStream;
p1 : TStrings) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = function (p0 : TStream): String of object;

_T4 = _T3;

_T5 = procedure (p0 : TStream;
p1 : String) of object;

_T6 = function (p0 : TStream): Boolean of object;

_T7 = function (p0 : TStream): Byte of object;

_T8 = function (p0 : TStream): Word of object;

_T9 = function (p0 : TStream): Integer of object;

_T10 = procedure (p0 : TStream;
p1 : TFont) of object;

_T11 = procedure (p0 : TStream;
p1 : Boolean) of object;

_T12 = procedure (p0 : TStream;
p1 : Byte) of object;

_T13 = procedure (p0 : TStream;
p1 : Word) of object;

_T14 = procedure (p0 : TStream;
p1 : Integer) of object;

_T15 = _T10;

_T16 = procedure (p0 : Array of TControl;
p1 : Boolean) of object;

_T17 = function (p0 : TWinControl;
const p1 : IDispatch): TControl of object;

_T18 = function (p0 : String): TfrTDataSet of object;

_T19 = function (p0 : TfrTField): Variant of object;

_T20 = procedure (p0 : String;
var p1 : TfrTDataSet;
var p2 : String) of object;

_T21 = function (p0 : TFontStyles): Integer of object;

_T22 = function (p0 : Integer): TFontStyles of object;

_T23 = function (p0 : TComponent;
p1 : String): TComponent of object;

{_T24 = procedure (p0 : TComponent;
p1 : TClass;
p2 : TStrings;
p3 : TComponent) of object;}

_T25 = function : String of object;

_T26 = function (p0 : String): Double of object;

_T27 = function (const p0 : String): String of object;

_T28 = procedure (p0 : String;
p1 : TStringList) of object;

_T29 = function (p0 : Integer): String of object;

function __TPoint__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TPoint__Wrapper.setX(const val : Longint);
begin
TPoint(GetRecordPtr^).X := val;
end;
function __TPoint__Wrapper.getX : Longint;
begin
result := TPoint(GetRecordPtr^).X;
end;
procedure __TPoint__Wrapper.setY(const val : Longint);
begin
TPoint(GetRecordPtr^).Y := val;
end;
function __TPoint__Wrapper.getY : Longint;
begin
result := TPoint(GetRecordPtr^).Y;
end;
function ____frControlAtPos__Wrapper(p0 : TWinControl;
const p1 : IDispatch): TControl;
var
__p1 : ^TPoint;
__i1 : IDispatch;
begin
if p1 = nil then exit;
__p1 := (p1 as IDCRecordWrapper).GetRecordPtr;
result := frControlAtPos(p0,__p1^);
end;


type __TPoint__Wrapper__ = class(__TPoint__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TPoint__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTPointToVariant(var R : TPoint) : OleVariant;
var
__rw : __TPoint__Wrapper__;
begin
__rw := __TPoint__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTPoint(const V : OleVariant) : TPoint;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TPoint((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..28] of string = (
'frReadMemo'
,'frReadMemo22'
,'frWriteMemo'
,'frReadString'
,'frReadString22'
,'frWriteString'
,'frReadBoolean'
,'frReadByte'
,'frReadWord'
,'frReadInteger'
,'frReadFont'
,'frWriteBoolean'
,'frWriteByte'
,'frWriteWord'
,'frWriteInteger'
,'frWriteFont'
,'frEnableControls'
,'frControlAtPos'
,'frGetDataSet'
,'frGetFieldValue'
,'frGetDataSetAndField'
,'frGetFontStyle'
,'frSetFontStyle'
,'frFindComponent'
,'frGetWindowsVersion'
,'frStrToFloat'
,'frRemoveQuotes'
,'frSetCommaText'
,'frLoadStr'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TStream),
TypeInfo(TStrings)],Addr(frReadMemo),cRegister);

RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(TStream),
TypeInfo(TStrings)],Addr(frReadMemo22),cRegister);

RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(TStream),
TypeInfo(TStrings)],Addr(frWriteMemo),cRegister);

RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[
TypeInfo(TStream),TypeInfo(String)],Addr(frReadString),cRegister);

RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[
TypeInfo(TStream),TypeInfo(String)],Addr(frReadString22),cRegister);

RegisterProc(nil,MethodNames[5],mtProc,TypeInfo(_T5),[
TypeInfo(TStream),
TypeInfo(String)],Addr(frWriteString),cRegister);

RegisterProc(nil,MethodNames[6],mtProc,TypeInfo(_T6),[
TypeInfo(TStream),TypeInfo(Boolean)],Addr(frReadBoolean),cRegister);

RegisterProc(nil,MethodNames[7],mtProc,TypeInfo(_T7),[
TypeInfo(TStream),TypeInfo(Byte)],Addr(frReadByte),cRegister);

RegisterProc(nil,MethodNames[8],mtProc,TypeInfo(_T8),[
TypeInfo(TStream),TypeInfo(Word)],Addr(frReadWord),cRegister);

RegisterProc(nil,MethodNames[9],mtProc,TypeInfo(_T9),[
TypeInfo(TStream),TypeInfo(Integer)],Addr(frReadInteger),cRegister);

RegisterProc(nil,MethodNames[10],mtProc,TypeInfo(_T10),[
TypeInfo(TStream),
TypeInfo(TFont)],Addr(frReadFont),cRegister);

RegisterProc(nil,MethodNames[11],mtProc,TypeInfo(_T11),[
TypeInfo(TStream),
TypeInfo(Boolean)],Addr(frWriteBoolean),cRegister);

RegisterProc(nil,MethodNames[12],mtProc,TypeInfo(_T12),[
TypeInfo(TStream),
TypeInfo(Byte)],Addr(frWriteByte),cRegister);

RegisterProc(nil,MethodNames[13],mtProc,TypeInfo(_T13),[
TypeInfo(TStream),
TypeInfo(Word)],Addr(frWriteWord),cRegister);

RegisterProc(nil,MethodNames[14],mtProc,TypeInfo(_T14),[
TypeInfo(TStream),
TypeInfo(Integer)],Addr(frWriteInteger),cRegister);

RegisterProc(nil,MethodNames[15],mtProc,TypeInfo(_T15),[
TypeInfo(TStream),
TypeInfo(TFont)],Addr(frWriteFont),cRegister);

RegisterProc(nil,MethodNames[16],mtProc,TypeInfo(_T16),[
ArrayInfo(TypeInfo(TControl)),
TypeInfo(Boolean)],Addr(frEnableControls),cRegister);

RegisterProc(nil,MethodNames[17],mtProc,TypeInfo(_T17),[
TypeInfo(TWinControl),
TypeInfo(IDispatch),TypeInfo(TControl)],Addr(____frControlAtPos__Wrapper),cRegister);

RegisterProc(nil,MethodNames[18],mtProc,TypeInfo(_T18),[
TypeInfo(String),TypeInfo(TfrTDataSet)],Addr(frGetDataSet),cRegister);

RegisterProc(nil,MethodNames[19],mtProc,TypeInfo(_T19),[
TypeInfo(TfrTField),TypeInfo(Variant)],Addr(frGetFieldValue),cRegister);

RegisterProc(nil,MethodNames[20],mtProc,TypeInfo(_T20),[
TypeInfo(String),
TypeInfo(TfrTDataSet),
TypeInfo(String)],Addr(frGetDataSetAndField),cRegister);

RegisterProc(nil,MethodNames[21],mtProc,TypeInfo(_T21),[
TypeInfo(TFontStyles),TypeInfo(Integer)],Addr(frGetFontStyle),cRegister);

RegisterProc(nil,MethodNames[22],mtProc,TypeInfo(_T22),[
TypeInfo(Integer),TypeInfo(TFontStyles)],Addr(frSetFontStyle),cRegister);

RegisterProc(nil,MethodNames[23],mtProc,TypeInfo(_T23),[
TypeInfo(TComponent),
TypeInfo(String),TypeInfo(TComponent)],Addr(frFindComponent),cRegister);

RegisterProc(nil,MethodNames[24],mtProc,TypeInfo(_T25),[TypeInfo(String)],Addr(frGetWindowsVersion),cRegister);

RegisterProc(nil,MethodNames[25],mtProc,TypeInfo(_T26),[
TypeInfo(String),TypeInfo(Double)],Addr(frStrToFloat),cRegister);

RegisterProc(nil,MethodNames[26],mtProc,TypeInfo(_T27),[
TypeInfo(String),TypeInfo(String)],Addr(frRemoveQuotes),cRegister);

RegisterProc(nil,MethodNames[27],mtProc,TypeInfo(_T28),[
TypeInfo(String),
TypeInfo(TStringList)],Addr(frSetCommaText),cRegister);

RegisterProc(nil,MethodNames[28],mtProc,TypeInfo(_T29),[
TypeInfo(Integer),TypeInfo(String)],Addr(frLoadStr),cRegister);

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
{RegisterProc(nil,'frGetComponents',mtProc,TypeInfo(_T24),[
TypeInfo(TComponent),
TypeInfo(TClass),
TypeInfo(TStrings),
TypeInfo(TComponent)],Addr(frGetComponents),cRegister)}

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
