{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit FRD_QRY_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  DB,
  FRD_Wrap,
  FRD_Qry;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = _T0;

_T6 = _T0;

_T7 = _T0;

_T8 = _T0;

_T9 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TfrQueryPropForm
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrQueryPropForm,'FormShow',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.FormShow));

RegRegisterMethod(TfrQueryPropForm,'FormHide',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.FormHide));

RegRegisterMethod(TfrQueryPropForm,'ParamsBClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.ParamsBClick));

RegRegisterMethod(TfrQueryPropForm,'FieldsBClick',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.FieldsBClick));

RegRegisterMethod(TfrQueryPropForm,'Button2Click',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.Button2Click));

RegRegisterMethod(TfrQueryPropForm,'FormCreate',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.FormCreate));

RegRegisterMethod(TfrQueryPropForm,'Button1Click',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.Button1Click));

RegRegisterMethod(TfrQueryPropForm,'Button4Click',TypeInfo(_T7),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.Button4Click));

RegRegisterMethod(TfrQueryPropForm,'bSQBClick',TypeInfo(_T8),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.bSQBClick));

RegRegisterMethod(TfrQueryPropForm,'AliasCBChange',TypeInfo(_T9),[
TypeInfo(TObject)],Addr(TfrQueryPropForm.AliasCBChange));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
