{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit EditChar_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Graphics,
  Forms,
  TeEngine,
  Chart,
  TeeEditCha,
  classes,
  dcscript,
  dcsystem,
  EditChar;
function ConvertTChartClickedPartToVariant(var R : TChartClickedPart) : OleVariant;
function ConvertVariantToTChartClickedPart(const V : OleVariant) : TChartClickedPart;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TChartClickedPart__Wrapper = class(TDCRecordWrapper)
private
fR : TChartClickedPart;
public
function GetRecordPtr : pointer; override;
published
procedure setPart(const val : TChartClickedPartStyle);
function getPart : TChartClickedPartStyle;
property Part : TChartClickedPartStyle read getPart write setPart;
procedure setPointIndex(const val : Integer);
function getPointIndex : Integer;
property PointIndex : Integer read getPointIndex write setPointIndex;
procedure setASeries(const val : TChartSeries);
function getASeries : TChartSeries;
property ASeries : TChartSeries read getASeries write setASeries;
procedure setAAxis(const val : TChartAxis);
function getAAxis : TChartAxis;
property AAxis : TChartAxis read getAAxis write setAAxis;
end;
type
_T0 = procedure (p0 : TForm;
p1 : TCustomChart) of object;

_T1 = procedure (p0 : TForm;
p1 : TChartSeries) of object;

_T2 = _T1;

_T3 = _T1;

_T4 = _T0;

_T5 = procedure (p0 : TForm;
p1 : TChartAxis) of object;

_T6 = procedure (p0 : TForm;
p1 : TChartWall) of object;

_T7 = procedure (p0 : TForm;
p1 : TChartTitle) of object;

_T8 = procedure (p0 : TForm;
p1 : TCustomChart;
p2 : Integer) of object;

_T9 = procedure (p0 : TForm;
p1 : TCustomChart;
const p2 : IDispatch) of object;

_T10 = procedure (p0 : TComponent;
p1 : TCustomChart) of object;

_T11 = procedure (p0 : TForm;
p1 : TTeeCustomTool) of object;

function __TChartClickedPart__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TChartClickedPart__Wrapper.setPart(const val : TChartClickedPartStyle);
begin
TChartClickedPart(GetRecordPtr^).Part := val;
end;
function __TChartClickedPart__Wrapper.getPart : TChartClickedPartStyle;
begin
result := TChartClickedPart(GetRecordPtr^).Part;
end;
procedure __TChartClickedPart__Wrapper.setPointIndex(const val : Integer);
begin
TChartClickedPart(GetRecordPtr^).PointIndex := val;
end;
function __TChartClickedPart__Wrapper.getPointIndex : Integer;
begin
result := TChartClickedPart(GetRecordPtr^).PointIndex;
end;
procedure __TChartClickedPart__Wrapper.setASeries(const val : TChartSeries);
begin
TChartClickedPart(GetRecordPtr^).ASeries := val;
end;
function __TChartClickedPart__Wrapper.getASeries : TChartSeries;
begin
result := TChartClickedPart(GetRecordPtr^).ASeries;
end;
procedure __TChartClickedPart__Wrapper.setAAxis(const val : TChartAxis);
begin
TChartClickedPart(GetRecordPtr^).AAxis := val;
end;
function __TChartClickedPart__Wrapper.getAAxis : TChartAxis;
begin
result := TChartClickedPart(GetRecordPtr^).AAxis;
end;
procedure ____EditChartPart__Wrapper(p0 : TForm;
p1 : TCustomChart;
const p2 : IDispatch);
var
__p2 : ^TChartClickedPart;
__i2 : IDispatch;
begin
if p2 = nil then exit;
__p2 := (p2 as IDCRecordWrapper).GetRecordPtr;
EditChartPart(p0,p1,__p2^);
end;


type __TChartClickedPart__Wrapper__ = class(__TChartClickedPart__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TChartClickedPart__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTChartClickedPartToVariant(var R : TChartClickedPart) : OleVariant;
var
__rw : __TChartClickedPart__Wrapper__;
begin
__rw := __TChartClickedPart__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTChartClickedPart(const V : OleVariant) : TChartClickedPart;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TChartClickedPart((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..11] of string = (
'EditChartLegend'
,'EditSeries'
,'EditSeriesDataSource'
,'EditSeriesMarks'
,'EditChart'
,'EditChartAxis'
,'EditChartWall'
,'EditChartTitle'
,'EditChartPage'
,'EditChartPart'
,'EditDSSChart'
,'EditChartTool'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TForm),
TypeInfo(TCustomChart)],Addr(EditChartLegend),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(TForm),
TypeInfo(TChartSeries)],Addr(EditSeries),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(TForm),
TypeInfo(TChartSeries)],Addr(EditSeriesDataSource),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[
TypeInfo(TForm),
TypeInfo(TChartSeries)],Addr(EditSeriesMarks),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[
TypeInfo(TForm),
TypeInfo(TCustomChart)],Addr(EditChart),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[5],mtProc,TypeInfo(_T5),[
TypeInfo(TForm),
TypeInfo(TChartAxis)],Addr(EditChartAxis),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[6],mtProc,TypeInfo(_T6),[
TypeInfo(TForm),
TypeInfo(TChartWall)],Addr(EditChartWall),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[7],mtProc,TypeInfo(_T7),[
TypeInfo(TForm),
TypeInfo(TChartTitle)],Addr(EditChartTitle),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[8],mtProc,TypeInfo(_T8),[
TypeInfo(TForm),
TypeInfo(TCustomChart),
TypeInfo(Integer)],Addr(EditChartPage),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[9],mtProc,TypeInfo(_T9),[
TypeInfo(TForm),
TypeInfo(TCustomChart),
TypeInfo(IDispatch)],Addr(____EditChartPart__Wrapper),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[10],mtProc,TypeInfo(_T10),[
TypeInfo(TComponent),
TypeInfo(TCustomChart)],Addr(EditDSSChart),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[11],mtProc,TypeInfo(_T11),[
TypeInfo(TForm),
TypeInfo(TTeeCustomTool)],Addr(EditChartTool),cRegister));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
