{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit StatChar_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  TeEngine,
  Series,
  TeCanvas,
  CandleCh,
  classes,
  dcscript,
  dcsystem,
  StatChar;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
function __DC__GetTBollingerFunction__LowBand(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TBollingerFunction(Instance).LowBand);
end;

function __DC__GetTMACDFunction__MACDExp(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TMACDFunction(Instance).MACDExp);
end;

function __DC__GetTMACDFunction__Histogram(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TMACDFunction(Instance).Histogram);
end;

procedure __RegisterProps;
begin
RegisterProperty(TBollingerFunction,'LowBand',__DC__GetTBollingerFunction__LowBand,nil);
RegisterProperty(TMACDFunction,'MACDExp',__DC__GetTMACDFunction__MACDExp,nil);
RegisterProperty(TMACDFunction,'Histogram',__DC__GetTMACDFunction__Histogram,nil);
end;

const __ConstNames0 : array[0..1] of string = (
'rsiOpenClose'
,'rsiClose'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,rsiOpenClose));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,rsiClose));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..11] of TClass = (
TBollingerFunction,
TExpAverageFunction,
TExpMovAveFunction,
THistogramSeries,
TMACDFunction,
TMomentumDivFunction,
TMomentumFunction,
TMovingAverageFunction,
TRMSFunction,
TRSIFunction,
TStdDeviationFunction,
TStochasticFunction
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

initialization
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
