{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeAxisIncr_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  ExtCtrls,
  Chart,
  TeEngine,
  TeeProcs,
  classes,
  dcscript,
  dcsystem,
  TeeAxisIncr;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (p0 : TComponent;
const p1 : Double;
p2 : Boolean;
p3 : Boolean;
const p4 : String): String of object;

_T1 = procedure (const p0 : String) of object;

_T2 = procedure (p0 : TObject) of object;

_T3 = _T2;

_T4 = _T2;

_T5 = _T2;

_T6 = _T2;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TAxisIncrement
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..1] of string = (
'GetIncrementText'
,'TeeShowIncorrect'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TComponent),
TypeInfo(Double),
TypeInfo(Boolean),
TypeInfo(Boolean),
TypeInfo(String),TypeInfo(String)],Addr(GetIncrementText),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(String)],Addr(TeeShowIncorrect),cRegister));

RegRegisterMethod(TAxisIncrement,'FormShow',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TAxisIncrement.FormShow));

RegRegisterMethod(TAxisIncrement,'RadioGroup1Click',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TAxisIncrement.RadioGroup1Click));

RegRegisterMethod(TAxisIncrement,'BitBtn1Click',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TAxisIncrement.BitBtn1Click));

RegRegisterMethod(TAxisIncrement,'CBExactClick',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TAxisIncrement.CBExactClick));

RegRegisterMethod(TAxisIncrement,'CBStepsChange',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TAxisIncrement.CBStepsChange));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
