{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeAnnToolEdit_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  ComCtrls,
  TeeProcs,
  TeeTools,
  TeCanvas,
  TeeCustomShapeEditor,
  classes,
  dcscript,
  dcsystem,
  TeeAnnToolEdit;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = _T0;

_T6 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TAnnotationToolEdit
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TAnnotationToolEdit,'FormShow',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TAnnotationToolEdit.FormShow));

RegRegisterMethod(TAnnotationToolEdit,'EFormatChange',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TAnnotationToolEdit.EFormatChange));

RegRegisterMethod(TAnnotationToolEdit,'CBPosChange',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TAnnotationToolEdit.CBPosChange));

RegRegisterMethod(TAnnotationToolEdit,'ECustLeftChange',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TAnnotationToolEdit.ECustLeftChange));

RegRegisterMethod(TAnnotationToolEdit,'CBCustPosClick',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TAnnotationToolEdit.CBCustPosClick));

RegRegisterMethod(TAnnotationToolEdit,'ECustTopChange',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TAnnotationToolEdit.ECustTopChange));

RegRegisterMethod(TAnnotationToolEdit,'FormCreate',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TAnnotationToolEdit.FormCreate));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
