{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeAbout_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  Graphics,
  Controls,
  Forms,
  ExtCtrls,
  StdCtrls,
  SysUtils,
  classes,
  dcscript,
  dcsystem,
  TeeAbout;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TeeWindowHandle;
const p1 : String) of object;

_T1 = procedure (const p0 : String;
const p1 : String) of object;

_T2 = procedure (p0 : TObject) of object;

_T3 = _T2;

_T4 = _T2;

procedure ____TeeShowAboutBox__Wrapper(cArgs : integer; pArgs : PArgList);
begin
case cArgs of
0:
TeeShowAboutBox;
1:
TeeShowAboutBox(OleVariant(pargs^[0]));
2:
TeeShowAboutBox(OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end
end;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TTeeAboutForm
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..1] of string = (
'GotoURL'
,'TeeShowAboutBox'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TeeWindowHandle),
TypeInfo(String)],Addr(GotoURL),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtScriptProc,TypeInfo(_T1),[
TypeInfo(String),
TypeInfo(String)],Addr(____TeeShowAboutBox__Wrapper),cRegister));

RegRegisterMethod(TTeeAboutForm,'LabelwwwClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TTeeAboutForm.LabelwwwClick));

RegRegisterMethod(TTeeAboutForm,'FormCreate',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TTeeAboutForm.FormCreate));

RegRegisterMethod(TTeeAboutForm,'FormPaint',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TTeeAboutForm.FormPaint));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
