{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeBrushDlg_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  ExtCtrls,
  TeCanvas,
  TeePenDlg,
  classes,
  dcscript,
  dcsystem,
  TeeBrushDlg;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TRect__Wrapper = class(TDCRecordWrapper)
private
fR : TRect;
public
function GetRecordPtr : pointer; override;
published
procedure setLeft(const val : Integer);
function getLeft : Integer;
property Left : Integer read getLeft write setLeft;
procedure setTop(const val : Integer);
function getTop : Integer;
property Top : Integer read getTop write setTop;
procedure setRight(const val : Integer);
function getRight : Integer;
property Right : Integer read getRight write setRight;
procedure setBottom(const val : Integer);
function getBottom : Integer;
property Bottom : Integer read getBottom write setBottom;
end;
type
_T0 = function (p0 : TComponent;
p1 : TChartBrush): Boolean of object;

_T1 = function (p0 : TComponent;
p1 : TTeeFont): Boolean of object;

_T2 = function (p0 : TComponent): String of object;

_T3 = procedure (p0 : TComponent;
p1 : TPicture) of object;

_T4 = procedure (p0 : Integer;
p1 : TBitmap) of object;

_T5 = procedure (p0 : TObject) of object;

_T6 = _T5;

_T7 = procedure (p0 : TObject;
var p1 : TCloseAction) of object;

_T8 = _T5;

_T9 = _T5;

_T10 = _T5;

_T11 = procedure (p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState) of object;

function __TRect__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TRect__Wrapper.setLeft(const val : Integer);
begin
TRect(GetRecordPtr^).Left := val;
end;
function __TRect__Wrapper.getLeft : Integer;
begin
result := TRect(GetRecordPtr^).Left;
end;
procedure __TRect__Wrapper.setTop(const val : Integer);
begin
TRect(GetRecordPtr^).Top := val;
end;
function __TRect__Wrapper.getTop : Integer;
begin
result := TRect(GetRecordPtr^).Top;
end;
procedure __TRect__Wrapper.setRight(const val : Integer);
begin
TRect(GetRecordPtr^).Right := val;
end;
function __TRect__Wrapper.getRight : Integer;
begin
result := TRect(GetRecordPtr^).Right;
end;
procedure __TRect__Wrapper.setBottom(const val : Integer);
begin
TRect(GetRecordPtr^).Bottom := val;
end;
function __TRect__Wrapper.getBottom : Integer;
begin
result := TRect(GetRecordPtr^).Bottom;
end;
procedure __TBrushDialog__LStyleDrawItem__Wrapper(__Instance : TBrushDialog;
p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState);
var
__p2 : ^TRect;
__i2 : IDispatch;
begin
if p2 = nil then exit;
__p2 := (p2 as IDCRecordWrapper).GetRecordPtr;
TBrushDialog(__Instance).LStyleDrawItem(p0,p1,__p2^,p3);
end;


type __TRect__Wrapper__ = class(__TRect__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TRect__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
var
__rw : __TRect__Wrapper__;
begin
__rw := __TRect__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TRect((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TBrushDialog
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..4] of string = (
'EditChartBrush'
,'EditTeeFont'
,'TeeGetPictureFileName'
,'TeeLoadClearImage'
,'GetTeeBrush'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TComponent),
TypeInfo(TChartBrush),TypeInfo(Boolean)],Addr(EditChartBrush),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(TComponent),
TypeInfo(TTeeFont),TypeInfo(Boolean)],Addr(EditTeeFont),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(TComponent),TypeInfo(String)],Addr(TeeGetPictureFileName),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[
TypeInfo(TComponent),
TypeInfo(TPicture)],Addr(TeeLoadClearImage),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[
TypeInfo(Integer),
TypeInfo(TBitmap)],Addr(GetTeeBrush),cRegister));

RegRegisterMethod(TBrushDialog,'FormShow',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TBrushDialog.FormShow));

RegRegisterMethod(TBrushDialog,'Button3Click',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TBrushDialog.Button3Click));

RegRegisterMethod(TBrushDialog,'FormClose',TypeInfo(_T7),[
TypeInfo(TObject),
TypeInfo(TCloseAction)],Addr(TBrushDialog.FormClose));

RegRegisterMethod(TBrushDialog,'Button1Click',TypeInfo(_T8),[
TypeInfo(TObject)],Addr(TBrushDialog.Button1Click));

RegRegisterMethod(TBrushDialog,'LStyleClick',TypeInfo(_T9),[
TypeInfo(TObject)],Addr(TBrushDialog.LStyleClick));

RegRegisterMethod(TBrushDialog,'FormCreate',TypeInfo(_T10),[
TypeInfo(TObject)],Addr(TBrushDialog.FormCreate));

RegRegisterMethod(TBrushDialog,'LStyleDrawItem',TypeInfo(_T11),[
TypeInfo(TWinControl),
TypeInfo(Integer),
TypeInfo(IDispatch),
TypeInfo(TOwnerDrawState)],Addr(__TBrushDialog__LStyleDrawItem__Wrapper));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
