{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeChartActions_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  ActnList,
  Chart,
  TeEngine,
  classes,
  dcscript,
  dcsystem,
  TeeChartActions;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..14] of TClass = (
TChartAction,
TChartAction3D,
TChartActionAxes,
TChartActionCopy,
TChartActionEdit,
TChartActionGrid,
TChartActionLegend,
TChartActionPrint,
TChartActionSave,
TCustomChartAction,
TCustomSeriesAction,
TSeriesAction,
TSeriesActionActive,
TSeriesActionEdit,
TSeriesActionMarks
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

initialization
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
