{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeChartBook_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  Menus,
  ComCtrls,
  ExtCtrls,
  Chart,
  TeeComma,
  classes,
  dcscript,
  dcsystem,
  TeeChartBook;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = function : TCustomChart of object;

_T2 = function : TTeeCommander of object;

_T3 = procedure (const p0 : String) of object;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TChartBook
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..0] of string = (
'Register'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),NoParams,Addr(Register),cRegister));

RegRegisterMethod(TChartBook,'ActiveChart',TypeInfo(_T1),[TypeInfo(TCustomChart)],Addr(TChartBook.ActiveChart));

RegRegisterMethod(TChartBook,'ActiveToolbar',TypeInfo(_T2),[TypeInfo(TTeeCommander)],Addr(TChartBook.ActiveToolbar));

RegRegisterMethod(TChartBook,'AddChart',TypeInfo(_T3),[
TypeInfo(String)],Addr(TChartBook.AddChart));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
