{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeChartGrid_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  Chart,
  TeEngine,
  TeeProcs,
  TeCanvas,
  TeeNavigator,
  Controls,
  Grids,
  Graphics,
  ExtCtrls,
  classes,
  dcscript,
  dcsystem,
  TeeChartGrid;
function ConvertTGridRectToVariant(var R : TGridRect) : OleVariant;
function ConvertVariantToTGridRect(const V : OleVariant) : TGridRect;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TGridRect__Wrapper = class(TDCRecordWrapper)
private
fR : TGridRect;
public
function GetRecordPtr : pointer; override;
published
procedure setLeft(const val : Longint);
function getLeft : Longint;
property Left : Longint read getLeft write setLeft;
procedure setTop(const val : Longint);
function getTop : Longint;
property Top : Longint read getTop write setTop;
procedure setRight(const val : Longint);
function getRight : Longint;
property Right : Longint read getRight write setRight;
procedure setBottom(const val : Longint);
function getBottom : Longint;
property Bottom : Longint read getBottom write setBottom;
end;
type
_T0 = procedure  of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = procedure (p0 : Boolean) of object;

function __TGridRect__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TGridRect__Wrapper.setLeft(const val : Longint);
begin
TGridRect(GetRecordPtr^).Left := val;
end;
function __TGridRect__Wrapper.getLeft : Longint;
begin
result := TGridRect(GetRecordPtr^).Left;
end;
procedure __TGridRect__Wrapper.setTop(const val : Longint);
begin
TGridRect(GetRecordPtr^).Top := val;
end;
function __TGridRect__Wrapper.getTop : Longint;
begin
result := TGridRect(GetRecordPtr^).Top;
end;
procedure __TGridRect__Wrapper.setRight(const val : Longint);
begin
TGridRect(GetRecordPtr^).Right := val;
end;
function __TGridRect__Wrapper.getRight : Longint;
begin
result := TGridRect(GetRecordPtr^).Right;
end;
procedure __TGridRect__Wrapper.setBottom(const val : Longint);
begin
TGridRect(GetRecordPtr^).Bottom := val;
end;
function __TGridRect__Wrapper.getBottom : Longint;
begin
result := TGridRect(GetRecordPtr^).Bottom;
end;

type __TGridRect__Wrapper__ = class(__TGridRect__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TGridRect__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTGridRectToVariant(var R : TGridRect) : OleVariant;
var
__rw : __TGridRect__Wrapper__;
begin
__rw := __TGridRect__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTGridRect(const V : OleVariant) : TGridRect;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TGridRect((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
function __DC__GetTChartGrid__Col(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).Col;
end;

procedure __DC__SetTChartGrid__Col(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).Col:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__ColCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).ColCount;
end;

procedure __DC__SetTChartGrid__ColCount(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).ColCount:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__ColWidths(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).ColWidths[OleVariant(Params^[0])];
end;

procedure __DC__SetTChartGrid__ColWidths(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).ColWidths[OleVariant(Params^[1])]:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__EditorMode(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).EditorMode;
end;

procedure __DC__SetTChartGrid__EditorMode(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).EditorMode:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__GridHeight(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).GridHeight;
end;

function __DC__GetTChartGrid__GridWidth(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).GridWidth;
end;

function __DC__GetTChartGrid__LeftCol(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).LeftCol;
end;

procedure __DC__SetTChartGrid__LeftCol(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).LeftCol:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__Selection(Instance : TObject; Params : PVariantArgList) : OleVariant;
var
__wrapper : __TGridRect__Wrapper;
begin
__wrapper := __TGridRect__Wrapper.Create;
__wrapper.fR := TChartGrid(Instance).Selection;
result := IUnknown(__wrapper) as IDispatch;
end;

procedure __DC__SetTChartGrid__Selection(Instance : TObject; Params : PVariantArgList);
var
__idisp:IDispatch;
__iwrapper:IDCRecordWrapper;
begin
__idisp:=DCVarToInterface(OleVariant(Params^[0]));
if __idisp=nil then exit;
__idisp.QueryInterface(IDCRecordWrapper, __iwrapper);
TChartGrid(Instance).Selection:=TGridRect(__iwrapper.GetRecordPtr^);
end;

function __DC__GetTChartGrid__Row(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).Row;
end;

procedure __DC__SetTChartGrid__Row(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).Row:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__RowCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).RowCount;
end;

procedure __DC__SetTChartGrid__RowCount(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).RowCount:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__RowHeights(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).RowHeights[OleVariant(Params^[0])];
end;

procedure __DC__SetTChartGrid__RowHeights(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).RowHeights[OleVariant(Params^[1])]:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__TabStops(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).TabStops[OleVariant(Params^[0])];
end;

procedure __DC__SetTChartGrid__TabStops(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).TabStops[OleVariant(Params^[1])]:=OleVariant(Params^[0]);
end;

function __DC__GetTChartGrid__TopRow(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartGrid(Instance).TopRow;
end;

procedure __DC__SetTChartGrid__TopRow(Instance : TObject; Params : PVariantArgList);
begin
TChartGrid(Instance).TopRow:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomChartGrid__Chart(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomChartGrid(Instance).Chart);
end;

procedure __DC__SetTCustomChartGrid__Chart(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).Chart:=TCustomChart(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomChartGrid__Series(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomChartGrid(Instance).Series);
end;

procedure __DC__SetTCustomChartGrid__Series(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).Series:=TChartSeries(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomChartGrid__ShowColors(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomChartGrid(Instance).ShowColors;
end;

procedure __DC__SetTCustomChartGrid__ShowColors(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).ShowColors:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomChartGrid__ShowFields(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomChartGrid(Instance).ShowFields;
end;

procedure __DC__SetTCustomChartGrid__ShowFields(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).ShowFields:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomChartGrid__ShowLabels(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomChartGrid(Instance).ShowLabels;
end;

procedure __DC__SetTCustomChartGrid__ShowLabels(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).ShowLabels:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomChartGrid__ShowXValues(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomChartGrid(Instance).ShowXValues;
end;

procedure __DC__SetTCustomChartGrid__ShowXValues(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).ShowXValues:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomChartGrid__FixedCols(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomChartGrid(Instance).FixedCols;
end;

procedure __DC__SetTCustomChartGrid__FixedCols(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).FixedCols:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomChartGrid__DefaultRowHeight(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomChartGrid(Instance).DefaultRowHeight;
end;

procedure __DC__SetTCustomChartGrid__DefaultRowHeight(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).DefaultRowHeight:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomChartGrid__GridLineWidth(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomChartGrid(Instance).GridLineWidth;
end;

procedure __DC__SetTCustomChartGrid__GridLineWidth(Instance : TObject; Params : PVariantArgList);
begin
TCustomChartGrid(Instance).GridLineWidth:=OleVariant(Params^[0]);
end;

procedure __RegisterProps;
begin
RegisterProperty(TChartGrid,'Col',__DC__GetTChartGrid__Col,__DC__SetTChartGrid__Col);
RegisterProperty(TChartGrid,'ColCount',__DC__GetTChartGrid__ColCount,__DC__SetTChartGrid__ColCount);
RegisterIndexedProperty(TChartGrid,'ColWidths',1,False,__DC__GetTChartGrid__ColWidths,__DC__SetTChartGrid__ColWidths);
RegisterProperty(TChartGrid,'EditorMode',__DC__GetTChartGrid__EditorMode,__DC__SetTChartGrid__EditorMode);
RegisterProperty(TChartGrid,'GridHeight',__DC__GetTChartGrid__GridHeight,nil);
RegisterProperty(TChartGrid,'GridWidth',__DC__GetTChartGrid__GridWidth,nil);
RegisterProperty(TChartGrid,'LeftCol',__DC__GetTChartGrid__LeftCol,__DC__SetTChartGrid__LeftCol);
RegisterProperty(TChartGrid,'Selection',__DC__GetTChartGrid__Selection,__DC__SetTChartGrid__Selection);
RegisterProperty(TChartGrid,'Row',__DC__GetTChartGrid__Row,__DC__SetTChartGrid__Row);
RegisterProperty(TChartGrid,'RowCount',__DC__GetTChartGrid__RowCount,__DC__SetTChartGrid__RowCount);
RegisterIndexedProperty(TChartGrid,'RowHeights',1,False,__DC__GetTChartGrid__RowHeights,__DC__SetTChartGrid__RowHeights);
RegisterIndexedProperty(TChartGrid,'TabStops',1,False,__DC__GetTChartGrid__TabStops,__DC__SetTChartGrid__TabStops);
RegisterProperty(TChartGrid,'TopRow',__DC__GetTChartGrid__TopRow,__DC__SetTChartGrid__TopRow);
RegisterProperty(TCustomChartGrid,'Chart',__DC__GetTCustomChartGrid__Chart,__DC__SetTCustomChartGrid__Chart);
RegisterProperty(TCustomChartGrid,'Series',__DC__GetTCustomChartGrid__Series,__DC__SetTCustomChartGrid__Series);
RegisterProperty(TCustomChartGrid,'ShowColors',__DC__GetTCustomChartGrid__ShowColors,__DC__SetTCustomChartGrid__ShowColors);
RegisterProperty(TCustomChartGrid,'ShowFields',__DC__GetTCustomChartGrid__ShowFields,__DC__SetTCustomChartGrid__ShowFields);
RegisterProperty(TCustomChartGrid,'ShowLabels',__DC__GetTCustomChartGrid__ShowLabels,__DC__SetTCustomChartGrid__ShowLabels);
RegisterProperty(TCustomChartGrid,'ShowXValues',__DC__GetTCustomChartGrid__ShowXValues,__DC__SetTCustomChartGrid__ShowXValues);
RegisterProperty(TCustomChartGrid,'FixedCols',__DC__GetTCustomChartGrid__FixedCols,__DC__SetTCustomChartGrid__FixedCols);
RegisterProperty(TCustomChartGrid,'DefaultRowHeight',__DC__GetTCustomChartGrid__DefaultRowHeight,__DC__SetTCustomChartGrid__DefaultRowHeight);
RegisterProperty(TCustomChartGrid,'GridLineWidth',__DC__GetTCustomChartGrid__GridLineWidth,__DC__SetTCustomChartGrid__GridLineWidth);
end;

const __ConstNames0 : array[0..2] of string = (
'cgsAuto'
,'cgsNo'
,'cgsYes'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,cgsAuto));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,cgsNo));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,cgsYes));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..2] of TClass = (
TChartGrid,
TChartGridNavigator,
TCustomChartGrid
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TCustomChartGrid,'Delete',TypeInfo(_T0),NoParams,Addr(TCustomChartGrid.Delete));

RegRegisterMethod(TCustomChartGrid,'Insert',TypeInfo(_T1),NoParams,Addr(TCustomChartGrid.Insert));

RegRegisterMethod(TCustomChartGrid,'RecalcDimensions',TypeInfo(_T2),NoParams,Addr(TCustomChartGrid.RecalcDimensions));

RegRegisterMethod(TCustomChartGrid,'StartEditing',TypeInfo(_T3),NoParams,Addr(TCustomChartGrid.StartEditing));

RegRegisterMethod(TCustomChartGrid,'StopEditing',TypeInfo(_T4),[
TypeInfo(Boolean)],Addr(TCustomChartGrid.StopEditing));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
