{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeCustEdit_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  ExtCtrls,
  ComCtrls,
  TeeProcs,
  Chart,
  Series,
  TeCanvas,
  TeePenDlg,
  classes,
  dcscript,
  dcsystem,
  TeeCustEdit;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = _T0;

_T6 = _T0;

_T7 = _T0;

_T8 = _T0;

_T9 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TCustomSeriesEditor
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TCustomSeriesEditor,'FormShow',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.FormShow));

RegRegisterMethod(TCustomSeriesEditor,'CBStairsClick',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.CBStairsClick));

RegRegisterMethod(TCustomSeriesEditor,'CBInvStairsClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.CBInvStairsClick));

RegRegisterMethod(TCustomSeriesEditor,'CBColorEachClick',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.CBColorEachClick));

RegRegisterMethod(TCustomSeriesEditor,'CBDark3DClick',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.CBDark3DClick));

RegRegisterMethod(TCustomSeriesEditor,'CBStackChange',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.CBStackChange));

RegRegisterMethod(TCustomSeriesEditor,'EHeightChange',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.EHeightChange));

RegRegisterMethod(TCustomSeriesEditor,'CBClickClick',TypeInfo(_T7),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.CBClickClick));

RegRegisterMethod(TCustomSeriesEditor,'BBrushClick',TypeInfo(_T8),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.BBrushClick));

RegRegisterMethod(TCustomSeriesEditor,'FormCreate',TypeInfo(_T9),[
TypeInfo(TObject)],Addr(TCustomSeriesEditor.FormCreate));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
