{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeColorBandEdit_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  ExtCtrls,
  ComCtrls,
  Buttons,
  Chart,
  TeeTools,
  TeCanvas,
  TeePenDlg,
  TeeAxisToolEdit,
  classes,
  dcscript,
  dcsystem,
  TeeColorBandEdit;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = _T0;

_T6 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TColorBandToolEditor
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TColorBandToolEditor,'FormShow',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TColorBandToolEditor.FormShow));

RegRegisterMethod(TColorBandToolEditor,'BPatternClick',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TColorBandToolEditor.BPatternClick));

RegRegisterMethod(TColorBandToolEditor,'EStartChange',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TColorBandToolEditor.EStartChange));

RegRegisterMethod(TColorBandToolEditor,'EEndChange',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TColorBandToolEditor.EEndChange));

RegRegisterMethod(TColorBandToolEditor,'BGradientClick',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TColorBandToolEditor.BGradientClick));

RegRegisterMethod(TColorBandToolEditor,'ETransChange',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TColorBandToolEditor.ETransChange));

RegRegisterMethod(TColorBandToolEditor,'CBDrawBehindClick',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TColorBandToolEditor.CBDrawBehindClick));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
