{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeContourEdit_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  ExtCtrls,
  ComCtrls,
  Chart,
  TeeSurfa,
  TeCanvas,
  TeePenDlg,
  TeeProcs,
  classes,
  dcscript,
  dcsystem,
  TeeContourEdit;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = _T0;

_T6 = procedure (p0 : TObject;
p1 : TMouseButton;
p2 : TShiftState;
p3 : Integer;
p4 : Integer) of object;

_T7 = _T0;

_T8 = _T0;

_T9 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TContourSeriesEditor
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TContourSeriesEditor,'FormShow',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.FormShow));

RegRegisterMethod(TContourSeriesEditor,'SENumChange',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.SENumChange));

RegRegisterMethod(TContourSeriesEditor,'CBYPosLevelClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.CBYPosLevelClick));

RegRegisterMethod(TContourSeriesEditor,'SEYPosChange',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.SEYPosChange));

RegRegisterMethod(TContourSeriesEditor,'CBColorEachClick',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.CBColorEachClick));

RegRegisterMethod(TContourSeriesEditor,'CBAutoLevelsClick',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.CBAutoLevelsClick));

RegRegisterMethod(TContourSeriesEditor,'SHColorMouseUp',TypeInfo(_T6),[
TypeInfo(TObject),
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TContourSeriesEditor.SHColorMouseUp));

RegRegisterMethod(TContourSeriesEditor,'ELevelChange',TypeInfo(_T7),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.ELevelChange));

RegRegisterMethod(TContourSeriesEditor,'EValueChange',TypeInfo(_T8),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.EValueChange));

RegRegisterMethod(TContourSeriesEditor,'FormCreate',TypeInfo(_T9),[
TypeInfo(TObject)],Addr(TContourSeriesEditor.FormCreate));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
