{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeFunnel_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  Graphics,
  TeEngine,
  Chart,
  SysUtils,
  TeCanvas,
  classes,
  dcscript,
  dcsystem,
  TeeFunnel;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function : TChartValueList of object;

_T1 = procedure (const p0 : TChartValueList) of object;

_T2 = function (const p0 : Double;
const p1 : Double;
const p2 : String;
p3 : TColor): Integer of object;

_T3 = procedure  of object;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TFunnelSeries
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TFunnelSeries,'GetQuoteValues',TypeInfo(_T0),[TypeInfo(TChartValueList)], pointer(288));

RegRegisterMethod(TFunnelSeries,'SetQuoteValues',TypeInfo(_T1),[
TypeInfo(TChartValueList)], pointer(292));

RegRegisterMethod(TFunnelSeries,'AddSegment',TypeInfo(_T2),[
TypeInfo(Double),
TypeInfo(Double),
TypeInfo(String),
TypeInfo(TColor),TypeInfo(Integer)],Addr(TFunnelSeries.AddSegment));

RegRegisterMethod(TFunnelSeries,'Recalc',TypeInfo(_T3),NoParams,Addr(TFunnelSeries.Recalc));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
