{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeeNavigator_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  ExtCtrls,
  Controls,
  Buttons,
  TeeProcs,
  Chart,
  classes,
  dcscript,
  dcsystem,
  TeeNavigator;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TChartNavigateBtn) of object;

_T1 = procedure  of object;

_T2 = _T1;

_T3 = _T1;

function __DC__GetTChartNavButton__Index(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TChartNavButton(Instance).Index;
end;

procedure __DC__SetTChartNavButton__Index(Instance : TObject; Params : PVariantArgList);
begin
TChartNavButton(Instance).Index:=OleVariant(Params^[0]);
end;

procedure __RegisterProps;
begin
RegisterProperty(TChartNavButton,'Index',__DC__GetTChartNavButton__Index,__DC__SetTChartNavButton__Index);
end;

const __ConstNames0 : array[0..10] of string = (
'ngEnabled'
,'ngDisabled'
,'nbFirst'
,'nbPrior'
,'nbNext'
,'nbLast'
,'nbInsert'
,'nbDelete'
,'nbEdit'
,'nbPost'
,'nbCancel'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,ngEnabled));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,ngDisabled));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,nbFirst));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,nbPrior));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,nbNext));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,nbLast));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,nbInsert));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,nbDelete));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,nbEdit));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,nbPost));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,nbCancel));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..2] of TClass = (
TChartNavButton,
TChartPageNavigator,
TCustomChartNavigator
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TCustomChartNavigator,'BtnClick',TypeInfo(_T0),[
TypeInfo(TChartNavigateBtn)], pointer(MinVMTOffset - 73));

RegRegisterMethod(TCustomChartNavigator,'InitButtons',TypeInfo(_T1),NoParams, pointer(184));

RegRegisterMethod(TCustomChartNavigator,'EnableButtons',TypeInfo(_T2),NoParams, pointer(188));

RegRegisterMethod(TCustomChartNavigator,'InitHints',TypeInfo(_T3),NoParams,Addr(TCustomChartNavigator.InitHints));

RegisterEvent(TypeInfo(TNotifyButtonClickedEvent),[
TypeInfo(TChartNavigateBtn)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
