{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit TeePo3DEdit_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  ExtCtrls,
  ComCtrls,
  Chart,
  Series,
  TeePoin3,
  TeCanvas,
  TeePenDlg,
  TeeProcs,
  classes,
  dcscript,
  dcsystem,
  TeePo3DEdit;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TPoint3DSeriesEditor
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TPoint3DSeriesEditor,'FormShow',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TPoint3DSeriesEditor.FormShow));

RegRegisterMethod(TPoint3DSeriesEditor,'CBColorEachClick',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TPoint3DSeriesEditor.CBColorEachClick));

RegRegisterMethod(TPoint3DSeriesEditor,'SEPointDepthChange',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TPoint3DSeriesEditor.SEPointDepthChange));

RegRegisterMethod(TPoint3DSeriesEditor,'FormCreate',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TPoint3DSeriesEditor.FormCreate));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
