unit ib_imp;

interface

uses
  ib_462,
  IBBatchMove_462,
  ibblob_462,
  IBCustomDataset_462,
  ibdatabase_462,
  ibdatabaseinfo_462,
  IBDialogs_462,
  iberrorcodes_462,
  ibevents_462,
//  ibexternals_462,
  IBExtract_462,
  ibheader_462,
  IBInstall_462,
  IBInstallHeader_462,
  IBIntf_462,
  ibquery_462,
  IBServices_462,
  ibsql_462,
  ibsqlmonitor_462,
  ibstoredproc_462,
  ibtable_462,
  ibupdatesql_462,
  ibutils_462,
  IBXconst_462;

implementation

end.
