{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit IBServices_462;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  SysUtils,
  Controls,
  Forms,
  IBDialogs,
  IBHeader,
  IB,
  IBExternals,
  classes,
  dcscript,
  dcsystem,
  IBServices;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = _T0;

_T2 = _T0;

_T3 = procedure (p0 : TShutdownMode;
p1 : Integer) of object;

_T4 = procedure (p0 : Integer) of object;

_T5 = _T4;

_T6 = _T4;

_T7 = _T0;

_T8 = _T0;

_T9 = procedure (p0 : Boolean) of object;

_T10 = _T9;

_T11 = _T9;

_T12 = function : String of object;

_T13 = _T12;

_T14 = _T0;

_T15 = _T0;

_T16 = _T0;

_T17 = _T0;

_T18 = _T0;

_T19 = _T0;

_T20 = _T0;

_T21 = procedure (p0 : String) of object;

_T22 = _T0;

_T23 = _T0;

_T24 = _T0;

_T25 = _T0;

_T26 = _T0;

_T27 = _T0;

_T28 = _T0;

_T29 = _T0;

_T30 = _T0;

_T31 = _T0;

_T32 = _T0;

_T33 = _T0;

function __DC__GetTIBControlAndQueryService__Eof(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TIBControlAndQueryService(Instance).Eof;
end;

function __DC__GetTIBControlService__IsServiceRunning(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TIBControlService(Instance).IsServiceRunning;
end;

function __DC__GetTIBCustomService__Handle(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := PointerToVariant(TIBCustomService(Instance).Handle);
end;

function __DC__GetTIBCustomService__ServiceParamBySPB(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TIBCustomService(Instance).ServiceParamBySPB[OleVariant(Params^[0])];
end;

procedure __DC__SetTIBCustomService__ServiceParamBySPB(Instance : TObject; Params : PVariantArgList);
begin
TIBCustomService(Instance).ServiceParamBySPB[OleVariant(Params^[1])]:=OleVariant(Params^[0]);
end;

function __DC__GetTIBSecurityService__UserInfo(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBSecurityService(Instance).UserInfo[OleVariant(Params^[0])]);
end;

function __DC__GetTIBSecurityService__UserInfoCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TIBSecurityService(Instance).UserInfoCount;
end;

function __DC__GetTIBServerProperties__DatabaseInfo(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBServerProperties(Instance).DatabaseInfo);
end;

function __DC__GetTIBServerProperties__LicenseInfo(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBServerProperties(Instance).LicenseInfo);
end;

function __DC__GetTIBServerProperties__LicenseMaskInfo(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBServerProperties(Instance).LicenseMaskInfo);
end;

function __DC__GetTIBServerProperties__VersionInfo(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBServerProperties(Instance).VersionInfo);
end;

function __DC__GetTIBServerProperties__ConfigParams(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBServerProperties(Instance).ConfigParams);
end;

function __DC__GetTIBValidationService__LimboTransactionInfo(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBValidationService(Instance).LimboTransactionInfo[OleVariant(Params^[0])]);
end;

function __DC__GetTIBValidationService__LimboTransactionInfoCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TIBValidationService(Instance).LimboTransactionInfoCount;
end;

procedure __RegisterProps;
begin
RegisterProperty(TIBControlAndQueryService,'Eof',__DC__GetTIBControlAndQueryService__Eof,nil);
RegisterProperty(TIBControlService,'IsServiceRunning',__DC__GetTIBControlService__IsServiceRunning,nil);
RegisterProperty(TIBCustomService,'Handle',__DC__GetTIBCustomService__Handle,nil);
RegisterIndexedProperty(TIBCustomService,'ServiceParamBySPB',1,False,__DC__GetTIBCustomService__ServiceParamBySPB,__DC__SetTIBCustomService__ServiceParamBySPB);
RegisterIndexedProperty(TIBSecurityService,'UserInfo',1,False,__DC__GetTIBSecurityService__UserInfo,nil);
RegisterProperty(TIBSecurityService,'UserInfoCount',__DC__GetTIBSecurityService__UserInfoCount,nil);
RegisterProperty(TIBServerProperties,'DatabaseInfo',__DC__GetTIBServerProperties__DatabaseInfo,nil);
RegisterProperty(TIBServerProperties,'LicenseInfo',__DC__GetTIBServerProperties__LicenseInfo,nil);
RegisterProperty(TIBServerProperties,'LicenseMaskInfo',__DC__GetTIBServerProperties__LicenseMaskInfo,nil);
RegisterProperty(TIBServerProperties,'VersionInfo',__DC__GetTIBServerProperties__VersionInfo,nil);
RegisterProperty(TIBServerProperties,'ConfigParams',__DC__GetTIBServerProperties__ConfigParams,nil);
RegisterIndexedProperty(TIBValidationService,'LimboTransactionInfo',1,False,__DC__GetTIBValidationService__LimboTransactionInfo,nil);
RegisterProperty(TIBValidationService,'LimboTransactionInfoCount',__DC__GetTIBValidationService__LimboTransactionInfoCount,nil);
end;

const __ConstNames0 : array[0..67] of string = (
'DefaultBufferSize'
,'SPBPrefix'
,'TCP'
,'SPX'
,'NamedPipe'
,'Local'
,'ByLine'
,'ByChunk'
,'Database'
,'License'
,'LicenseMask'
,'ConfigParameters'
,'Version'
,'Forced'
,'DenyTransaction'
,'DenyAttachment'
,'LicenseAdd'
,'LicenseRemove'
,'DataPages'
,'DbLog'
,'HeaderPages'
,'IndexPages'
,'SystemRelations'
,'IgnoreChecksums'
,'IgnoreLimbo'
,'MetadataOnly'
,'NoGarbageCollection'
,'OldMetadataDesc'
,'NonTransportable'
,'ConvertExtTables'
,'DeactivateIndexes'
,'NoShadow'
,'NoValidityCheck'
,'OneRelationAtATime'
,'Replace'
,'CreateNewDB'
,'UseAllSpace'
,'LimboTransactions'
,'CheckDB'
,'IgnoreChecksum'
,'KillShadows'
,'MendDB'
,'SweepDB'
,'ValidateDB'
,'ValidateFull'
,'CommitGlobal'
,'RollbackGlobal'
,'RecoverTwoPhaseGlobal'
,'NoGlobalAction'
,'LimboState'
,'CommitState'
,'RollbackState'
,'UnknownState'
,'CommitAdvise'
,'RollbackAdvise'
,'UnknownAdvise'
,'CommitAction'
,'RollbackAction'
,'ActionAddUser'
,'ActionDeleteUser'
,'ActionModifyUser'
,'ActionDisplayUser'
,'ModifyFirstName'
,'ModifyMiddleName'
,'ModifyLastName'
,'ModifyUserId'
,'ModifyGroupId'
,'ModifyPassword'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,DefaultBufferSize));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,SPBPrefix));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,TCP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,SPX));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,NamedPipe));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,Local));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,ByLine));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,ByChunk));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,Database));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,License));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,LicenseMask));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,ConfigParameters));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,Version));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,Forced));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,DenyTransaction));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,DenyAttachment));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,LicenseAdd));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,LicenseRemove));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[18] ,DataPages));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[19] ,DbLog));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[20] ,HeaderPages));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[21] ,IndexPages));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[22] ,SystemRelations));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[23] ,IgnoreChecksums));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[24] ,IgnoreLimbo));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[25] ,MetadataOnly));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[26] ,NoGarbageCollection));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[27] ,OldMetadataDesc));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[28] ,NonTransportable));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[29] ,ConvertExtTables));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[30] ,DeactivateIndexes));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[31] ,NoShadow));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[32] ,NoValidityCheck));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[33] ,OneRelationAtATime));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[34] ,Replace));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[35] ,CreateNewDB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[36] ,UseAllSpace));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[37] ,LimboTransactions));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[38] ,CheckDB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[39] ,IgnoreChecksum));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[40] ,KillShadows));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[41] ,MendDB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[42] ,SweepDB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[43] ,ValidateDB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[44] ,ValidateFull));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[45] ,CommitGlobal));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[46] ,RollbackGlobal));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[47] ,RecoverTwoPhaseGlobal));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[48] ,NoGlobalAction));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[49] ,LimboState));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[50] ,CommitState));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[51] ,RollbackState));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[52] ,UnknownState));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[53] ,CommitAdvise));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[54] ,RollbackAdvise));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[55] ,UnknownAdvise));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[56] ,CommitAction));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[57] ,RollbackAction));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[58] ,ActionAddUser));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[59] ,ActionDeleteUser));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[60] ,ActionModifyUser));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[61] ,ActionDisplayUser));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[62] ,ModifyFirstName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[63] ,ModifyMiddleName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[64] ,ModifyLastName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[65] ,ModifyUserId));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[66] ,ModifyGroupId));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[67] ,ModifyPassword));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..20] of TClass = (
TConfigFileData,
TConfigParams,
TDatabaseInfo,
TIBBackupRestoreService,
TIBBackupService,
TIBConfigService,
TIBControlAndQueryService,
TIBControlService,
TIBCustomService,
TIBLicensingService,
TIBLogService,
TIBRestoreService,
TIBSecurityService,
TIBServerProperties,
TIBStatisticalService,
TIBValidationService,
TLicenseInfo,
TLicenseMaskInfo,
TLimboTransactionInfo,
TUserInfo,
TVersionInfo
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegisterProc(TConfigFileData,'Create',mtConstructor,TypeInfo(_T0),NoParams,Addr(TConfigFileData.Create),cRegister);

RegisterProc(TConfigParams,'Create',mtConstructor,TypeInfo(_T1),NoParams,Addr(TConfigParams.Create),cRegister);

RegisterProc(TDatabaseInfo,'Create',mtConstructor,TypeInfo(_T2),NoParams,Addr(TDatabaseInfo.Create),cRegister);

RegRegisterMethod(TIBConfigService,'ShutdownDatabase',TypeInfo(_T3),[
TypeInfo(TShutdownMode),
TypeInfo(Integer)],Addr(TIBConfigService.ShutdownDatabase));

RegRegisterMethod(TIBConfigService,'SetSweepInterval',TypeInfo(_T4),[
TypeInfo(Integer)],Addr(TIBConfigService.SetSweepInterval));

RegRegisterMethod(TIBConfigService,'SetDBSqlDialect',TypeInfo(_T5),[
TypeInfo(Integer)],Addr(TIBConfigService.SetDBSqlDialect));

RegRegisterMethod(TIBConfigService,'SetPageBuffers',TypeInfo(_T6),[
TypeInfo(Integer)],Addr(TIBConfigService.SetPageBuffers));

RegRegisterMethod(TIBConfigService,'ActivateShadow',TypeInfo(_T7),NoParams,Addr(TIBConfigService.ActivateShadow));

RegRegisterMethod(TIBConfigService,'BringDatabaseOnline',TypeInfo(_T8),NoParams,Addr(TIBConfigService.BringDatabaseOnline));

RegRegisterMethod(TIBConfigService,'SetReserveSpace',TypeInfo(_T9),[
TypeInfo(Boolean)],Addr(TIBConfigService.SetReserveSpace));

RegRegisterMethod(TIBConfigService,'SetAsyncMode',TypeInfo(_T10),[
TypeInfo(Boolean)],Addr(TIBConfigService.SetAsyncMode));

RegRegisterMethod(TIBConfigService,'SetReadOnly',TypeInfo(_T11),[
TypeInfo(Boolean)],Addr(TIBConfigService.SetReadOnly));

RegRegisterMethod(TIBControlAndQueryService,'GetNextLine',TypeInfo(_T12),[TypeInfo(String)],Addr(TIBControlAndQueryService.GetNextLine));

RegRegisterMethod(TIBControlAndQueryService,'GetNextChunk',TypeInfo(_T13),[TypeInfo(String)],Addr(TIBControlAndQueryService.GetNextChunk));

RegRegisterMethod(TIBControlService,'SetServiceStartOptions',TypeInfo(_T14),NoParams, pointer(48));

RegRegisterMethod(TIBControlService,'ServiceStart',TypeInfo(_T15),NoParams, pointer(52));

RegRegisterMethod(TIBCustomService,'Attach',TypeInfo(_T16),NoParams,Addr(TIBCustomService.Attach));

RegRegisterMethod(TIBCustomService,'Detach',TypeInfo(_T17),NoParams,Addr(TIBCustomService.Detach));

RegRegisterMethod(TIBLicensingService,'AddLicense',TypeInfo(_T18),NoParams,Addr(TIBLicensingService.AddLicense));

RegRegisterMethod(TIBLicensingService,'RemoveLicense',TypeInfo(_T19),NoParams,Addr(TIBLicensingService.RemoveLicense));

RegRegisterMethod(TIBSecurityService,'DisplayUsers',TypeInfo(_T20),NoParams,Addr(TIBSecurityService.DisplayUsers));

RegRegisterMethod(TIBSecurityService,'DisplayUser',TypeInfo(_T21),[
TypeInfo(String)],Addr(TIBSecurityService.DisplayUser));

RegRegisterMethod(TIBSecurityService,'AddUser',TypeInfo(_T22),NoParams,Addr(TIBSecurityService.AddUser));

RegRegisterMethod(TIBSecurityService,'DeleteUser',TypeInfo(_T23),NoParams,Addr(TIBSecurityService.DeleteUser));

RegRegisterMethod(TIBSecurityService,'ModifyUser',TypeInfo(_T24),NoParams,Addr(TIBSecurityService.ModifyUser));

RegRegisterMethod(TIBServerProperties,'Fetch',TypeInfo(_T25),NoParams,Addr(TIBServerProperties.Fetch));

RegRegisterMethod(TIBServerProperties,'FetchDatabaseInfo',TypeInfo(_T26),NoParams,Addr(TIBServerProperties.FetchDatabaseInfo));

RegRegisterMethod(TIBServerProperties,'FetchLicenseInfo',TypeInfo(_T27),NoParams,Addr(TIBServerProperties.FetchLicenseInfo));

RegRegisterMethod(TIBServerProperties,'FetchLicenseMaskInfo',TypeInfo(_T28),NoParams,Addr(TIBServerProperties.FetchLicenseMaskInfo));

RegRegisterMethod(TIBServerProperties,'FetchConfigParams',TypeInfo(_T29),NoParams,Addr(TIBServerProperties.FetchConfigParams));

RegRegisterMethod(TIBServerProperties,'FetchVersionInfo',TypeInfo(_T30),NoParams,Addr(TIBServerProperties.FetchVersionInfo));

RegRegisterMethod(TIBValidationService,'FetchLimboTransactionInfo',TypeInfo(_T31),NoParams,Addr(TIBValidationService.FetchLimboTransactionInfo));

RegRegisterMethod(TIBValidationService,'FixLimboTransactionErrors',TypeInfo(_T32),NoParams,Addr(TIBValidationService.FixLimboTransactionErrors));

RegisterProc(TLicenseInfo,'Create',mtConstructor,TypeInfo(_T33),NoParams,Addr(TLicenseInfo.Create),cRegister);

RegisterEvent(TypeInfo(TLoginEvent),[
TypeInfo(TIBCustomService),
TypeInfo(TStrings)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
