{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit ibupdatesql_462;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  SysUtils,
  DB,
  IB,
  IBCustomDataSet,
  IBQuery,
  classes,
  dcscript,
  dcsystem,
  IBUpdateSQL;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TUpdateKind) of object;

_T1 = _T0;

function __DC__GetTIBUpdateSQL__DataSet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBUpdateSQL(Instance).DataSet);
end;

procedure __DC__SetTIBUpdateSQL__DataSet(Instance : TObject; Params : PVariantArgList);
begin
TIBUpdateSQL(Instance).DataSet:=TIBCustomDataSet(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTIBUpdateSQL__Query(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBUpdateSQL(Instance).Query[OleVariant(Params^[0])]);
end;

function __DC__GetTIBUpdateSQL__SQL(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBUpdateSQL(Instance).SQL[OleVariant(Params^[0])]);
end;

procedure __DC__SetTIBUpdateSQL__SQL(Instance : TObject; Params : PVariantArgList);
begin
TIBUpdateSQL(Instance).SQL[OleVariant(Params^[1])]:=TStrings(VarToObject(OleVariant(Params^[0])));
end;

procedure __RegisterProps;
begin
RegisterProperty(TIBUpdateSQL,'DataSet',__DC__GetTIBUpdateSQL__DataSet,__DC__SetTIBUpdateSQL__DataSet);
RegisterIndexedProperty(TIBUpdateSQL,'Query',1,False,__DC__GetTIBUpdateSQL__Query,nil);
RegisterIndexedProperty(TIBUpdateSQL,'SQL',1,False,__DC__GetTIBUpdateSQL__SQL,__DC__SetTIBUpdateSQL__SQL);
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TIBUpdateSQL
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TIBUpdateSQL,'ExecSQL',TypeInfo(_T0),[
TypeInfo(TUpdateKind)],Addr(TIBUpdateSQL.ExecSQL));

RegRegisterMethod(TIBUpdateSQL,'SetParams',TypeInfo(_T1),[
TypeInfo(TUpdateKind)],Addr(TIBUpdateSQL.SetParams));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
