{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit xlReport_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  ComObj,
  Controls,
  ActiveX,
  OleCtnrs,
  SysUtils,
  Windows,
  Forms,
  Dialogs,
  Clipbrd,
  DDEML,
  DDEMan,
  DB,
  Excel8G2,
  VBIDE8G2,
  Office8G2,
  xlcUtils,
  xlcOPack,
  xlcClasses,
  xlStdOPack,
  classes,
  dcscript,
  dcsystem,
  xlReport;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (const p0 : Integer;
const p1 : Integer): string of object;

_T1 = _T0;

_T2 = _T0;

_T3 = function (p0 : IxlRange): string of object;

_T4 = function : string of object;

_T5 = procedure (p0 : IxlApplication;
const p1 : Boolean) of object;

_T6 = function : TxlDataSource of object;

_T7 = function : TxlExcelDataSource of object;

_T8 = procedure  of object;

_T9 = procedure (var p0 : string;
var p1 : string;
p2 : Boolean) of object;

_T10 = procedure (p0 : IxlWorksheet;
p1 : IxlWorkbook;
var p2 : string) of object;

_T11 = procedure (const p0 : string;
const p1 : string) of object;

_T12 = _T8;

_T13 = procedure (p0 : OLEVariant) of object;

_T14 = _T11;

_T15 = procedure (p0 : Array of TxlExcelReport;
p1 : Array of string) of object;

_T16 = function : TxlExcelReportParam of object;

{_T17 = procedure (p0 : TComponent;
p1 : string;
p2 : string;
p3 : string;
p4 : string;
p5 : TxlReportOptionsSet;
p6 : string;
p7 : TxlReportHandleEvent;
p8 : TxlReportHandleEvent) of object;}

_T19 = _T8;

_T20 = _T8;

_T21 = _T8;

_T22 = _T13;

_T23 = function : TxlReportParam of object;

procedure __TxlExcelReport__ReportTo__Wrapper(__Instance : TObject; cArgs : integer; pArgs : PArgList);
begin
case cArgs of
1:
TxlExcelReport(__Instance).ReportTo(OleVariant(pargs^[0]));
2:
TxlExcelReport(__Instance).ReportTo(OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end
end;

function __DC__GetTxlDataSource__Report(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlDataSource(Instance).Report);
end;

function __DC__GetTxlDataSource__IXLSApp(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).IXLSApp;
end;

function __DC__GetTxlDataSource__IWorkbooks(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).IWorkbooks;
end;

function __DC__GetTxlDataSource__IWorkbook(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).IWorkbook;
end;

function __DC__GetTxlDataSource__INames(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).INames;
end;

function __DC__GetTxlDataSource__IName(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).IName;
end;

function __DC__GetTxlDataSource__IWorksheets(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).IWorksheets;
end;

function __DC__GetTxlDataSource__IWorksheet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).IWorksheet;
end;

function __DC__GetTxlDataSource__ITempSheet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).ITempSheet;
end;

function __DC__GetTxlDataSource__IRange(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).IRange;
end;

function __DC__GetTxlDataSource__MasterSource(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlDataSource(Instance).MasterSource);
end;

procedure __DC__SetTxlDataSource__MasterSource(Instance : TObject; Params : PVariantArgList);
begin
TxlDataSource(Instance).MasterSource:=TxlExcelDataSource(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTxlDataSource__RangeType(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).RangeType;
end;

function __DC__GetTxlDataSource__Row(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).Row;
end;

function __DC__GetTxlDataSource__Column(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).Column;
end;

function __DC__GetTxlDataSource__RowCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).RowCount;
end;

function __DC__GetTxlDataSource__ColCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlDataSource(Instance).ColCount;
end;

function __DC__GetTxlDataSources__Report(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlDataSources(Instance).Report);
end;

function __DC__GetTxlDataSources__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlDataSources(Instance).Items[OleVariant(Params^[0])]);
end;

procedure __DC__SetTxlDataSources__Items(Instance : TObject; Params : PVariantArgList);
begin
TxlDataSources(Instance).Items[OleVariant(Params^[1])]:=TxlDataSource(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTxlExcelDataSource__IXLSApp(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).IXLSApp;
end;

function __DC__GetTxlExcelDataSource__IWorkbooks(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).IWorkbooks;
end;

function __DC__GetTxlExcelDataSource__IWorkbook(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).IWorkbook;
end;

function __DC__GetTxlExcelDataSource__INames(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).INames;
end;

function __DC__GetTxlExcelDataSource__IName(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).IName;
end;

function __DC__GetTxlExcelDataSource__IWorksheets(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).IWorksheets;
end;

function __DC__GetTxlExcelDataSource__IWorksheet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).IWorksheet;
end;

function __DC__GetTxlExcelDataSource__ITempSheet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).ITempSheet;
end;

function __DC__GetTxlExcelDataSource__IRange(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelDataSource(Instance).IRange;
end;

function __DC__GetTxlExcelDataSources__Report(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlExcelDataSources(Instance).Report);
end;

function __DC__GetTxlExcelDataSources__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlExcelDataSources(Instance).Items[OleVariant(Params^[0])]);
end;

procedure __DC__SetTxlExcelDataSources__Items(Instance : TObject; Params : PVariantArgList);
begin
TxlExcelDataSources(Instance).Items[OleVariant(Params^[1])]:=TxlExcelDataSource(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTxlExcelReport__Options(Instance : TObject; Params : PVariantArgList) : OleVariant;
var
  tmp : TxlReportOptionsSet;
begin
tmp := TxlExcelReport(Instance).Options;
result := VarFromSet(tmp, sizeof(tmp));
end;

procedure __DC__SetTxlExcelReport__Options(Instance : TObject; Params : PVariantArgList);
var
  tmp : TxlReportOptionsSet;
begin
VarToSet(tmp, sizeof(tmp), Variant(Params^[0]));
TxlExcelReport(Instance).Options:=tmp;
end;

function __DC__GetTxlExcelReport__IXLSApp(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelReport(Instance).IXLSApp;
end;

function __DC__GetTxlExcelReport__IWorkbooks(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelReport(Instance).IWorkbooks;
end;

function __DC__GetTxlExcelReport__IWorkbook(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelReport(Instance).IWorkbook;
end;

function __DC__GetTxlExcelReport__INames(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelReport(Instance).INames;
end;

function __DC__GetTxlExcelReport__IWorksheets(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelReport(Instance).IWorksheets;
end;

function __DC__GetTxlExcelReport__ITempSheet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelReport(Instance).ITempSheet;
end;

function __DC__GetTxlExcelReport__IWorksheetFunction(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelReport(Instance).IWorksheetFunction;
end;

function __DC__GetTxlExcelReport__IModule(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlExcelReport(Instance).IModule;
end;

function __DC__GetTxlExcelReportParams__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlExcelReportParams(Instance).Items[OleVariant(Params^[0])]);
end;

procedure __DC__SetTxlExcelReportParams__Items(Instance : TObject; Params : PVariantArgList);
begin
TxlExcelReportParams(Instance).Items[OleVariant(Params^[1])]:=TxlExcelReportParam(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTxlExcelReportParams__Report(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlExcelReportParams(Instance).Report);
end;

function __DC__GetTxlReport__IXLSApp(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).IXLSApp;
end;

function __DC__GetTxlReport__IWorkbooks(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).IWorkbooks;
end;

function __DC__GetTxlReport__IWorkbook(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).IWorkbook;
end;

function __DC__GetTxlReport__INames(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).INames;
end;

function __DC__GetTxlReport__IWorksheets(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).IWorksheets;
end;

function __DC__GetTxlReport__ITempSheet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).ITempSheet;
end;

function __DC__GetTxlReport__IWorksheetFunction(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).IWorksheetFunction;
end;

function __DC__GetTxlReport__IModule(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).IModule;
end;

function __DC__GetTxlReport__Debug(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TxlReport(Instance).Debug;
end;

procedure __DC__SetTxlReport__Debug(Instance : TObject; Params : PVariantArgList);
begin
TxlReport(Instance).Debug:=OleVariant(Params^[0]);
end;

function __DC__GetTxlReport__ParamByName(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlReport(Instance).ParamByName[OleVariant(Params^[0])]);
end;

function __DC__GetTxlReportParam__Report(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlReportParam(Instance).Report);
end;

function __DC__GetTxlReportParams__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlReportParams(Instance).Items[OleVariant(Params^[0])]);
end;

procedure __DC__SetTxlReportParams__Items(Instance : TObject; Params : PVariantArgList);
begin
TxlReportParams(Instance).Items[OleVariant(Params^[1])]:=TxlReportParam(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTxlReportParams__Report(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TxlReportParams(Instance).Report);
end;

procedure __RegisterProps;
begin
RegisterProperty(TxlDataSource,'Report',__DC__GetTxlDataSource__Report,nil);
RegisterProperty(TxlDataSource,'IXLSApp',__DC__GetTxlDataSource__IXLSApp,nil);
RegisterProperty(TxlDataSource,'IWorkbooks',__DC__GetTxlDataSource__IWorkbooks,nil);
RegisterProperty(TxlDataSource,'IWorkbook',__DC__GetTxlDataSource__IWorkbook,nil);
RegisterProperty(TxlDataSource,'INames',__DC__GetTxlDataSource__INames,nil);
RegisterProperty(TxlDataSource,'IName',__DC__GetTxlDataSource__IName,nil);
RegisterProperty(TxlDataSource,'IWorksheets',__DC__GetTxlDataSource__IWorksheets,nil);
RegisterProperty(TxlDataSource,'IWorksheet',__DC__GetTxlDataSource__IWorksheet,nil);
RegisterProperty(TxlDataSource,'ITempSheet',__DC__GetTxlDataSource__ITempSheet,nil);
RegisterProperty(TxlDataSource,'IRange',__DC__GetTxlDataSource__IRange,nil);
RegisterProperty(TxlDataSource,'MasterSource',__DC__GetTxlDataSource__MasterSource,__DC__SetTxlDataSource__MasterSource);
RegisterProperty(TxlDataSource,'RangeType',__DC__GetTxlDataSource__RangeType,nil);
RegisterProperty(TxlDataSource,'Row',__DC__GetTxlDataSource__Row,nil);
RegisterProperty(TxlDataSource,'Column',__DC__GetTxlDataSource__Column,nil);
RegisterProperty(TxlDataSource,'RowCount',__DC__GetTxlDataSource__RowCount,nil);
RegisterProperty(TxlDataSource,'ColCount',__DC__GetTxlDataSource__ColCount,nil);
RegisterProperty(TxlDataSources,'Report',__DC__GetTxlDataSources__Report,nil);
RegisterIndexedProperty(TxlDataSources,'Items',1,True,__DC__GetTxlDataSources__Items,__DC__SetTxlDataSources__Items);
RegisterProperty(TxlExcelDataSource,'IXLSApp',__DC__GetTxlExcelDataSource__IXLSApp,nil);
RegisterProperty(TxlExcelDataSource,'IWorkbooks',__DC__GetTxlExcelDataSource__IWorkbooks,nil);
RegisterProperty(TxlExcelDataSource,'IWorkbook',__DC__GetTxlExcelDataSource__IWorkbook,nil);
RegisterProperty(TxlExcelDataSource,'INames',__DC__GetTxlExcelDataSource__INames,nil);
RegisterProperty(TxlExcelDataSource,'IName',__DC__GetTxlExcelDataSource__IName,nil);
RegisterProperty(TxlExcelDataSource,'IWorksheets',__DC__GetTxlExcelDataSource__IWorksheets,nil);
RegisterProperty(TxlExcelDataSource,'IWorksheet',__DC__GetTxlExcelDataSource__IWorksheet,nil);
RegisterProperty(TxlExcelDataSource,'ITempSheet',__DC__GetTxlExcelDataSource__ITempSheet,nil);
RegisterProperty(TxlExcelDataSource,'IRange',__DC__GetTxlExcelDataSource__IRange,nil);
RegisterProperty(TxlExcelDataSources,'Report',__DC__GetTxlExcelDataSources__Report,nil);
RegisterIndexedProperty(TxlExcelDataSources,'Items',1,True,__DC__GetTxlExcelDataSources__Items,__DC__SetTxlExcelDataSources__Items);
RegisterProperty(TxlExcelReport,'Options',__DC__GetTxlExcelReport__Options,__DC__SetTxlExcelReport__Options);
RegisterProperty(TxlExcelReport,'IXLSApp',__DC__GetTxlExcelReport__IXLSApp,nil);
RegisterProperty(TxlExcelReport,'IWorkbooks',__DC__GetTxlExcelReport__IWorkbooks,nil);
RegisterProperty(TxlExcelReport,'IWorkbook',__DC__GetTxlExcelReport__IWorkbook,nil);
RegisterProperty(TxlExcelReport,'INames',__DC__GetTxlExcelReport__INames,nil);
RegisterProperty(TxlExcelReport,'IWorksheets',__DC__GetTxlExcelReport__IWorksheets,nil);
RegisterProperty(TxlExcelReport,'ITempSheet',__DC__GetTxlExcelReport__ITempSheet,nil);
RegisterProperty(TxlExcelReport,'IWorksheetFunction',__DC__GetTxlExcelReport__IWorksheetFunction,nil);
RegisterProperty(TxlExcelReport,'IModule',__DC__GetTxlExcelReport__IModule,nil);
RegisterIndexedProperty(TxlExcelReportParams,'Items',1,True,__DC__GetTxlExcelReportParams__Items,__DC__SetTxlExcelReportParams__Items);
RegisterProperty(TxlExcelReportParams,'Report',__DC__GetTxlExcelReportParams__Report,nil);
RegisterProperty(TxlReport,'IXLSApp',__DC__GetTxlReport__IXLSApp,nil);
RegisterProperty(TxlReport,'IWorkbooks',__DC__GetTxlReport__IWorkbooks,nil);
RegisterProperty(TxlReport,'IWorkbook',__DC__GetTxlReport__IWorkbook,nil);
RegisterProperty(TxlReport,'INames',__DC__GetTxlReport__INames,nil);
RegisterProperty(TxlReport,'IWorksheets',__DC__GetTxlReport__IWorksheets,nil);
RegisterProperty(TxlReport,'ITempSheet',__DC__GetTxlReport__ITempSheet,nil);
RegisterProperty(TxlReport,'IWorksheetFunction',__DC__GetTxlReport__IWorksheetFunction,nil);
RegisterProperty(TxlReport,'IModule',__DC__GetTxlReport__IModule,nil);
RegisterProperty(TxlReport,'Debug',__DC__GetTxlReport__Debug,__DC__SetTxlReport__Debug);
RegisterIndexedProperty(TxlReport,'ParamByName',1,False,__DC__GetTxlReport__ParamByName,nil);
RegisterProperty(TxlReportParam,'Report',__DC__GetTxlReportParam__Report,nil);
RegisterIndexedProperty(TxlReportParams,'Items',1,True,__DC__GetTxlReportParams__Items,__DC__SetTxlReportParams__Items);
RegisterProperty(TxlReportParams,'Report',__DC__GetTxlReportParams__Report,nil);
end;

function __DC__GetxlReport__xlrExcelVer(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := xlReport.xlrExcelVer;
end;

procedure __DC__SetxlReport__xlrExcelVer(Instance : TObject; Params : PVariantArgList);
begin
xlReport.xlrExcelVer:=OleVariant(Params^[0]);
end;

function __DC__GetxlReport__xlrLCID(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := xlReport.xlrLCID;
end;

procedure __DC__SetxlReport__xlrLCID(Instance : TObject; Params : PVariantArgList);
begin
xlReport.xlrLCID:=OleVariant(Params^[0]);
end;

function __DC__GetxlReport__xlrDebug(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := xlReport.xlrDebug;
end;

procedure __DC__SetxlReport__xlrDebug(Instance : TObject; Params : PVariantArgList);
begin
xlReport.xlrDebug:=OleVariant(Params^[0]);
end;

function __DC__GetxlReport__xlrLocaleR(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := xlReport.xlrLocaleR;
end;

procedure __DC__SetxlReport__xlrLocaleR(Instance : TObject; Params : PVariantArgList);
begin
xlReport.xlrLocaleR:=OleVariant(Params^[0]);
end;

function __DC__GetxlReport__xlrLocaleC(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := xlReport.xlrLocaleC;
end;

procedure __DC__SetxlReport__xlrLocaleC(Instance : TObject; Params : PVariantArgList);
begin
xlReport.xlrLocaleC:=OleVariant(Params^[0]);
end;

var __RegisteredVars : TList;
procedure __RegisterVars;
begin
__RegisteredVars := TList.Create;
__RegisteredVars.Add(RegisterVar('xlrExcelVer',__DC__GetxlReport__xlrExcelVer,__DC__SetxlReport__xlrExcelVer));
__RegisteredVars.Add(RegisterVar('xlrLCID',__DC__GetxlReport__xlrLCID,__DC__SetxlReport__xlrLCID));
__RegisteredVars.Add(RegisterVar('xlrDebug',__DC__GetxlReport__xlrDebug,__DC__SetxlReport__xlrDebug));
__RegisteredVars.Add(RegisterVar('xlrLocaleR',__DC__GetxlReport__xlrLocaleR,__DC__SetxlReport__xlrLocaleR));
__RegisteredVars.Add(RegisterVar('xlrLocaleC',__DC__GetxlReport__xlrLocaleC,__DC__SetxlReport__xlrLocaleC));
end;

procedure __UnregisterVars;
begin
__RegisteredVars.Free;
end;

const __ConstNames0 : array[0..28] of string = (
'xroOptimizeLaunch'
,'xroNewInstance'
,'xroDisplayAlerts'
,'xroAddToMRU'
,'xroAutoSave'
,'xroUseTemp'
,'xroAutoOpen'
,'xroAutoClose'
,'xroHideExcel'
,'xroSaveClipboard'
,'xroRefreshParams'
,'xrgoAutoOpen'
,'xrgoAutoClose'
,'xrgoPreserveRowHeight'
,'xdmCSV'
,'xdmVariant'
,'xdmDDE'
,'xlrProductName'
,'xlrVersionAddStr'
,'xlrIDEVer'
,'xlrProductID'
,'xlrHomeURL'
,'xlrVersionHi'
,'xlrVersionLo'
,'xlrVersionBuild'
,'xlrMultisheet'
,'xlrSetFilter'
,'xlrModuleName'
,'vbCR'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,xroOptimizeLaunch));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,xroNewInstance));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,xroDisplayAlerts));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,xroAddToMRU));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,xroAutoSave));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,xroUseTemp));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,xroAutoOpen));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,xroAutoClose));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,xroHideExcel));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,xroSaveClipboard));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,xroRefreshParams));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,xrgoAutoOpen));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,xrgoAutoClose));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,xrgoPreserveRowHeight));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,xdmCSV));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,xdmVariant));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,xdmDDE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,xlrProductName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[18] ,xlrVersionAddStr));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[19] ,xlrIDEVer));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[20] ,xlrProductID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[21] ,xlrHomeURL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[22] ,xlrVersionHi));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[23] ,xlrVersionLo));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[24] ,xlrVersionBuild));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[25] ,xlrMultisheet));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[26] ,xlrSetFilter));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[27] ,xlrModuleName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[28] ,vbCR));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..9] of TClass = (
TxlDataSource,
TxlDataSources,
TxlExcelDataSource,
TxlExcelDataSources,
TxlExcelReport,
TxlExcelReportParam,
TxlExcelReportParams,
TxlReport,
TxlReportParam,
TxlReportParams
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..5] of string = (
'A1'
,'A1Abs'
,'R1C1'
,'R1C1OfRange'
,'xlrVersionStr'
,'BeforeRunMacro'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(string)],Addr(A1),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(string)],Addr(A1Abs),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(string)],Addr(R1C1),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[
TypeInfo(IxlRange),TypeInfo(string)],Addr(R1C1OfRange),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[TypeInfo(string)],Addr(xlrVersionStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[5],mtProc,TypeInfo(_T5),[
TypeInfo(IxlApplication),
TypeInfo(Boolean)],Addr(BeforeRunMacro),cRegister));

RegRegisterMethod(TxlDataSources,'Add',TypeInfo(_T6),[TypeInfo(TxlDataSource)],Addr(TxlDataSources.Add));

RegRegisterMethod(TxlExcelDataSources,'Add',TypeInfo(_T7),[TypeInfo(TxlExcelDataSource)],Addr(TxlExcelDataSources.Add));

RegRegisterMethod(TxlExcelReport,'SaveInTempFile',TypeInfo(_T8),NoParams, pointer(128));

RegRegisterMethod(TxlExcelReport,'DoOnBeforeWorkbookSave',TypeInfo(_T9),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(Boolean)], pointer(132));

RegRegisterMethod(TxlExcelReport,'DoOnTargetBookSheetName',TypeInfo(_T10),[
TypeInfo(IxlWorksheet),
TypeInfo(IxlWorkbook),
TypeInfo(string)], pointer(136));

RegRegisterMethod(TxlExcelReport,'MultisheetReport',TypeInfo(_T11),[
TypeInfo(string),
TypeInfo(string)], pointer(140));

RegisterProc(TxlExcelReport,'ReleaseExcelApplication',mtClassMethod,TypeInfo(_T12),NoParams,Addr(TxlExcelReport.ReleaseExcelApplication),cRegister);

RegisterProc(TxlExcelReport,'ConnectToExcelApplication',mtClassMethod,TypeInfo(_T13),[
TypeInfo(OLEVariant)],Addr(TxlExcelReport.ConnectToExcelApplication),cRegister);

RegisterProc(TxlExcelReport,'ReportTo',mtScriptMethod,TypeInfo(_T14),[
TypeInfo(string),
TypeInfo(string)],Addr(__TxlExcelReport__ReportTo__Wrapper),cRegister);

RegisterProc(TxlExcelReport,'MergeReports',mtClassMethod,TypeInfo(_T15),[
ArrayInfo(TypeInfo(TxlExcelReport)),
ArrayInfo(TypeInfo(string))], pointer(148),cRegister);

RegRegisterMethod(TxlExcelReportParams,'Add',TypeInfo(_T16),[TypeInfo(TxlExcelReportParam)],Addr(TxlExcelReportParams.Add));

RegRegisterMethod(TxlReport,'Report',TypeInfo(_T19),NoParams,Addr(TxlReport.Report));

RegRegisterMethod(TxlReport,'Edit',TypeInfo(_T20),NoParams,Addr(TxlReport.Edit));

RegisterProc(TxlReport,'ReleaseExcelApplication',mtClassMethod,TypeInfo(_T21),NoParams,Addr(TxlReport.ReleaseExcelApplication),cRegister);

RegisterProc(TxlReport,'ConnectToExcelApplication',mtClassMethod,TypeInfo(_T22),[
TypeInfo(OLEVariant)],Addr(TxlReport.ConnectToExcelApplication),cRegister);

RegRegisterMethod(TxlReportParams,'Add',TypeInfo(_T23),[TypeInfo(TxlReportParam)],Addr(TxlReportParams.Add));

{RegisterProc(TxlReport,'CreateEx',mtConstructor,TypeInfo(_T17),[
TypeInfo(TComponent),
TypeInfo(string),
TypeInfo(string),
TypeInfo(string),
TypeInfo(string),
TypeInfo(TxlReportOptionsSet),
TypeInfo(string),
TypeInfo(TxlReportHandleEvent),
TypeInfo(TxlReportHandleEvent)], pointer(152),cRegister)}

RegisterEvent(TypeInfo(TxlDataTransferHandleEvent),[
TypeInfo(TxlDataSource)]);

RegisterEvent(TypeInfo(TxlGetDataSourceInfo),[
TypeInfo(TxlDataSource),
TypeInfo(Integer)]);

RegisterEvent(TypeInfo(TxlGetFieldInfo),[
TypeInfo(TxlDataSource),
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(TxlDataType)]);

RegisterEvent(TypeInfo(TxlGetRecord),[
TypeInfo(TxlDataSource),
TypeInfo(Integer),
TypeInfo(OLEVariant),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TxlOnBeforeWorkbookSave),[
TypeInfo(TxlReport),
TypeInfo(string),
TypeInfo(string),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TxlOnMacro),[
TypeInfo(TxlReport),
TypeInfo(TxlDataSource),
TypeInfo(TxlMacroType),
TypeInfo(string),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant),
TypeInfo(OLEVariant)]);

RegisterEvent(TypeInfo(TxlOnProgress),[
TypeInfo(TxlReport),
TypeInfo(Integer),
TypeInfo(Integer)]);

RegisterEvent(TypeInfo(TxlOnTargetBookSheetName),[
TypeInfo(TxlReport),
TypeInfo(IxlWorksheet),
TypeInfo(IxlWorkbook),
TypeInfo(string)]);

RegisterEvent(TypeInfo(TxlReportHandleEvent),[
TypeInfo(TxlReport)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
__RegisterVars;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnRegisterVars;
__UnregisterProcs;
end.
