{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit CLIPICON_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  SysUtils,
  Graphics,
  Controls,
  classes,
  dcscript,
  dcsystem,
  ClipIcon;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TIcon;
p1 : TColor) of object;

_T1 = procedure (p0 : TIcon) of object;

_T2 = function : TIcon of object;

_T3 = procedure (p0 : HIcon;
var p1 : Integer;
var p2 : Integer) of object;

_T4 = function (p0 : TIcon): HIcon of object;

_T5 = procedure (p0 : TCanvas;
p1 : TIcon;
p2 : Integer;
p3 : Integer) of object;

procedure __RegisterProps;
begin
end;

function __DC__GetClipIcon__CF_ICON(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := ClipIcon.CF_ICON;
end;

procedure __DC__SetClipIcon__CF_ICON(Instance : TObject; Params : PVariantArgList);
begin
ClipIcon.CF_ICON:=OleVariant(Params^[0]);
end;

var __RegisteredVars : TList;
procedure __RegisterVars;
begin
__RegisteredVars := TList.Create;
__RegisteredVars.Add(RegisterVar('CF_ICON',__DC__GetClipIcon__CF_ICON,__DC__SetClipIcon__CF_ICON));
end;

procedure __UnregisterVars;
begin
__RegisteredVars.Free;
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..5] of string = (
'CopyIconToClipboard'
,'AssignClipboardIcon'
,'CreateIconFromClipboard'
,'GetIconSize'
,'CreateRealSizeIcon'
,'DrawRealSizeIcon'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TIcon),
TypeInfo(TColor)],Addr(CopyIconToClipboard),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(TIcon)],Addr(AssignClipboardIcon),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[TypeInfo(TIcon)],Addr(CreateIconFromClipboard),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[
TypeInfo(HIcon),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(GetIconSize),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[
TypeInfo(TIcon),TypeInfo(HIcon)],Addr(CreateRealSizeIcon),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[5],mtProc,TypeInfo(_T5),[
TypeInfo(TCanvas),
TypeInfo(TIcon),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(DrawRealSizeIcon),cRegister));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
__RegisterVars;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnRegisterVars;
__UnregisterProcs;
end.
