{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit DATEUTIL_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  classes,
  dcscript,
  dcsystem,
  DateUtil;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function : Word of object;

_T1 = function (p0 : Integer): Boolean of object;

_T2 = function (p0 : Integer;
p1 : Integer): Integer of object;

_T3 = function : TDateTime of object;

_T4 = _T3;

_T5 = _T3;

_T6 = function (p0 : TDateTime): Word of object;

_T7 = _T6;

_T8 = _T6;

_T9 = function (p0 : TDateTime;
p1 : Integer;
p2 : Integer;
p3 : Integer): TDateTime of object;

_T10 = function (p0 : TDateTime;
p1 : Integer): TDateTime of object;

_T11 = _T10;

_T12 = _T10;

_T13 = function (p0 : TDateTime): Boolean of object;

_T14 = procedure (p0 : TDateTime;
p1 : TDateTime;
var p2 : Word;
var p3 : Word;
var p4 : Word) of object;

_T15 = function (p0 : TDateTime;
p1 : TDateTime): Double of object;

_T16 = function (p0 : TDateTime;
p1 : TDateTime): Longint of object;

_T17 = _T16;

_T18 = function (p0 : TDateTime;
p1 : Integer;
p2 : Integer;
p3 : Integer;
p4 : Integer): TDateTime of object;

_T19 = _T10;

_T20 = _T10;

_T21 = _T10;

_T22 = _T10;

_T23 = function (p0 : TDateTime): TDateTime of object;

_T24 = function (const p0 : string): TDateOrder of object;

_T25 = function (const p0 : string;
p1 : Byte): Byte of object;

_T26 = function (const p0 : string;
p1 : TDateTime): TDateTime of object;

_T27 = function (const p0 : string;
const p1 : string): TDateTime of object;

_T28 = function (const p0 : string;
const p1 : string;
p2 : TDateTime): TDateTime of object;

_T29 = function (p0 : Boolean): string of object;

_T30 = function (p0 : Char;
p1 : Boolean): string of object;

_T31 = function (p0 : TDateTime): string of object;

_T32 = _T31;

procedure __RegisterProps;
begin
end;

function __DC__GetDateUtil__FourDigitYear(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := DateUtil.FourDigitYear;
end;

procedure __DC__SetDateUtil__FourDigitYear(Instance : TObject; Params : PVariantArgList);
begin
DateUtil.FourDigitYear:=OleVariant(Params^[0]);
end;

var __RegisteredVars : TList;
procedure __RegisterVars;
begin
__RegisteredVars := TList.Create;
__RegisteredVars.Add(RegisterVar('FourDigitYear',__DC__GetDateUtil__FourDigitYear,__DC__SetDateUtil__FourDigitYear));
end;

procedure __UnregisterVars;
begin
__RegisteredVars.Free;
end;

const __ConstNames0 : array[0..12] of string = (
'doMDY'
,'doDMY'
,'doYMD'
,'Sun'
,'Mon'
,'Tue'
,'Wed'
,'Thu'
,'Fri'
,'Sat'
,'DefaultDateOrder'
,'CenturyOffset'
,'NullDate'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,doMDY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,doDMY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,doYMD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,Sun));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,Mon));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,Tue));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,Wed));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,Thu));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,Fri));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,Sat));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,DefaultDateOrder));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,CenturyOffset));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,NullDate));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..32] of string = (
'CurrentYear'
,'IsLeapYear'
,'DaysPerMonth'
,'FirstDayOfPrevMonth'
,'LastDayOfPrevMonth'
,'FirstDayOfNextMonth'
,'ExtractDay'
,'ExtractMonth'
,'ExtractYear'
,'IncDate'
,'IncDay'
,'IncMonth'
,'IncYear'
,'ValidDate'
,'DateDiff'
,'MonthsBetween'
,'DaysInPeriod'
,'DaysBetween'
,'IncTime'
,'IncHour'
,'IncMinute'
,'IncSecond'
,'IncMSec'
,'CutTime'
,'GetDateOrder'
,'MonthFromName'
,'StrToDateDef'
,'StrToDateFmt'
,'StrToDateFmtDef'
,'DefDateFormat'
,'DefDateMask'
,'FormatLongDate'
,'FormatLongDateTime'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[TypeInfo(Word)],Addr(CurrentYear),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(Integer),TypeInfo(Boolean)],Addr(IsLeapYear),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(Integer)],Addr(DaysPerMonth),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[TypeInfo(TDateTime)],Addr(FirstDayOfPrevMonth),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[TypeInfo(TDateTime)],Addr(LastDayOfPrevMonth),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[5],mtProc,TypeInfo(_T5),[TypeInfo(TDateTime)],Addr(FirstDayOfNextMonth),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[6],mtProc,TypeInfo(_T6),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(ExtractDay),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[7],mtProc,TypeInfo(_T7),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(ExtractMonth),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[8],mtProc,TypeInfo(_T8),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(ExtractYear),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[9],mtProc,TypeInfo(_T9),[
TypeInfo(TDateTime),
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncDate),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[10],mtProc,TypeInfo(_T10),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncDay),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[11],mtProc,TypeInfo(_T11),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncMonth),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[12],mtProc,TypeInfo(_T12),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncYear),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[13],mtProc,TypeInfo(_T13),[
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(ValidDate),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[14],mtProc,TypeInfo(_T14),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word)],Addr(DateDiff),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[15],mtProc,TypeInfo(_T15),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(MonthsBetween),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[16],mtProc,TypeInfo(_T16),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Longint)],Addr(DaysInPeriod),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[17],mtProc,TypeInfo(_T17),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Longint)],Addr(DaysBetween),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[18],mtProc,TypeInfo(_T18),[
TypeInfo(TDateTime),
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncTime),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[19],mtProc,TypeInfo(_T19),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncHour),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[20],mtProc,TypeInfo(_T20),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncMinute),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[21],mtProc,TypeInfo(_T21),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncSecond),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[22],mtProc,TypeInfo(_T22),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(IncMSec),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[23],mtProc,TypeInfo(_T23),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(CutTime),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[24],mtProc,TypeInfo(_T24),[
TypeInfo(string),TypeInfo(TDateOrder)],Addr(GetDateOrder),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[25],mtProc,TypeInfo(_T25),[
TypeInfo(string),
TypeInfo(Byte),TypeInfo(Byte)],Addr(MonthFromName),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[26],mtProc,TypeInfo(_T26),[
TypeInfo(string),
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(StrToDateDef),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[27],mtProc,TypeInfo(_T27),[
TypeInfo(string),
TypeInfo(string),TypeInfo(TDateTime)],Addr(StrToDateFmt),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[28],mtProc,TypeInfo(_T28),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(StrToDateFmtDef),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[29],mtProc,TypeInfo(_T29),[
TypeInfo(Boolean),TypeInfo(string)],Addr(DefDateFormat),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[30],mtProc,TypeInfo(_T30),[
TypeInfo(Char),
TypeInfo(Boolean),TypeInfo(string)],Addr(DefDateMask),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[31],mtProc,TypeInfo(_T31),[
TypeInfo(TDateTime),TypeInfo(string)],Addr(FormatLongDate),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[32],mtProc,TypeInfo(_T32),[
TypeInfo(TDateTime),TypeInfo(string)],Addr(FormatLongDateTime),cRegister));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
__RegisterVars;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnRegisterVars;
__UnregisterProcs;
end.
