{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit DBSECUR_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  SysUtils,
  Windows,
  Messages,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  DB,
  DBTables,
  RxLogin,
  LoginDlg,
  ChPswDlg,
  classes,
  dcscript,
  dcsystem,
  DBSecur;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (p0 : TTable;
const p1 : string;
const p2 : string): Boolean of object;

_T1 = function : Boolean of object;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TDBSecurity
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TDBSecurity,'DoCheckUser',TypeInfo(_T0),[
TypeInfo(TTable),
TypeInfo(string),
TypeInfo(string),TypeInfo(Boolean)], pointer(MinVMTOffset - 19));

RegRegisterMethod(TDBSecurity,'ChangePassword',TypeInfo(_T1),[TypeInfo(Boolean)],Addr(TDBSecurity.ChangePassword));

RegisterEvent(TypeInfo(TCheckUserEvent),[
TypeInfo(TTable),
TypeInfo(string),TypeInfo(Boolean)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
