{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit GIFCTRL_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Messages,
  Windows,
  SysUtils,
  Graphics,
  Controls,
  Forms,
  StdCtrls,
  Menus,
  ExtCtrls,
  Animate,
  RxGIF,
  RxTimer,
  classes,
  dcscript,
  dcsystem,
  GIFCtrl;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TRxGIFAnimator
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TRxGIFAnimator,'Change',TypeInfo(_T0),NoParams, pointer(MinVMTOffset - 50));

RegRegisterMethod(TRxGIFAnimator,'FrameChanged',TypeInfo(_T1),NoParams, pointer(MinVMTOffset - 51));

RegRegisterMethod(TRxGIFAnimator,'Start',TypeInfo(_T2),NoParams, pointer(MinVMTOffset - 52));

RegRegisterMethod(TRxGIFAnimator,'Stop',TypeInfo(_T3),NoParams, pointer(MinVMTOffset - 53));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
