{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit MRULIST_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  SysUtils,
  Menus,
  IniFiles,
  Registry,
  Placemnt,
  classes,
  dcscript,
  dcsystem,
  MRUList;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = procedure (p0 : TObject;
const p1 : string;
p2 : Integer;
var p3 : string;
var p4 : Longint) of object;

_T2 = procedure (p0 : TObject;
const p1 : string;
p2 : Integer;
const p3 : string;
p4 : Longint) of object;

_T3 = procedure (var p0 : string;
var p1 : TShortCut;
p2 : Longint) of object;

_T4 = procedure (const p0 : string;
const p1 : string;
p2 : Longint) of object;

_T5 = procedure (const p0 : string;
p1 : Longint) of object;

_T6 = _T0;

_T7 = procedure (const p0 : string) of object;

_T8 = _T0;

_T9 = procedure (p0 : TRegIniFile;
const p1 : string) of object;

_T10 = _T9;

_T11 = procedure (p0 : TIniFile;
const p1 : string) of object;

_T12 = _T11;

_T13 = _T0;

_T14 = _T0;

_T15 = _T7;

function __DC__GetTMRUManager__Strings(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TMRUManager(Instance).Strings);
end;

function __DC__GetTRecentStrings__MaxSize(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TRecentStrings(Instance).MaxSize;
end;

procedure __DC__SetTRecentStrings__MaxSize(Instance : TObject; Params : PVariantArgList);
begin
TRecentStrings(Instance).MaxSize:=OleVariant(Params^[0]);
end;

function __DC__GetTRecentStrings__Mode(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TRecentStrings(Instance).Mode;
end;

procedure __DC__SetTRecentStrings__Mode(Instance : TObject; Params : PVariantArgList);
begin
TRecentStrings(Instance).Mode:=OleVariant(Params^[0]);
end;

procedure __RegisterProps;
begin
RegisterProperty(TMRUManager,'Strings',__DC__GetTMRUManager__Strings,nil);
RegisterProperty(TRecentStrings,'MaxSize',__DC__GetTRecentStrings__MaxSize,__DC__SetTRecentStrings__MaxSize);
RegisterProperty(TRecentStrings,'Mode',__DC__GetTRecentStrings__Mode,__DC__SetTRecentStrings__Mode);
end;

const __ConstNames0 : array[0..3] of string = (
'adTab'
,'adSpace'
,'rmInsert'
,'rmAppend'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,adTab));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,adSpace));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,rmInsert));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,rmAppend));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..1] of TClass = (
TMRUManager,
TRecentStrings
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TMRUManager,'Change',TypeInfo(_T0),NoParams, pointer(MinVMTOffset - 15));

RegRegisterMethod(TMRUManager,'DoReadItem',TypeInfo(_T1),[
TypeInfo(TObject),
TypeInfo(string),
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(Longint)], pointer(MinVMTOffset - 16));

RegRegisterMethod(TMRUManager,'DoWriteItem',TypeInfo(_T2),[
TypeInfo(TObject),
TypeInfo(string),
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(Longint)], pointer(MinVMTOffset - 17));

RegRegisterMethod(TMRUManager,'GetItemData',TypeInfo(_T3),[
TypeInfo(string),
TypeInfo(TShortCut),
TypeInfo(Longint)], pointer(MinVMTOffset - 18));

RegRegisterMethod(TMRUManager,'DoClick',TypeInfo(_T4),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(Longint)], pointer(MinVMTOffset - 19));

RegRegisterMethod(TMRUManager,'Add',TypeInfo(_T5),[
TypeInfo(string),
TypeInfo(Longint)],Addr(TMRUManager.Add));

RegRegisterMethod(TMRUManager,'Clear',TypeInfo(_T6),NoParams,Addr(TMRUManager.Clear));

RegRegisterMethod(TMRUManager,'Remove',TypeInfo(_T7),[
TypeInfo(string)],Addr(TMRUManager.Remove));

RegRegisterMethod(TMRUManager,'UpdateRecentMenu',TypeInfo(_T8),NoParams,Addr(TMRUManager.UpdateRecentMenu));

RegRegisterMethod(TMRUManager,'LoadFromRegistry',TypeInfo(_T9),[
TypeInfo(TRegIniFile),
TypeInfo(string)],Addr(TMRUManager.LoadFromRegistry));

RegRegisterMethod(TMRUManager,'SaveToRegistry',TypeInfo(_T10),[
TypeInfo(TRegIniFile),
TypeInfo(string)],Addr(TMRUManager.SaveToRegistry));

RegRegisterMethod(TMRUManager,'LoadFromIni',TypeInfo(_T11),[
TypeInfo(TIniFile),
TypeInfo(string)],Addr(TMRUManager.LoadFromIni));

RegRegisterMethod(TMRUManager,'SaveToIni',TypeInfo(_T12),[
TypeInfo(TIniFile),
TypeInfo(string)],Addr(TMRUManager.SaveToIni));

RegisterProc(TRecentStrings,'Create',mtConstructor,TypeInfo(_T13),NoParams,Addr(TRecentStrings.Create),cRegister);

RegRegisterMethod(TRecentStrings,'DeleteExceed',TypeInfo(_T14),NoParams,Addr(TRecentStrings.DeleteExceed));

RegRegisterMethod(TRecentStrings,'Remove',TypeInfo(_T15),[
TypeInfo(string)],Addr(TRecentStrings.Remove));

RegisterEvent(TypeInfo(TClickMenuEvent),[
TypeInfo(TObject),
TypeInfo(string),
TypeInfo(string),
TypeInfo(Longint)]);

RegisterEvent(TypeInfo(TGetItemEvent),[
TypeInfo(TObject),
TypeInfo(string),
TypeInfo(TShortCut),
TypeInfo(Longint)]);

RegisterEvent(TypeInfo(TReadItemEvent),[
TypeInfo(TObject),
TypeInfo(TObject),
TypeInfo(string),
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(Longint)]);

RegisterEvent(TypeInfo(TWriteItemEvent),[
TypeInfo(TObject),
TypeInfo(TObject),
TypeInfo(string),
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(Longint)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
