{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit RXCALC_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  SysUtils,
  Messages,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  Menus,
  ExtCtrls,
  Buttons,
  RxCtrls,
  Clipbrd,
  classes,
  dcscript,
  dcsystem,
  RxCalc;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (p0 : TComponent;
p1 : THelpContext): TRxCalculatorForm of object;

_T1 = function (p0 : TComponent;
p1 : TBiDiMode): TWinControl of object;

_T2 = procedure (p0 : TWinControl;
p1 : Byte;
p2 : Boolean) of object;

_T3 = procedure  of object;

_T4 = procedure (var p0 : Char) of object;

_T5 = _T3;

_T6 = function : Boolean of object;

function ____CreatePopupCalculator__Wrapper(cArgs : integer; pArgs : PArgList) : OleVariant;
begin
case cArgs of
1:
result := VarFromObject(CreatePopupCalculator(TComponent(VarToObject(OleVariant(pargs^[0])))));
2:
result := VarFromObject(CreatePopupCalculator(TComponent(VarToObject(OleVariant(pargs^[1]))),OleVariant(pargs^[0])));
end
end;

function __DC__GetTRxCalculator__CalcDisplay(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TRxCalculator(Instance).CalcDisplay;
end;

function __DC__GetTRxCalculator__Memory(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TRxCalculator(Instance).Memory;
end;

procedure __RegisterProps;
begin
RegisterProperty(TRxCalculator,'CalcDisplay',__DC__GetTRxCalculator__CalcDisplay,nil);
RegisterProperty(TRxCalculator,'Memory',__DC__GetTRxCalculator__Memory,nil);
end;

const __ConstNames0 : array[0..3] of string = (
'DefCalcPrecision'
,'csFirst'
,'csValid'
,'csError'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,DefCalcPrecision));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,csFirst));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,csValid));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,csError));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..1] of TClass = (
TRxCalculator,
TRxCalculatorForm
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..2] of string = (
'CreateCalculatorForm'
,'CreatePopupCalculator'
,'SetupPopupCalculator'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TComponent),
TypeInfo(THelpContext),TypeInfo(TRxCalculatorForm)],Addr(CreateCalculatorForm),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtScriptProc,TypeInfo(_T1),[
TypeInfo(TComponent),
TypeInfo(TBiDiMode),TypeInfo(TWinControl)],Addr(____CreatePopupCalculator__Wrapper),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(TWinControl),
TypeInfo(Byte),
TypeInfo(Boolean)],Addr(SetupPopupCalculator),cRegister));

RegRegisterMethod(TRxCalculator,'Change',TypeInfo(_T3),NoParams, pointer(MinVMTOffset - 15));

RegRegisterMethod(TRxCalculator,'CalcKey',TypeInfo(_T4),[
TypeInfo(Char)], pointer(MinVMTOffset - 16));

RegRegisterMethod(TRxCalculator,'DisplayChange',TypeInfo(_T5),NoParams, pointer(MinVMTOffset - 17));

RegRegisterMethod(TRxCalculator,'Execute',TypeInfo(_T6),[TypeInfo(Boolean)],Addr(TRxCalculator.Execute));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
