{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit RXCCONST_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  classes,
  dcscript,
  dcsystem,
  RXCConst;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..11] of string = (
'MaxExtStrID'
,'SBrowse'
,'SDefaultFilter'
,'SDateDlgTitle'
,'SNextYear'
,'SNextMonth'
,'SPrevYear'
,'SPrevMonth'
,'SNotImplemented'
,'SFileNotExec'
,'SLoadLibError'
,'SDetails'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,MaxExtStrID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,SBrowse));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,SDefaultFilter));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,SDateDlgTitle));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,SNextYear));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,SNextMonth));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,SPrevYear));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,SPrevMonth));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,SNotImplemented));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,SFileNotExec));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,SLoadLibError));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,SDetails));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

initialization
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
