{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit RXDICE_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  SysUtils,
  Windows,
  Graphics,
  Messages,
  Controls,
  Forms,
  StdCtrls,
  ExtCtrls,
  Menus,
  RxTimer,
  VCLUtils,
  classes,
  dcscript,
  dcsystem,
  RXDice;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TRxDice
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TRxDice,'Change',TypeInfo(_T0),NoParams, pointer(MinVMTOffset - 73));

RegRegisterMethod(TRxDice,'DoStart',TypeInfo(_T1),NoParams, pointer(MinVMTOffset - 74));

RegRegisterMethod(TRxDice,'DoStop',TypeInfo(_T2),NoParams, pointer(MinVMTOffset - 75));

RegRegisterMethod(TRxDice,'RandomValue',TypeInfo(_T3),NoParams,Addr(TRxDice.RandomValue));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
