{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit Rxgrdcpt_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  Menus,
  RxHook,
  VclUtils,
  classes,
  dcscript,
  dcsystem,
  RxGrdCpt;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (p0 : TCustomForm;
p1 : TColor): TRxGradientCaption of object;

_T1 = procedure  of object;

_T2 = procedure (p0 : TRxGradientCaption) of object;

_T3 = function : TRxCaption of object;

_T4 = _T1;

_T5 = procedure (p0 : Integer;
p1 : Integer) of object;

_T6 = _T1;

_T7 = _T1;

function __DC__GetTRxCaption__GradientCaption(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TRxCaption(Instance).GradientCaption);
end;

function __DC__GetTRxCaptionList__Parent(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TRxCaptionList(Instance).Parent);
end;

function __DC__GetTRxCaptionList__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TRxCaptionList(Instance).Items[OleVariant(Params^[0])]);
end;

procedure __DC__SetTRxCaptionList__Items(Instance : TObject; Params : PVariantArgList);
begin
TRxCaptionList(Instance).Items[OleVariant(Params^[1])]:=TRxCaption(VarToObject(OleVariant(Params^[0])));
end;

procedure __RegisterProps;
begin
RegisterProperty(TRxCaption,'GradientCaption',__DC__GetTRxCaption__GradientCaption,nil);
RegisterProperty(TRxCaptionList,'Parent',__DC__GetTRxCaptionList__Parent,nil);
RegisterIndexedProperty(TRxCaptionList,'Items',1,True,__DC__GetTRxCaptionList__Items,__DC__SetTRxCaptionList__Items);
end;

const __ConstNames0 : array[0..1] of string = (
'hdLeftToRight'
,'hdRightToLeft'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,hdLeftToRight));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,hdRightToLeft));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..2] of TClass = (
TRxCaption,
TRxCaptionList,
TRxGradientCaption
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..0] of string = (
'GradientFormCaption'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TCustomForm),
TypeInfo(TColor),TypeInfo(TRxGradientCaption)],Addr(GradientFormCaption),cRegister));

RegRegisterMethod(TRxCaption,'RestoreDefaults',TypeInfo(_T1),NoParams, pointer(28));

RegisterProc(TRxCaptionList,'Create',mtConstructor,TypeInfo(_T2),[
TypeInfo(TRxGradientCaption)],Addr(TRxCaptionList.Create),cRegister);

RegRegisterMethod(TRxCaptionList,'Add',TypeInfo(_T3),[TypeInfo(TRxCaption)],Addr(TRxCaptionList.Add));

RegRegisterMethod(TRxCaptionList,'RestoreDefaults',TypeInfo(_T4),NoParams,Addr(TRxCaptionList.RestoreDefaults));

RegRegisterMethod(TRxGradientCaption,'MoveCaption',TypeInfo(_T5),[
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TRxGradientCaption.MoveCaption));

RegRegisterMethod(TRxGradientCaption,'Update',TypeInfo(_T6),NoParams,Addr(TRxGradientCaption.Update));

RegRegisterMethod(TRxGradientCaption,'Clear',TypeInfo(_T7),NoParams,Addr(TRxGradientCaption.Clear));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
