{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit RXLCONST_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  classes,
  dcscript,
  dcsystem,
  RXLConst;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..23] of string = (
'MaxExtStrID'
,'srRXControls'
,'srRXDBAware'
,'srRXTools'
,'srSaveImageList'
,'srStorageDesigner'
,'srProxyEditor'
,'srPageProxies'
,'srProxyName'
,'srPageName'
,'srSBItemNotCreate'
,'srConfirmSBDelete'
,'srSpeedbarDesigner'
,'srNewSectionName'
,'srEventNotCreate'
,'srTimerDesigner'
,'srTimerEvents'
,'srAniCurFilter'
,'srEditPicture'
,'srLoadAniCursor'
,'srLoadIcon'
,'srCaptionDesigner'
,'srGradientCaptions'
,'srBorrowStructure'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,MaxExtStrID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,srRXControls));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,srRXDBAware));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,srRXTools));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,srSaveImageList));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,srStorageDesigner));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,srProxyEditor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,srPageProxies));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,srProxyName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,srPageName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,srSBItemNotCreate));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,srConfirmSBDelete));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,srSpeedbarDesigner));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,srNewSectionName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,srEventNotCreate));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,srTimerDesigner));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,srTimerEvents));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,srAniCurFilter));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[18] ,srEditPicture));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[19] ,srLoadAniCursor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[20] ,srLoadIcon));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[21] ,srCaptionDesigner));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[22] ,srGradientCaptions));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[23] ,srBorrowStructure));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

initialization
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
