{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit RXSHELL_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Windows,
  Messages,
  Graphics,
  SysUtils,
  Forms,
  Controls,
  Menus,
  ShellAPI,
  IcoList,
  classes,
  dcscript,
  dcsystem,
  RXShell;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (const p0 : string;
p1 : Integer): TIcon of object;

_T1 = procedure (const p0 : string;
const p1 : string) of object;

_T2 = function (const p0 : string;
const p1 : string;
const p2 : string;
p3 : TExecState): THandle of object;

_T3 = function (const p0 : string;
const p1 : string;
const p2 : string;
p3 : TExecState): Integer of object;

_T4 = procedure  of object;

_T5 = procedure (p0 : TMouseButton;
p1 : TShiftState;
p2 : Integer;
p3 : Integer) of object;

_T6 = _T5;

_T7 = procedure (p0 : TShiftState;
p1 : Integer;
p2 : Integer) of object;

_T8 = _T5;

_T9 = _T4;

_T10 = _T4;

_T11 = _T4;

function __DC__GetTRxTrayIcon__Handle(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TRxTrayIcon(Instance).Handle;
end;

procedure __RegisterProps;
begin
RegisterProperty(TRxTrayIcon,'Handle',__DC__GetTRxTrayIcon__Handle,nil);
end;

const __ConstNames0 : array[0..3] of string = (
'esNormal'
,'esMinimized'
,'esMaximized'
,'esHidden'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,esNormal));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,esMinimized));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,esMaximized));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,esHidden));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..0] of TClass = (
TRxTrayIcon
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..3] of string = (
'IconExtract'
,'WinAbout'
,'FileExecute'
,'FileExecuteWait'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(string),
TypeInfo(Integer),TypeInfo(TIcon)],Addr(IconExtract),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(string),
TypeInfo(string)],Addr(WinAbout),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(string),
TypeInfo(TExecState),TypeInfo(THandle)],Addr(FileExecute),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(string),
TypeInfo(TExecState),TypeInfo(Integer)],Addr(FileExecuteWait),cRegister));

RegRegisterMethod(TRxTrayIcon,'DblClick',TypeInfo(_T4),NoParams, pointer(MinVMTOffset - 15));

RegRegisterMethod(TRxTrayIcon,'DoClick',TypeInfo(_T5),[
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)], pointer(MinVMTOffset - 16));

RegRegisterMethod(TRxTrayIcon,'MouseDown',TypeInfo(_T6),[
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)], pointer(MinVMTOffset - 17));

RegRegisterMethod(TRxTrayIcon,'MouseMove',TypeInfo(_T7),[
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)], pointer(MinVMTOffset - 18));

RegRegisterMethod(TRxTrayIcon,'MouseUp',TypeInfo(_T8),[
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)], pointer(MinVMTOffset - 19));

RegRegisterMethod(TRxTrayIcon,'UpdateNotifyData',TypeInfo(_T9),NoParams, pointer(48));

RegRegisterMethod(TRxTrayIcon,'Hide',TypeInfo(_T10),NoParams,Addr(TRxTrayIcon.Hide));

RegRegisterMethod(TRxTrayIcon,'Show',TypeInfo(_T11),NoParams,Addr(TRxTrayIcon.Show));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
