{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit RxStrUtils_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  SysUtils,
  classes,
  dcscript,
  dcsystem,
  RxStrUtils;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (const p0 : string): string of object;

_T1 = _T0;

_T2 = function (const p0 : string;
const p1 : TCharSet): Boolean of object;

_T3 = function (const p0 : string;
const p1 : string;
const p2 : string): string of object;

_T4 = _T0;

_T5 = function (const p0 : string;
p1 : Char): string of object;

_T6 = _T0;

_T7 = _T0;

_T8 = _T0;

_T9 = _T0;

_T10 = function (const p0 : string;
p1 : Byte): string of object;

_T11 = function (const p0 : string;
p1 : string;
p2 : Integer): Integer of object;

_T12 = function (p0 : Char;
p1 : Integer): string of object;

_T13 = _T12;

_T14 = function (p0 : Char;
const p1 : string;
p2 : Integer): string of object;

_T15 = _T14;

_T16 = function (const p0 : string;
p1 : Integer): string of object;

_T17 = _T16;

_T18 = _T16;

_T19 = function (const p0 : string;
const p1 : string): Integer of object;

_T20 = _T19;

_T21 = _T5;

_T22 = function (var p0 : string;
p1 : Char): string of object;

_T23 = _T0;

_T24 = function (var p0 : string): string of object;

_T25 = function (const p0 : string;
const p1 : TCharSet): string of object;

_T26 = function (const p0 : string;
const p1 : TCharSet): Integer of object;

_T27 = function (const p0 : Integer;
const p1 : string;
const p2 : TCharSet): Integer of object;

_T28 = function (p0 : Integer;
const p1 : string;
const p2 : TCharSet): string of object;

_T29 = function (p0 : Integer;
const p1 : string;
const p2 : TCharSet;
var p3 : Integer): string of object;

_T30 = _T28;

_T31 = function (const p0 : string;
var p1 : Integer;
const p2 : TCharSet): string of object;

_T32 = function (const p0 : string;
const p1 : string;
const p2 : TCharSet): Boolean of object;

_T33 = _T5;

_T34 = _T5;

_T35 = _T19;

_T36 = function (p0 : string;
p1 : string;
p2 : Boolean): Boolean of object;

_T37 = function (const p0 : ShortString;
const p1 : ShortString): ShortString of object;

_T38 = function (const p0 : string;
const p1 : string): string of object;

_T39 = _T38;

_T40 = function (const p0 : string;
p1 : TCharSet): string of object;

_T41 = _T0;

_T42 = function (p0 : Longint;
p1 : Byte): string of object;

_T43 = _T42;

_T44 = function (const p0 : string): Longint of object;

_T45 = _T44;

_T46 = function (p0 : Longint;
p1 : Byte;
p2 : Byte): string of object;

_T47 = function (p0 : string;
p1 : Byte): Longint of object;

_T48 = function (p0 : Longint;
p1 : Integer;
p2 : Integer): string of object;

_T49 = function (p0 : Longint): string of object;

_T50 = _T44;

procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..3] of string = (
'CRLF'
,'DigitChars'
,'Brackets'
,'StdWordDelims'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,CRLF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,VarFromSet(DigitChars, sizeof(DigitChars))));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,VarFromSet(Brackets, sizeof(Brackets))));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,VarFromSet(StdWordDelims, sizeof(StdWordDelims))));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..50] of string = (
'StrToOem'
,'OemToAnsiStr'
,'IsEmptyStr'
,'ReplaceStr'
,'DelSpace'
,'DelChars'
,'DelBSpace'
,'DelESpace'
,'DelRSpace'
,'DelSpace1'
,'Tab2Space'
,'NPos'
,'MakeStr'
,'MS'
,'AddChar'
,'AddCharR'
,'LeftStr'
,'RightStr'
,'CenterStr'
,'CompStr'
,'CompText'
,'Copy2Symb'
,'Copy2SymbDel'
,'Copy2Space'
,'Copy2SpaceDel'
,'AnsiProperCase'
,'WordCount'
,'WordPosition'
,'ExtractWord'
,'ExtractWordPos'
,'ExtractDelimited'
,'ExtractSubstr'
,'IsWordPresent'
,'QuotedString'
,'ExtractQuotedString'
,'FindPart'
,'IsWild'
,'XorString'
,'XorEncode'
,'XorDecode'
,'GetCmdLineArg'
,'Numb2USA'
,'Dec2Hex'
,'D2H'
,'Hex2Dec'
,'H2D'
,'Dec2Numb'
,'Numb2Dec'
,'IntToBin'
,'IntToRoman'
,'RomanToInt'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(string),TypeInfo(string)],Addr(StrToOem),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(string),TypeInfo(string)],Addr(OemToAnsiStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(string),
TypeInfo(TCharSet),TypeInfo(Boolean)],Addr(IsEmptyStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(string),TypeInfo(string)],Addr(ReplaceStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[
TypeInfo(string),TypeInfo(string)],Addr(DelSpace),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[5],mtProc,TypeInfo(_T5),[
TypeInfo(string),
TypeInfo(Char),TypeInfo(string)],Addr(DelChars),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[6],mtProc,TypeInfo(_T6),[
TypeInfo(string),TypeInfo(string)],Addr(DelBSpace),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[7],mtProc,TypeInfo(_T7),[
TypeInfo(string),TypeInfo(string)],Addr(DelESpace),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[8],mtProc,TypeInfo(_T8),[
TypeInfo(string),TypeInfo(string)],Addr(DelRSpace),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[9],mtProc,TypeInfo(_T9),[
TypeInfo(string),TypeInfo(string)],Addr(DelSpace1),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[10],mtProc,TypeInfo(_T10),[
TypeInfo(string),
TypeInfo(Byte),TypeInfo(string)],Addr(Tab2Space),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[11],mtProc,TypeInfo(_T11),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(Integer),TypeInfo(Integer)],Addr(NPos),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[12],mtProc,TypeInfo(_T12),[
TypeInfo(Char),
TypeInfo(Integer),TypeInfo(string)],Addr(MakeStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[13],mtProc,TypeInfo(_T13),[
TypeInfo(Char),
TypeInfo(Integer),TypeInfo(string)],Addr(MS),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[14],mtProc,TypeInfo(_T14),[
TypeInfo(Char),
TypeInfo(string),
TypeInfo(Integer),TypeInfo(string)],Addr(AddChar),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[15],mtProc,TypeInfo(_T15),[
TypeInfo(Char),
TypeInfo(string),
TypeInfo(Integer),TypeInfo(string)],Addr(AddCharR),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[16],mtProc,TypeInfo(_T16),[
TypeInfo(string),
TypeInfo(Integer),TypeInfo(string)],Addr(LeftStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[17],mtProc,TypeInfo(_T17),[
TypeInfo(string),
TypeInfo(Integer),TypeInfo(string)],Addr(RightStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[18],mtProc,TypeInfo(_T18),[
TypeInfo(string),
TypeInfo(Integer),TypeInfo(string)],Addr(CenterStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[19],mtProc,TypeInfo(_T19),[
TypeInfo(string),
TypeInfo(string),TypeInfo(Integer)],Addr(CompStr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[20],mtProc,TypeInfo(_T20),[
TypeInfo(string),
TypeInfo(string),TypeInfo(Integer)],Addr(CompText),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[21],mtProc,TypeInfo(_T21),[
TypeInfo(string),
TypeInfo(Char),TypeInfo(string)],Addr(Copy2Symb),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[22],mtProc,TypeInfo(_T22),[
TypeInfo(string),
TypeInfo(Char),TypeInfo(string)],Addr(Copy2SymbDel),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[23],mtProc,TypeInfo(_T23),[
TypeInfo(string),TypeInfo(string)],Addr(Copy2Space),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[24],mtProc,TypeInfo(_T24),[
TypeInfo(string),TypeInfo(string)],Addr(Copy2SpaceDel),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[25],mtProc,TypeInfo(_T25),[
TypeInfo(string),
TypeInfo(TCharSet),TypeInfo(string)],Addr(AnsiProperCase),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[26],mtProc,TypeInfo(_T26),[
TypeInfo(string),
TypeInfo(TCharSet),TypeInfo(Integer)],Addr(WordCount),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[27],mtProc,TypeInfo(_T27),[
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(TCharSet),TypeInfo(Integer)],Addr(WordPosition),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[28],mtProc,TypeInfo(_T28),[
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(TCharSet),TypeInfo(string)],Addr(ExtractWord),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[29],mtProc,TypeInfo(_T29),[
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(TCharSet),
TypeInfo(Integer),TypeInfo(string)],Addr(ExtractWordPos),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[30],mtProc,TypeInfo(_T30),[
TypeInfo(Integer),
TypeInfo(string),
TypeInfo(TCharSet),TypeInfo(string)],Addr(ExtractDelimited),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[31],mtProc,TypeInfo(_T31),[
TypeInfo(string),
TypeInfo(Integer),
TypeInfo(TCharSet),TypeInfo(string)],Addr(ExtractSubstr),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[32],mtProc,TypeInfo(_T32),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(TCharSet),TypeInfo(Boolean)],Addr(IsWordPresent),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[33],mtProc,TypeInfo(_T33),[
TypeInfo(string),
TypeInfo(Char),TypeInfo(string)],Addr(QuotedString),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[34],mtProc,TypeInfo(_T34),[
TypeInfo(string),
TypeInfo(Char),TypeInfo(string)],Addr(ExtractQuotedString),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[35],mtProc,TypeInfo(_T35),[
TypeInfo(string),
TypeInfo(string),TypeInfo(Integer)],Addr(FindPart),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[36],mtProc,TypeInfo(_T36),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(Boolean),TypeInfo(Boolean)],Addr(IsWild),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[37],mtProc,TypeInfo(_T37),[
TypeInfo(ShortString),
TypeInfo(ShortString),TypeInfo(ShortString)],Addr(XorString),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[38],mtProc,TypeInfo(_T38),[
TypeInfo(string),
TypeInfo(string),TypeInfo(string)],Addr(XorEncode),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[39],mtProc,TypeInfo(_T39),[
TypeInfo(string),
TypeInfo(string),TypeInfo(string)],Addr(XorDecode),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[40],mtProc,TypeInfo(_T40),[
TypeInfo(string),
TypeInfo(TCharSet),TypeInfo(string)],Addr(GetCmdLineArg),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[41],mtProc,TypeInfo(_T41),[
TypeInfo(string),TypeInfo(string)],Addr(Numb2USA),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[42],mtProc,TypeInfo(_T42),[
TypeInfo(Longint),
TypeInfo(Byte),TypeInfo(string)],Addr(Dec2Hex),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[43],mtProc,TypeInfo(_T43),[
TypeInfo(Longint),
TypeInfo(Byte),TypeInfo(string)],Addr(D2H),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[44],mtProc,TypeInfo(_T44),[
TypeInfo(string),TypeInfo(Longint)],Addr(Hex2Dec),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[45],mtProc,TypeInfo(_T45),[
TypeInfo(string),TypeInfo(Longint)],Addr(H2D),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[46],mtProc,TypeInfo(_T46),[
TypeInfo(Longint),
TypeInfo(Byte),
TypeInfo(Byte),TypeInfo(string)],Addr(Dec2Numb),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[47],mtProc,TypeInfo(_T47),[
TypeInfo(string),
TypeInfo(Byte),TypeInfo(Longint)],Addr(Numb2Dec),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[48],mtProc,TypeInfo(_T48),[
TypeInfo(Longint),
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(string)],Addr(IntToBin),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[49],mtProc,TypeInfo(_T49),[
TypeInfo(Longint),TypeInfo(string)],Addr(IntToRoman),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[50],mtProc,TypeInfo(_T50),[
TypeInfo(string),TypeInfo(Longint)],Addr(RomanToInt),cRegister));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
