{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit RXSWITCH_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  SysUtils,
  Windows,
  Messages,
  Graphics,
  Controls,
  Forms,
  StdCtrls,
  ExtCtrls,
  Menus,
  classes,
  dcscript,
  dcsystem,
  RXSwitch;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = _T0;

_T2 = _T0;

procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..4] of string = (
'tpNone'
,'tpLeft'
,'tpRight'
,'tpAbove'
,'tpBelow'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,tpNone));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,tpLeft));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,tpRight));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,tpAbove));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,tpBelow));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..0] of TClass = (
TRxSwitch
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
initialization
RegRegisterMethod(TRxSwitch,'DoOn',TypeInfo(_T0),NoParams, pointer(MinVMTOffset - 73));

RegRegisterMethod(TRxSwitch,'DoOff',TypeInfo(_T1),NoParams, pointer(MinVMTOffset - 74));

RegRegisterMethod(TRxSwitch,'ToggleSwitch',TypeInfo(_T2),NoParams,Addr(TRxSwitch.ToggleSwitch));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
