{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit IBUpdateSQLW_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  SysUtils,
  Classes,
  DB,
  IB,
  IBCustomDataSet,
  IBQuery,
  IBUpdateSQL,
  IBDatabase,
  Variants,
  IBUpdateSQLW;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = procedure (p0 : TUpdateKind) of object;

_T2 = _T1;

function __DC__GetTIBUpdateSQLW__QueryW(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TIBUpdateSQLW(Instance).QueryW[OleVariant(Params^[0])]);
end;

procedure __RegisterProps;
begin
RegisterIndexedProperty(TIBUpdateSQLW,'QueryW',1,False,__DC__GetTIBUpdateSQLW__QueryW,nil);
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TIBUpdateSQLW
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..0] of string = (
'Register'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),NoParams,Addr(Register),cRegister);

RegRegisterMethod(TIBUpdateSQLW,'ExecSQLW',TypeInfo(_T1),[
TypeInfo(TUpdateKind)],Addr(TIBUpdateSQLW.ExecSQLW));

RegRegisterMethod(TIBUpdateSQLW,'SetParamsW',TypeInfo(_T2),[
TypeInfo(TUpdateKind)],Addr(TIBUpdateSQLW.SetParamsW));

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
