{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit DateUtils_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  classes,
  dcscript,
  dcsystem,
  dcdreamlib,
  SysUtils,
  Math,
  Types,
  DateUtils;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (const p0 : TDateTime): TDateTime of object;

_T1 = _T0;

_T2 = function (const p0 : TDateTime): Boolean of object;

_T3 = _T2;

_T4 = function (const p0 : Word;
const p1 : Word;
const p2 : Word): Boolean of object;

_T5 = function (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word): Boolean of object;

_T6 = function (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word;
const p4 : Word;
const p5 : Word;
const p6 : Word): Boolean of object;

_T7 = function (const p0 : Word;
const p1 : Word): Boolean of object;

_T8 = _T4;

_T9 = _T5;

_T10 = function (const p0 : TDateTime): Word of object;

_T11 = function (const p0 : Word): Word of object;

_T12 = _T10;

_T13 = _T11;

_T14 = _T10;

_T15 = function (const p0 : Word;
const p1 : Word): Word of object;

_T16 = function : TDateTime of object;

_T17 = _T16;

_T18 = _T16;

_T19 = _T2;

_T20 = function (const p0 : TDateTime;
const p1 : TDateTime): Boolean of object;

_T21 = _T10;

_T22 = _T10;

_T23 = _T10;

_T24 = _T10;

_T25 = _T10;

_T26 = _T10;

_T27 = _T10;

_T28 = _T10;

_T29 = _T0;

_T30 = _T0;

_T31 = function (const p0 : Word): TDateTime of object;

_T32 = _T31;

_T33 = _T0;

_T34 = _T0;

_T35 = function (const p0 : Word;
const p1 : Word): TDateTime of object;

_T36 = _T35;

_T37 = _T0;

_T38 = _T0;

_T39 = function (const p0 : Word;
const p1 : Word;
const p2 : Word): TDateTime of object;

_T40 = _T39;

_T41 = _T0;

_T42 = _T0;

_T43 = _T39;

_T44 = _T39;

_T45 = _T10;

_T46 = _T10;

_T47 = _T10;

_T48 = _T10;

_T49 = function (const p0 : TDateTime): LongWord of object;

_T50 = _T49;

{_T51 = function (const p0 : TDateTime): Int64 of object;}

_T52 = _T10;

_T53 = _T10;

_T54 = _T10;

_T55 = _T10;

_T56 = _T49;

_T57 = _T49;

_T58 = _T10;

_T59 = _T10;

_T60 = _T10;

_T61 = _T49;

_T62 = _T49;

_T63 = _T10;

_T64 = _T10;

_T65 = _T49;

_T66 = _T49;

_T67 = _T10;

_T68 = _T10;

_T69 = _T49;

_T70 = _T10;

_T71 = _T49;

_T72 = _T10;

_T73 = function (const p0 : TDateTime;
const p1 : TDateTime;
const p2 : Integer): Boolean of object;

_T74 = _T73;

_T75 = _T73;

_T76 = _T73;

{_T77 = function (const p0 : TDateTime;
const p1 : TDateTime;
const p2 : Int64): Boolean of object;}

{_T78 = function (const p0 : TDateTime;
const p1 : TDateTime;
const p2 : Int64): Boolean of object;}

{_T79 = function (const p0 : TDateTime;
const p1 : TDateTime;
const p2 : Int64): Boolean of object;}

{_T80 = function (const p0 : TDateTime;
const p1 : TDateTime;
const p2 : Int64): Boolean of object;}

_T81 = function (const p0 : TDateTime;
const p1 : TDateTime): Integer of object;

_T82 = _T81;

_T83 = _T81;

_T84 = _T81;

{_T85 = function (const p0 : TDateTime;
const p1 : TDateTime): Int64 of object;}

{_T86 = function (const p0 : TDateTime;
const p1 : TDateTime): Int64 of object;}

{_T87 = function (const p0 : TDateTime;
const p1 : TDateTime): Int64 of object;}

{_T88 = function (const p0 : TDateTime;
const p1 : TDateTime): Int64 of object;}

_T89 = function (const p0 : TDateTime;
const p1 : TDateTime): Double of object;

_T90 = _T89;

_T91 = _T89;

_T92 = _T89;

_T93 = _T89;

_T94 = _T89;

_T95 = _T89;

_T96 = _T89;

_T97 = function (const p0 : TDateTime;
const p1 : Integer): TDateTime of object;

_T98 = _T97;

_T99 = _T97;

_T104 = function (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word;
const p4 : Word;
const p5 : Word;
const p6 : Word): TDateTime of object;

_T105 = procedure (const p0 : TDateTime;
out p1 : Word;
out p2 : Word;
out p3 : Word;
out p4 : Word;
out p5 : Word;
out p6 : Word;
out p7 : Word) of object;

_T106 = _T39;

_T107 = procedure (const p0 : TDateTime;
out p1 : Word;
out p2 : Word;
out p3 : Word) of object;

_T108 = _T35;

_T109 = procedure (const p0 : TDateTime;
out p1 : Word;
out p2 : Word) of object;

_T110 = function (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word): TDateTime of object;

_T111 = procedure (const p0 : TDateTime;
out p1 : Word;
out p2 : Word;
out p3 : Word;
out p4 : Word) of object;

_T112 = function (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word;
const p4 : Word;
const p5 : Word;
const p6 : Word;
out p7 : TDateTime): Boolean of object;

_T113 = function (const p0 : Word;
const p1 : Word;
out p2 : TDateTime): Boolean of object;

_T114 = function (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word;
var p4 : TDateTime): Boolean of object;

_T115 = function (const p0 : TDateTime;
const p1 : Word): TDateTime of object;

_T116 = _T115;

_T117 = _T115;

_T118 = _T115;

_T119 = _T115;

_T120 = _T115;

_T121 = _T115;

_T122 = function (const p0 : TDateTime;
const p1 : Word;
const p2 : Word;
const p3 : Word): TDateTime of object;

_T123 = function (const p0 : TDateTime;
const p1 : Word;
const p2 : Word;
const p3 : Word;
const p4 : Word): TDateTime of object;

_T124 = function (const p0 : TDateTime;
const p1 : Word;
const p2 : Word;
const p3 : Word;
const p4 : Word;
const p5 : Word;
const p6 : Word;
const p7 : Word): TDateTime of object;

_T125 = function (const p0 : TDateTime;
const p1 : Word;
const p2 : Word;
const p3 : Word;
const p4 : Word;
const p5 : Word;
const p6 : Word;
const p7 : Word;
out p8 : TDateTime): Boolean of object;

_T126 = function (const p0 : TDateTime;
const p1 : TDateTime): TValueRelationship of object;

_T127 = _T20;

_T128 = _T126;

_T129 = _T20;

_T130 = _T126;

_T131 = _T20;

_T132 = _T10;

_T133 = _T111;

_T134 = _T110;

_T135 = function (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word;
out p4 : TDateTime): Boolean of object;

_T136 = procedure (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word;
const p4 : Word;
const p5 : Word;
const p6 : Word;
const p7 : TDateTime) of object;

_T137 = procedure (const p0 : Word;
const p1 : Word;
const p2 : Word) of object;

_T138 = procedure (const p0 : Word;
const p1 : Word) of object;

_T139 = procedure (const p0 : Word;
const p1 : Word;
const p2 : Word;
const p3 : Word) of object;

_T140 = _T139;

_T141 = function (const p0 : TDateTime): Double of object;

_T142 = function (const p0 : Double): TDateTime of object;

_T143 = function (const p0 : Double;
out p1 : TDateTime): Boolean of object;

_T144 = _T141;

_T145 = _T142;

_T146 = _T143;

{_T147 = function (const p0 : TDateTime): Int64 of object;}

{_T148 = function (const p0 : Int64): TDateTime of object;}

function ____StartOfAWeek__Wrapper(cArgs : integer; pArgs : PArgList) : OleVariant;
begin
case cArgs of
2:
begin
result := StartOfAWeek(OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
3:
begin
result := StartOfAWeek(OleVariant(pargs^[2]),OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
end
end;

function ____EndOfAWeek__Wrapper(cArgs : integer; pArgs : PArgList) : OleVariant;
begin
case cArgs of
2:
begin
result := EndOfAWeek(OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
3:
begin
result := EndOfAWeek(OleVariant(pargs^[2]),OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
end
end;

function ____IncYear__Wrapper(cArgs : integer; pArgs : PArgList) : OleVariant;
begin
case cArgs of
1:
begin
result := IncYear(OleVariant(pargs^[0]));
end;
2:
begin
result := IncYear(OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
end
end;

function ____IncWeek__Wrapper(cArgs : integer; pArgs : PArgList) : OleVariant;
begin
case cArgs of
1:
begin
result := IncWeek(OleVariant(pargs^[0]));
end;
2:
begin
result := IncWeek(OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
end
end;

function ____IncDay__Wrapper(cArgs : integer; pArgs : PArgList) : OleVariant;
begin
case cArgs of
1:
begin
result := IncDay(OleVariant(pargs^[0]));
end;
2:
begin
result := IncDay(OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
end
end;

function ____EncodeDateWeek__Wrapper(cArgs : integer; pArgs : PArgList) : OleVariant;
begin
case cArgs of
2:
begin
result := EncodeDateWeek(OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
3:
begin
result := EncodeDateWeek(OleVariant(pargs^[2]),OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
end
end;

procedure ____InvalidDateTimeError__Wrapper(cArgs : integer; pArgs : PArgList);
begin
case cArgs of
7:
begin
InvalidDateTimeError(OleVariant(pargs^[6]),OleVariant(pargs^[5]),OleVariant(pargs^[4]),OleVariant(pargs^[3]),OleVariant(pargs^[2]),OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
8:
begin
InvalidDateTimeError(OleVariant(pargs^[7]),OleVariant(pargs^[6]),OleVariant(pargs^[5]),OleVariant(pargs^[4]),OleVariant(pargs^[3]),OleVariant(pargs^[2]),OleVariant(pargs^[1]),OleVariant(pargs^[0]));
end;
end
end;

procedure __RegisterProps;
begin
end;

function __DC__GetDateUtils__ApproxDaysPerMonth(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := DateUtils.ApproxDaysPerMonth;
end;

procedure __DC__SetDateUtils__ApproxDaysPerMonth(Instance : TObject; Params : PVariantArgList);
begin
DateUtils.ApproxDaysPerMonth:=OleVariant(Params^[0]);
end;

function __DC__GetDateUtils__ApproxDaysPerYear(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := DateUtils.ApproxDaysPerYear;
end;

procedure __DC__SetDateUtils__ApproxDaysPerYear(Instance : TObject; Params : PVariantArgList);
begin
DateUtils.ApproxDaysPerYear:=OleVariant(Params^[0]);
end;

var __RegisteredVars : TList;
procedure __RegisterVars;
begin
__RegisteredVars := TList.Create;
__RegisteredVars.Add(RegisterVar('ApproxDaysPerMonth',__DC__GetDateUtils__ApproxDaysPerMonth,__DC__SetDateUtils__ApproxDaysPerMonth));
__RegisteredVars.Add(RegisterVar('ApproxDaysPerYear',__DC__GetDateUtils__ApproxDaysPerYear,__DC__SetDateUtils__ApproxDaysPerYear));
end;

procedure __UnregisterVars;
begin
__RegisteredVars.Free;
end;

const __ConstNames0 : array[0..17] of string = (
'DaysPerWeek'
,'WeeksPerFortnight'
,'MonthsPerYear'
,'YearsPerDecade'
,'YearsPerCentury'
,'YearsPerMillennium'
,'DayMonday'
,'DayTuesday'
,'DayWednesday'
,'DayThursday'
,'DayFriday'
,'DaySaturday'
,'DaySunday'
,'OneHour'
,'OneMinute'
,'OneSecond'
,'OneMillisecond'
,'RecodeLeaveFieldAsIs'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,DaysPerWeek));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,WeeksPerFortnight));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,MonthsPerYear));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,YearsPerDecade));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,YearsPerCentury));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,YearsPerMillennium));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,DayMonday));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,DayTuesday));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,DayWednesday));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,DayThursday));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,DayFriday));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,DaySaturday));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,DaySunday));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,OneHour));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,OneMinute));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,OneSecond));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,OneMillisecond));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,RecodeLeaveFieldAsIs));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..133] of string = (
'DateOf'
,'TimeOf'
,'IsInLeapYear'
,'IsPM'
,'IsValidDate'
,'IsValidTime'
,'IsValidDateTime'
,'IsValidDateDay'
,'IsValidDateWeek'
,'IsValidDateMonthWeek'
,'WeeksInYear'
,'WeeksInAYear'
,'DaysInYear'
,'DaysInAYear'
,'DaysInMonth'
,'DaysInAMonth'
,'Today'
,'Yesterday'
,'Tomorrow'
,'IsToday'
,'IsSameDay'
,'YearOf'
,'MonthOf'
,'WeekOf'
,'DayOf'
,'HourOf'
,'MinuteOf'
,'SecondOf'
,'MilliSecondOf'
,'StartOfTheYear'
,'EndOfTheYear'
,'StartOfAYear'
,'EndOfAYear'
,'StartOfTheMonth'
,'EndOfTheMonth'
,'StartOfAMonth'
,'EndOfAMonth'
,'StartOfTheWeek'
,'EndOfTheWeek'
,'StartOfAWeek'
,'EndOfAWeek'
,'StartOfTheDay'
,'EndOfTheDay'
,'StartOfADay'
,'EndOfADay'
,'MonthOfTheYear'
,'WeekOfTheYear'
,'DayOfTheYear'
,'HourOfTheYear'
,'MinuteOfTheYear'
,'SecondOfTheYear'
,'WeekOfTheMonth'
,'DayOfTheMonth'
,'HourOfTheMonth'
,'MinuteOfTheMonth'
,'SecondOfTheMonth'
,'MilliSecondOfTheMonth'
,'DayOfTheWeek'
,'HourOfTheWeek'
,'MinuteOfTheWeek'
,'SecondOfTheWeek'
,'MilliSecondOfTheWeek'
,'HourOfTheDay'
,'MinuteOfTheDay'
,'SecondOfTheDay'
,'MilliSecondOfTheDay'
,'MinuteOfTheHour'
,'SecondOfTheHour'
,'MilliSecondOfTheHour'
,'SecondOfTheMinute'
,'MilliSecondOfTheMinute'
,'MilliSecondOfTheSecond'
,'WithinPastYears'
,'WithinPastMonths'
,'WithinPastWeeks'
,'WithinPastDays'
,'YearsBetween'
,'MonthsBetween'
,'WeeksBetween'
,'DaysBetween'
,'YearSpan'
,'MonthSpan'
,'WeekSpan'
,'DaySpan'
,'HourSpan'
,'MinuteSpan'
,'SecondSpan'
,'MilliSecondSpan'
,'IncYear'
,'IncWeek'
,'IncDay'
,'EncodeDateTime'
,'DecodeDateTime'
,'EncodeDateWeek'
,'DecodeDateWeek'
,'EncodeDateDay'
,'DecodeDateDay'
,'EncodeDateMonthWeek'
,'DecodeDateMonthWeek'
,'TryEncodeDateTime'
,'TryEncodeDateDay'
,'TryEncodeDateMonthWeek'
,'RecodeYear'
,'RecodeMonth'
,'RecodeDay'
,'RecodeHour'
,'RecodeMinute'
,'RecodeSecond'
,'RecodeMilliSecond'
,'RecodeDate'
,'RecodeTime'
,'RecodeDateTime'
,'TryRecodeDateTime'
,'CompareDateTime'
,'SameDateTime'
,'CompareDate'
,'SameDate'
,'CompareTime'
,'SameTime'
,'NthDayOfWeek'
,'DecodeDayOfWeekInMonth'
,'EncodeDayOfWeekInMonth'
,'TryEncodeDayOfWeekInMonth'
,'InvalidDateTimeError'
,'InvalidDateWeekError'
,'InvalidDateDayError'
,'InvalidDateMonthWeekError'
,'InvalidDayOfWeekInMonthError'
,'DateTimeToJulianDate'
,'JulianDateToDateTime'
,'TryJulianDateToDateTime'
,'DateTimeToModifiedJulianDate'
,'ModifiedJulianDateToDateTime'
,'TryModifiedJulianDateToDateTime'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(DateOf),cRegister);

RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(TimeOf),cRegister);

RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(IsInLeapYear),cRegister);

RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(IsPM),cRegister);

RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(Boolean)],Addr(IsValidDate),cRegister);

RegisterProc(nil,MethodNames[5],mtProc,TypeInfo(_T5),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(Boolean)],Addr(IsValidTime),cRegister);

RegisterProc(nil,MethodNames[6],mtProc,TypeInfo(_T6),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(Boolean)],Addr(IsValidDateTime),cRegister);

RegisterProc(nil,MethodNames[7],mtProc,TypeInfo(_T7),[
TypeInfo(Word),
TypeInfo(Word),TypeInfo(Boolean)],Addr(IsValidDateDay),cRegister);

RegisterProc(nil,MethodNames[8],mtProc,TypeInfo(_T8),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(Boolean)],Addr(IsValidDateWeek),cRegister);

RegisterProc(nil,MethodNames[9],mtProc,TypeInfo(_T9),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(Boolean)],Addr(IsValidDateMonthWeek),cRegister);

RegisterProc(nil,MethodNames[10],mtProc,TypeInfo(_T10),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(WeeksInYear),cRegister);

RegisterProc(nil,MethodNames[11],mtProc,TypeInfo(_T11),[
TypeInfo(Word),TypeInfo(Word)],Addr(WeeksInAYear),cRegister);

RegisterProc(nil,MethodNames[12],mtProc,TypeInfo(_T12),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(DaysInYear),cRegister);

RegisterProc(nil,MethodNames[13],mtProc,TypeInfo(_T13),[
TypeInfo(Word),TypeInfo(Word)],Addr(DaysInAYear),cRegister);

RegisterProc(nil,MethodNames[14],mtProc,TypeInfo(_T14),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(DaysInMonth),cRegister);

RegisterProc(nil,MethodNames[15],mtProc,TypeInfo(_T15),[
TypeInfo(Word),
TypeInfo(Word),TypeInfo(Word)],Addr(DaysInAMonth),cRegister);

RegisterProc(nil,MethodNames[16],mtProc,TypeInfo(_T16),[TypeInfo(TDateTime)],Addr(Today),cRegister);

RegisterProc(nil,MethodNames[17],mtProc,TypeInfo(_T17),[TypeInfo(TDateTime)],Addr(Yesterday),cRegister);

RegisterProc(nil,MethodNames[18],mtProc,TypeInfo(_T18),[TypeInfo(TDateTime)],Addr(Tomorrow),cRegister);

RegisterProc(nil,MethodNames[19],mtProc,TypeInfo(_T19),[
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(IsToday),cRegister);

RegisterProc(nil,MethodNames[20],mtProc,TypeInfo(_T20),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(IsSameDay),cRegister);

RegisterProc(nil,MethodNames[21],mtProc,TypeInfo(_T21),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(YearOf),cRegister);

RegisterProc(nil,MethodNames[22],mtProc,TypeInfo(_T22),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MonthOf),cRegister);

RegisterProc(nil,MethodNames[23],mtProc,TypeInfo(_T23),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(WeekOf),cRegister);

RegisterProc(nil,MethodNames[24],mtProc,TypeInfo(_T24),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(DayOf),cRegister);

RegisterProc(nil,MethodNames[25],mtProc,TypeInfo(_T25),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(HourOf),cRegister);

RegisterProc(nil,MethodNames[26],mtProc,TypeInfo(_T26),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MinuteOf),cRegister);

RegisterProc(nil,MethodNames[27],mtProc,TypeInfo(_T27),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(SecondOf),cRegister);

RegisterProc(nil,MethodNames[28],mtProc,TypeInfo(_T28),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MilliSecondOf),cRegister);

RegisterProc(nil,MethodNames[29],mtProc,TypeInfo(_T29),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(StartOfTheYear),cRegister);

RegisterProc(nil,MethodNames[30],mtProc,TypeInfo(_T30),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(EndOfTheYear),cRegister);

RegisterProc(nil,MethodNames[31],mtProc,TypeInfo(_T31),[
TypeInfo(Word),TypeInfo(TDateTime)],Addr(StartOfAYear),cRegister);

RegisterProc(nil,MethodNames[32],mtProc,TypeInfo(_T32),[
TypeInfo(Word),TypeInfo(TDateTime)],Addr(EndOfAYear),cRegister);

RegisterProc(nil,MethodNames[33],mtProc,TypeInfo(_T33),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(StartOfTheMonth),cRegister);

RegisterProc(nil,MethodNames[34],mtProc,TypeInfo(_T34),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(EndOfTheMonth),cRegister);

RegisterProc(nil,MethodNames[35],mtProc,TypeInfo(_T35),[
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(StartOfAMonth),cRegister);

RegisterProc(nil,MethodNames[36],mtProc,TypeInfo(_T36),[
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(EndOfAMonth),cRegister);

RegisterProc(nil,MethodNames[37],mtProc,TypeInfo(_T37),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(StartOfTheWeek),cRegister);

RegisterProc(nil,MethodNames[38],mtProc,TypeInfo(_T38),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(EndOfTheWeek),cRegister);

RegisterProc(nil,MethodNames[39],mtScriptProc,TypeInfo(_T39),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(____StartOfAWeek__Wrapper),cRegister);

RegisterProc(nil,MethodNames[40],mtScriptProc,TypeInfo(_T40),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(____EndOfAWeek__Wrapper),cRegister);

RegisterProc(nil,MethodNames[41],mtProc,TypeInfo(_T41),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(StartOfTheDay),cRegister);

RegisterProc(nil,MethodNames[42],mtProc,TypeInfo(_T42),[
TypeInfo(TDateTime),TypeInfo(TDateTime)],Addr(EndOfTheDay),cRegister);

RegisterProc(nil,MethodNames[43],mtProc,TypeInfo(_T43),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(StartOfADay),cRegister);

RegisterProc(nil,MethodNames[44],mtProc,TypeInfo(_T44),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(EndOfADay),cRegister);

RegisterProc(nil,MethodNames[45],mtProc,TypeInfo(_T45),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MonthOfTheYear),cRegister);

RegisterProc(nil,MethodNames[46],mtProc,TypeInfo(_T46),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(WeekOfTheYear),cRegister);

RegisterProc(nil,MethodNames[47],mtProc,TypeInfo(_T47),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(DayOfTheYear),cRegister);

RegisterProc(nil,MethodNames[48],mtProc,TypeInfo(_T48),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(HourOfTheYear),cRegister);

RegisterProc(nil,MethodNames[49],mtProc,TypeInfo(_T49),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(MinuteOfTheYear),cRegister);

RegisterProc(nil,MethodNames[50],mtProc,TypeInfo(_T50),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(SecondOfTheYear),cRegister);

RegisterProc(nil,MethodNames[51],mtProc,TypeInfo(_T52),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(WeekOfTheMonth),cRegister);

RegisterProc(nil,MethodNames[52],mtProc,TypeInfo(_T53),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(DayOfTheMonth),cRegister);

RegisterProc(nil,MethodNames[53],mtProc,TypeInfo(_T54),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(HourOfTheMonth),cRegister);

RegisterProc(nil,MethodNames[54],mtProc,TypeInfo(_T55),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MinuteOfTheMonth),cRegister);

RegisterProc(nil,MethodNames[55],mtProc,TypeInfo(_T56),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(SecondOfTheMonth),cRegister);

RegisterProc(nil,MethodNames[56],mtProc,TypeInfo(_T57),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(MilliSecondOfTheMonth),cRegister);

RegisterProc(nil,MethodNames[57],mtProc,TypeInfo(_T58),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(DayOfTheWeek),cRegister);

RegisterProc(nil,MethodNames[58],mtProc,TypeInfo(_T59),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(HourOfTheWeek),cRegister);

RegisterProc(nil,MethodNames[59],mtProc,TypeInfo(_T60),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MinuteOfTheWeek),cRegister);

RegisterProc(nil,MethodNames[60],mtProc,TypeInfo(_T61),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(SecondOfTheWeek),cRegister);

RegisterProc(nil,MethodNames[61],mtProc,TypeInfo(_T62),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(MilliSecondOfTheWeek),cRegister);

RegisterProc(nil,MethodNames[62],mtProc,TypeInfo(_T63),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(HourOfTheDay),cRegister);

RegisterProc(nil,MethodNames[63],mtProc,TypeInfo(_T64),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MinuteOfTheDay),cRegister);

RegisterProc(nil,MethodNames[64],mtProc,TypeInfo(_T65),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(SecondOfTheDay),cRegister);

RegisterProc(nil,MethodNames[65],mtProc,TypeInfo(_T66),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(MilliSecondOfTheDay),cRegister);

RegisterProc(nil,MethodNames[66],mtProc,TypeInfo(_T67),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MinuteOfTheHour),cRegister);

RegisterProc(nil,MethodNames[67],mtProc,TypeInfo(_T68),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(SecondOfTheHour),cRegister);

RegisterProc(nil,MethodNames[68],mtProc,TypeInfo(_T69),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(MilliSecondOfTheHour),cRegister);

RegisterProc(nil,MethodNames[69],mtProc,TypeInfo(_T70),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(SecondOfTheMinute),cRegister);

RegisterProc(nil,MethodNames[70],mtProc,TypeInfo(_T71),[
TypeInfo(TDateTime),TypeInfo(LongWord)],Addr(MilliSecondOfTheMinute),cRegister);

RegisterProc(nil,MethodNames[71],mtProc,TypeInfo(_T72),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(MilliSecondOfTheSecond),cRegister);

RegisterProc(nil,MethodNames[72],mtProc,TypeInfo(_T73),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(Boolean)],Addr(WithinPastYears),cRegister);

RegisterProc(nil,MethodNames[73],mtProc,TypeInfo(_T74),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(Boolean)],Addr(WithinPastMonths),cRegister);

RegisterProc(nil,MethodNames[74],mtProc,TypeInfo(_T75),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(Boolean)],Addr(WithinPastWeeks),cRegister);

RegisterProc(nil,MethodNames[75],mtProc,TypeInfo(_T76),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(Boolean)],Addr(WithinPastDays),cRegister);

RegisterProc(nil,MethodNames[76],mtProc,TypeInfo(_T81),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Integer)],Addr(YearsBetween),cRegister);

RegisterProc(nil,MethodNames[77],mtProc,TypeInfo(_T82),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Integer)],Addr(MonthsBetween),cRegister);

RegisterProc(nil,MethodNames[78],mtProc,TypeInfo(_T83),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Integer)],Addr(WeeksBetween),cRegister);

RegisterProc(nil,MethodNames[79],mtProc,TypeInfo(_T84),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Integer)],Addr(DaysBetween),cRegister);

RegisterProc(nil,MethodNames[80],mtProc,TypeInfo(_T89),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(YearSpan),cRegister);

RegisterProc(nil,MethodNames[81],mtProc,TypeInfo(_T90),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(MonthSpan),cRegister);

RegisterProc(nil,MethodNames[82],mtProc,TypeInfo(_T91),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(WeekSpan),cRegister);

RegisterProc(nil,MethodNames[83],mtProc,TypeInfo(_T92),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(DaySpan),cRegister);

RegisterProc(nil,MethodNames[84],mtProc,TypeInfo(_T93),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(HourSpan),cRegister);

RegisterProc(nil,MethodNames[85],mtProc,TypeInfo(_T94),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(MinuteSpan),cRegister);

RegisterProc(nil,MethodNames[86],mtProc,TypeInfo(_T95),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(SecondSpan),cRegister);

RegisterProc(nil,MethodNames[87],mtProc,TypeInfo(_T96),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Double)],Addr(MilliSecondSpan),cRegister);

RegisterProc(nil,MethodNames[88],mtScriptProc,TypeInfo(_T97),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(____IncYear__Wrapper),cRegister);

RegisterProc(nil,MethodNames[89],mtScriptProc,TypeInfo(_T98),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(____IncWeek__Wrapper),cRegister);

RegisterProc(nil,MethodNames[90],mtScriptProc,TypeInfo(_T99),[
TypeInfo(TDateTime),
TypeInfo(Integer),TypeInfo(TDateTime)],Addr(____IncDay__Wrapper),cRegister);

RegisterProc(nil,MethodNames[91],mtProc,TypeInfo(_T104),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(EncodeDateTime),cRegister);

RegisterProc(nil,MethodNames[92],mtProc,TypeInfo(_T105),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word)],Addr(DecodeDateTime),cRegister);

RegisterProc(nil,MethodNames[93],mtScriptProc,TypeInfo(_T106),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(____EncodeDateWeek__Wrapper),cRegister);

RegisterProc(nil,MethodNames[94],mtProc,TypeInfo(_T107),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word)],Addr(DecodeDateWeek),cRegister);

RegisterProc(nil,MethodNames[95],mtProc,TypeInfo(_T108),[
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(EncodeDateDay),cRegister);

RegisterProc(nil,MethodNames[96],mtProc,TypeInfo(_T109),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word)],Addr(DecodeDateDay),cRegister);

RegisterProc(nil,MethodNames[97],mtProc,TypeInfo(_T110),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(EncodeDateMonthWeek),cRegister);

RegisterProc(nil,MethodNames[98],mtProc,TypeInfo(_T111),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word)],Addr(DecodeDateMonthWeek),cRegister);

RegisterProc(nil,MethodNames[99],mtProc,TypeInfo(_T112),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(TryEncodeDateTime),cRegister);

RegisterProc(nil,MethodNames[100],mtProc,TypeInfo(_T113),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(TryEncodeDateDay),cRegister);

RegisterProc(nil,MethodNames[101],mtProc,TypeInfo(_T114),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(TryEncodeDateMonthWeek),cRegister);

RegisterProc(nil,MethodNames[102],mtProc,TypeInfo(_T115),[
TypeInfo(TDateTime),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeYear),cRegister);

RegisterProc(nil,MethodNames[103],mtProc,TypeInfo(_T116),[
TypeInfo(TDateTime),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeMonth),cRegister);

RegisterProc(nil,MethodNames[104],mtProc,TypeInfo(_T117),[
TypeInfo(TDateTime),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeDay),cRegister);

RegisterProc(nil,MethodNames[105],mtProc,TypeInfo(_T118),[
TypeInfo(TDateTime),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeHour),cRegister);

RegisterProc(nil,MethodNames[106],mtProc,TypeInfo(_T119),[
TypeInfo(TDateTime),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeMinute),cRegister);

RegisterProc(nil,MethodNames[107],mtProc,TypeInfo(_T120),[
TypeInfo(TDateTime),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeSecond),cRegister);

RegisterProc(nil,MethodNames[108],mtProc,TypeInfo(_T121),[
TypeInfo(TDateTime),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeMilliSecond),cRegister);

RegisterProc(nil,MethodNames[109],mtProc,TypeInfo(_T122),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeDate),cRegister);

RegisterProc(nil,MethodNames[110],mtProc,TypeInfo(_T123),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeTime),cRegister);

RegisterProc(nil,MethodNames[111],mtProc,TypeInfo(_T124),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(RecodeDateTime),cRegister);

RegisterProc(nil,MethodNames[112],mtProc,TypeInfo(_T125),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(TryRecodeDateTime),cRegister);

RegisterProc(nil,MethodNames[113],mtProc,TypeInfo(_T126),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(TValueRelationship)],Addr(CompareDateTime),cRegister);

RegisterProc(nil,MethodNames[114],mtProc,TypeInfo(_T127),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(SameDateTime),cRegister);

RegisterProc(nil,MethodNames[115],mtProc,TypeInfo(_T128),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(TValueRelationship)],Addr(CompareDate),cRegister);

RegisterProc(nil,MethodNames[116],mtProc,TypeInfo(_T129),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(SameDate),cRegister);

RegisterProc(nil,MethodNames[117],mtProc,TypeInfo(_T130),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(TValueRelationship)],Addr(CompareTime),cRegister);

RegisterProc(nil,MethodNames[118],mtProc,TypeInfo(_T131),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(SameTime),cRegister);

RegisterProc(nil,MethodNames[119],mtProc,TypeInfo(_T132),[
TypeInfo(TDateTime),TypeInfo(Word)],Addr(NthDayOfWeek),cRegister);

RegisterProc(nil,MethodNames[120],mtProc,TypeInfo(_T133),[
TypeInfo(TDateTime),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word)],Addr(DecodeDayOfWeekInMonth),cRegister);

RegisterProc(nil,MethodNames[121],mtProc,TypeInfo(_T134),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),TypeInfo(TDateTime)],Addr(EncodeDayOfWeekInMonth),cRegister);

RegisterProc(nil,MethodNames[122],mtProc,TypeInfo(_T135),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(TryEncodeDayOfWeekInMonth),cRegister);

RegisterProc(nil,MethodNames[123],mtScriptProc,TypeInfo(_T136),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(TDateTime)],Addr(____InvalidDateTimeError__Wrapper),cRegister);

RegisterProc(nil,MethodNames[124],mtProc,TypeInfo(_T137),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word)],Addr(InvalidDateWeekError),cRegister);

RegisterProc(nil,MethodNames[125],mtProc,TypeInfo(_T138),[
TypeInfo(Word),
TypeInfo(Word)],Addr(InvalidDateDayError),cRegister);

RegisterProc(nil,MethodNames[126],mtProc,TypeInfo(_T139),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word)],Addr(InvalidDateMonthWeekError),cRegister);

RegisterProc(nil,MethodNames[127],mtProc,TypeInfo(_T140),[
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word),
TypeInfo(Word)],Addr(InvalidDayOfWeekInMonthError),cRegister);

RegisterProc(nil,MethodNames[128],mtProc,TypeInfo(_T141),[
TypeInfo(TDateTime),TypeInfo(Double)],Addr(DateTimeToJulianDate),cRegister);

RegisterProc(nil,MethodNames[129],mtProc,TypeInfo(_T142),[
TypeInfo(Double),TypeInfo(TDateTime)],Addr(JulianDateToDateTime),cRegister);

RegisterProc(nil,MethodNames[130],mtProc,TypeInfo(_T143),[
TypeInfo(Double),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(TryJulianDateToDateTime),cRegister);

RegisterProc(nil,MethodNames[131],mtProc,TypeInfo(_T144),[
TypeInfo(TDateTime),TypeInfo(Double)],Addr(DateTimeToModifiedJulianDate),cRegister);

RegisterProc(nil,MethodNames[132],mtProc,TypeInfo(_T145),[
TypeInfo(Double),TypeInfo(TDateTime)],Addr(ModifiedJulianDateToDateTime),cRegister);

RegisterProc(nil,MethodNames[133],mtProc,TypeInfo(_T146),[
TypeInfo(Double),
TypeInfo(TDateTime),TypeInfo(Boolean)],Addr(TryModifiedJulianDateToDateTime),cRegister);

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
{RegisterProc(nil,'MilliSecondOfTheYear',mtProc,TypeInfo(_T51),[
TypeInfo(TDateTime),TypeInfo(Int64)],Addr(MilliSecondOfTheYear),cRegister)}

{RegisterProc(nil,'WithinPastHours',mtProc,TypeInfo(_T77),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Int64),TypeInfo(Boolean)],Addr(WithinPastHours),cRegister)}

{RegisterProc(nil,'WithinPastMinutes',mtProc,TypeInfo(_T78),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Int64),TypeInfo(Boolean)],Addr(WithinPastMinutes),cRegister)}

{RegisterProc(nil,'WithinPastSeconds',mtProc,TypeInfo(_T79),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Int64),TypeInfo(Boolean)],Addr(WithinPastSeconds),cRegister)}

{RegisterProc(nil,'WithinPastMilliSeconds',mtProc,TypeInfo(_T80),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),
TypeInfo(Int64),TypeInfo(Boolean)],Addr(WithinPastMilliSeconds),cRegister)}

{RegisterProc(nil,'HoursBetween',mtProc,TypeInfo(_T85),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Int64)],Addr(HoursBetween),cRegister)}

{RegisterProc(nil,'MinutesBetween',mtProc,TypeInfo(_T86),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Int64)],Addr(MinutesBetween),cRegister)}

{RegisterProc(nil,'SecondsBetween',mtProc,TypeInfo(_T87),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Int64)],Addr(SecondsBetween),cRegister)}

{RegisterProc(nil,'MilliSecondsBetween',mtProc,TypeInfo(_T88),[
TypeInfo(TDateTime),
TypeInfo(TDateTime),TypeInfo(Int64)],Addr(MilliSecondsBetween),cRegister)}

{RegisterProc(nil,'DateTimeToUnix',mtProc,TypeInfo(_T147),[
TypeInfo(TDateTime),TypeInfo(Int64)],Addr(DateTimeToUnix),cRegister)}

{RegisterProc(nil,'UnixToDateTime',mtProc,TypeInfo(_T148),[
TypeInfo(Int64),TypeInfo(TDateTime)],Addr(UnixToDateTime),cRegister)}

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
__RegisterVars;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnRegisterVars;
__UnregisterProcs;
end.
