{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit fr_cross_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Types,
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  Menus,
  FR_Class,
  FR_Cross1,
  FR_DSet,
  ExtCtrls,
  Buttons,
  fr_crossd,
  FR_Cross;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TRect__Wrapper = class(TDCRecordWrapper)
private
fR : TRect;
public
function GetRecordPtr : pointer; override;
published
procedure setLeft(const val : Longint);
function getLeft : Longint;
property Left : Longint read getLeft write setLeft;
procedure setTop(const val : Longint);
function getTop : Longint;
property Top : Longint read getTop write setTop;
procedure setRight(const val : Longint);
function getRight : Longint;
property Right : Longint read getRight write setRight;
procedure setBottom(const val : Longint);
function getBottom : Longint;
property Bottom : Longint read getBottom write setBottom;
end;
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = _T0;

_T6 = _T0;

_T7 = _T0;

_T8 = procedure (p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState) of object;

_T9 = procedure (p0 : TObject;
p1 : TObject;
p2 : Integer;
p3 : Integer;
p4 : TDragState;
var p5 : Boolean) of object;

_T10 = procedure (p0 : TObject;
p1 : TObject;
p2 : Integer;
p3 : Integer) of object;

_T11 = _T0;

_T12 = _T0;

_T13 = _T0;

function __TRect__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TRect__Wrapper.setLeft(const val : Longint);
begin
TRect(GetRecordPtr^).Left := val;
end;
function __TRect__Wrapper.getLeft : Longint;
begin
result := TRect(GetRecordPtr^).Left;
end;
procedure __TRect__Wrapper.setTop(const val : Longint);
begin
TRect(GetRecordPtr^).Top := val;
end;
function __TRect__Wrapper.getTop : Longint;
begin
result := TRect(GetRecordPtr^).Top;
end;
procedure __TRect__Wrapper.setRight(const val : Longint);
begin
TRect(GetRecordPtr^).Right := val;
end;
function __TRect__Wrapper.getRight : Longint;
begin
result := TRect(GetRecordPtr^).Right;
end;
procedure __TRect__Wrapper.setBottom(const val : Longint);
begin
TRect(GetRecordPtr^).Bottom := val;
end;
function __TRect__Wrapper.getBottom : Longint;
begin
result := TRect(GetRecordPtr^).Bottom;
end;
procedure __TfrCrossForm__ListBox4DrawItem__Wrapper(__Instance : TfrCrossForm;
p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState);
var
__p2 : ^TRect;
__i2 : IDispatch;
begin
if p2 = nil then exit;
__p2 := (p2 as IDCRecordWrapper).GetRecordPtr;
TfrCrossForm(__Instance).ListBox4DrawItem(p0,p1,__p2^,p3);
end;


type __TRect__Wrapper__ = class(__TRect__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TRect__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
var
__rw : __TRect__Wrapper__;
begin
__rw := __TRect__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TRect((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

function __DC__GetFR_Cross__GrandTotalStr(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := FR_Cross.GrandTotalStr;
end;

procedure __DC__SetFR_Cross__GrandTotalStr(Instance : TObject; Params : PVariantArgList);
begin
FR_Cross.GrandTotalStr:=OleVariant(Params^[0]);
end;

function __DC__GetFR_Cross__TotalStr(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := FR_Cross.TotalStr;
end;

procedure __DC__SetFR_Cross__TotalStr(Instance : TObject; Params : PVariantArgList);
begin
FR_Cross.TotalStr:=OleVariant(Params^[0]);
end;

function __DC__GetFR_Cross__TotalOfStr(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := FR_Cross.TotalOfStr;
end;

procedure __DC__SetFR_Cross__TotalOfStr(Instance : TObject; Params : PVariantArgList);
begin
FR_Cross.TotalOfStr:=OleVariant(Params^[0]);
end;

function __DC__GetFR_Cross__CellStr(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := FR_Cross.CellStr;
end;

procedure __DC__SetFR_Cross__CellStr(Instance : TObject; Params : PVariantArgList);
begin
FR_Cross.CellStr:=OleVariant(Params^[0]);
end;

function __DC__GetFR_Cross__HeaderStr(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := FR_Cross.HeaderStr;
end;

procedure __DC__SetFR_Cross__HeaderStr(Instance : TObject; Params : PVariantArgList);
begin
FR_Cross.HeaderStr:=OleVariant(Params^[0]);
end;

var __RegisteredVars : TList;
procedure __RegisterVars;
begin
__RegisteredVars := TList.Create;
__RegisteredVars.Add(RegisterVar('GrandTotalStr',__DC__GetFR_Cross__GrandTotalStr,__DC__SetFR_Cross__GrandTotalStr));
__RegisteredVars.Add(RegisterVar('TotalStr',__DC__GetFR_Cross__TotalStr,__DC__SetFR_Cross__TotalStr));
__RegisteredVars.Add(RegisterVar('TotalOfStr',__DC__GetFR_Cross__TotalOfStr,__DC__SetFR_Cross__TotalOfStr));
__RegisteredVars.Add(RegisterVar('CellStr',__DC__GetFR_Cross__CellStr,__DC__SetFR_Cross__CellStr));
__RegisteredVars.Add(RegisterVar('HeaderStr',__DC__GetFR_Cross__HeaderStr,__DC__SetFR_Cross__HeaderStr));
end;

procedure __UnregisterVars;
begin
__RegisteredVars.Free;
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..2] of TClass = (
TfrCrossForm,
TfrCrossObject,
TfrCrossView
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrCrossForm,'FormShow',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrCrossForm.FormShow));

RegRegisterMethod(TfrCrossForm,'DatasetsLBClick',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrCrossForm.DatasetsLBClick));

RegRegisterMethod(TfrCrossForm,'FormHide',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrCrossForm.FormHide));

RegRegisterMethod(TfrCrossForm,'ListBox3Enter',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TfrCrossForm.ListBox3Enter));

RegRegisterMethod(TfrCrossForm,'CheckBox1Click',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TfrCrossForm.CheckBox1Click));

RegRegisterMethod(TfrCrossForm,'ListBox3Click',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TfrCrossForm.ListBox3Click));

RegRegisterMethod(TfrCrossForm,'ListBox4Click',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TfrCrossForm.ListBox4Click));

RegRegisterMethod(TfrCrossForm,'ComboBox2Click',TypeInfo(_T7),[
TypeInfo(TObject)],Addr(TfrCrossForm.ComboBox2Click));

RegRegisterMethod(TfrCrossForm,'ListBox4DrawItem',TypeInfo(_T8),[
TypeInfo(TWinControl),
TypeInfo(Integer),
TypeInfo(IDispatch),
TypeInfo(TOwnerDrawState)],Addr(__TfrCrossForm__ListBox4DrawItem__Wrapper));

RegRegisterMethod(TfrCrossForm,'FieldsLBDragOver',TypeInfo(_T9),[
TypeInfo(TObject),
TypeInfo(TObject),
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(TDragState),
TypeInfo(Boolean)],Addr(TfrCrossForm.FieldsLBDragOver));

RegRegisterMethod(TfrCrossForm,'FieldsLBDragDrop',TypeInfo(_T10),[
TypeInfo(TObject),
TypeInfo(TObject),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrCrossForm.FieldsLBDragDrop));

RegRegisterMethod(TfrCrossForm,'ListBox3DblClick',TypeInfo(_T11),[
TypeInfo(TObject)],Addr(TfrCrossForm.ListBox3DblClick));

RegRegisterMethod(TfrCrossForm,'FormCreate',TypeInfo(_T12),[
TypeInfo(TObject)],Addr(TfrCrossForm.FormCreate));

RegRegisterMethod(TfrCrossForm,'SpeedButton1Click',TypeInfo(_T13),[
TypeInfo(TObject)],Addr(TfrCrossForm.SpeedButton1Click));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
__RegisterVars;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnRegisterVars;
end.
