{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit fr_gedit_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  SysUtils,
  Windows,
  Messages,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  Buttons,
  ExtCtrls,
  FR_Class,
  FR_Const,
  FR_GEdit;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = procedure (p0 : TObject;
var p1 : Word;
p2 : TShiftState) of object;

_T4 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TfrGEditorForm
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrGEditorForm,'BitBtn1Click',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrGEditorForm.BitBtn1Click));

RegRegisterMethod(TfrGEditorForm,'Button4Click',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrGEditorForm.Button4Click));

RegRegisterMethod(TfrGEditorForm,'FormCreate',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrGEditorForm.FormCreate));

RegRegisterMethod(TfrGEditorForm,'FormKeyDown',TypeInfo(_T3),[
TypeInfo(TObject),
TypeInfo(Word),
TypeInfo(TShiftState)],Addr(TfrGEditorForm.FormKeyDown));

RegRegisterMethod(TfrGEditorForm,'PB1Paint',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TfrGEditorForm.PB1Paint));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
