unit fr_imp;
interface
uses
//  fr_about_imp,
//  fr_arg_imp,
//  fr_attre_imp,
  fr_barc_imp,
//  fr_bnded_imp,
//  fr_btyp_imp,
  fr_chart_imp,
  fr_chbox_imp,
  fr_class_imp,
//  fr_color_imp,
//убрал вместе с регистрацией Tools  fr_combo_imp,
//  fr_const_imp,
  fr_cross_imp,
  fr_cross1_imp,
//  fr_crossd_imp,
//убрал вместе с регистрацией Tools   fr_ctrls_imp,
// fr_dbfldeditor_imp,
//  fr_dbfldlist_imp,
//  fr_dblookupctl_imp,
//  fr_dbnewlookup_imp,
//  fr_dbop_imp,
//  fr_dbrel_imp,
  fr_dbset_imp,
//  fr_dbsqledit_imp,
//  fr_dbutils_imp,
  fr_dctrl_imp,
  fr_debug_imp,
  fr_desgn_imp,
//  fr_dict_imp,
//убрал вместе с регистрацией Tools    fr_dock_imp,
//  fr_dopt_imp,
  fr_dset_imp,
//  fr_dsopt_imp,
  fr_e_csv_imp,
  fr_e_htm_imp,
//  fr_e_html2_imp,
//  fr_e_html2_editors_imp,
  fr_e_rtf_imp,
  fr_e_txt_imp,
//  fr_edit_imp,
//    fr_edit1_imp,
//  fr_expr_imp,
//  fr_flds_imp,
//  fr_flds1_imp,
//  fr_fmted_imp,
//  fr_funcs_imp,
//  fr_gedit_imp,
//  fr_grped_imp,
//  fr_hilit_imp,
//  fr_iflds_imp,
//  fr_insp_imp,
//  fr_intrp_imp,
//  fr_ledit_imp,
//  fr_newrp_imp,
  fr_ole_imp,
//  fr_pagef_imp,
//  fr_pars_imp,
    fr_passw_imp,
//  fr_pgopt_imp,
//  fr_popuplb_imp,
//  FR_PrDlg_imp,
  fr_prntr_imp,
//  fr_progr_imp,
  fr_ptabl_imp,
//  fr_qbeng_imp,
//  fr_reg_imp,
//  fr_restr_imp,
  fr_rich_imp,
  fr_rrect_imp,
//  fr_rxrtf_imp,
  fr_shape_imp,
//  fr_srch_imp,
//  fr_synmemo_imp,
//  fr_templ_imp,
//  FR_Utils_imp,
//  fr_var_imp,
//  fr_vared_imp,
//  fr_vbnd_imp,
  fr_view_imp,
  frbarcod_imp,
//  frd_db_imp,
//  frd_flde_imp,
//  frd_fldl_imp,
//  frd_form_imp,
//  frd_list_imp,
//  frd_look_imp,
//  frd_md_imp,
//  frd_mngr_imp,
//  frd_parm_imp,
//  frd_prop_imp,
//  frd_qry_imp,
//  frd_tbl_imp,
//  frd_tbl1_imp,
  frd_wrap_imp,
//    frexpimg_imp,
//    frHTMExp_imp,
    frIEMatrix_imp //,
//    frOLEExl_imp,
//    frProgr_imp,
//    frRtfExp_imp,
//    frTXTExp_imp,
//    frTxtExpPrn_imp,
//    frXMLExl_imp
;
implementation
end.
