{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit frd_list_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  DB,
  StdCtrls,
  ComCtrls,
  ExtCtrls,
  FR_Const,
  FR_DBRel,
  ImgList,
  FRD_List;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = procedure (p0 : TObject;
p1 : TListItem;
p2 : TItemChange) of object;

_T2 = _T0;

_T3 = _T0;

_T4 = _T0;

_T5 = _T0;

_T6 = procedure (p0 : TObject;
var p1 : TCloseAction) of object;

_T7 = _T0;

_T8 = procedure (p0 : TObject;
p1 : TListItem;
var p2 : Boolean) of object;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TfrDatasetsForm
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrDatasetsForm,'FormCreate',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrDatasetsForm.FormCreate));

RegRegisterMethod(TfrDatasetsForm,'LV1Change',TypeInfo(_T1),[
TypeInfo(TObject),
TypeInfo(TListItem),
TypeInfo(TItemChange)],Addr(TfrDatasetsForm.LV1Change));

RegRegisterMethod(TfrDatasetsForm,'NewTableBClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrDatasetsForm.NewTableBClick));

RegRegisterMethod(TfrDatasetsForm,'RemoveBClick',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TfrDatasetsForm.RemoveBClick));

RegRegisterMethod(TfrDatasetsForm,'PropBClick',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TfrDatasetsForm.PropBClick));

RegRegisterMethod(TfrDatasetsForm,'NewQueryBClick',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TfrDatasetsForm.NewQueryBClick));

RegRegisterMethod(TfrDatasetsForm,'FormClose',TypeInfo(_T6),[
TypeInfo(TObject),
TypeInfo(TCloseAction)],Addr(TfrDatasetsForm.FormClose));

RegRegisterMethod(TfrDatasetsForm,'NewDatabaseBClick',TypeInfo(_T7),[
TypeInfo(TObject)],Addr(TfrDatasetsForm.NewDatabaseBClick));

RegRegisterMethod(TfrDatasetsForm,'LV1Editing',TypeInfo(_T8),[
TypeInfo(TObject),
TypeInfo(TListItem),
TypeInfo(Boolean)],Addr(TfrDatasetsForm.LV1Editing));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
