{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit DBXpress_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  classes,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  DB,
  DBXpress;
function ConvertFLDDescToVariant(var R : FLDDesc) : OleVariant;
function ConvertVariantToFLDDesc(const V : OleVariant) : FLDDesc;
function ConvertObjAttrDescToVariant(var R : ObjAttrDesc) : OleVariant;
function ConvertVariantToObjAttrDesc(const V : OleVariant) : ObjAttrDesc;
function ConvertObjParentDescToVariant(var R : ObjParentDesc) : OleVariant;
function ConvertVariantToObjParentDesc(const V : OleVariant) : ObjParentDesc;
function ConvertObjTypeDescToVariant(var R : ObjTypeDesc) : OleVariant;
function ConvertVariantToObjTypeDesc(const V : OleVariant) : ObjTypeDesc;
function ConvertSPParamDescToVariant(var R : SPParamDesc) : OleVariant;
function ConvertVariantToSPParamDesc(const V : OleVariant) : SPParamDesc;
function ConvertTTransactionDescToVariant(var R : TTransactionDesc) : OleVariant;
function ConvertVariantToTTransactionDesc(const V : OleVariant) : TTransactionDesc;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __FLDDesc__Wrapper = class(TDCRecordWrapper)
private
fR : FLDDesc;
public
function GetRecordPtr : pointer; override;
published
procedure setiFldNum(const val : Word);
function getiFldNum : Word;
property iFldNum : Word read getiFldNum write setiFldNum;
procedure setiFldType(const val : Word);
function getiFldType : Word;
property iFldType : Word read getiFldType write setiFldType;
procedure setiSubType(const val : Word);
function getiSubType : Word;
property iSubType : Word read getiSubType write setiSubType;
procedure setiUnits1(const val : SmallInt);
function getiUnits1 : SmallInt;
property iUnits1 : SmallInt read getiUnits1 write setiUnits1;
procedure setiUnits2(const val : SmallInt);
function getiUnits2 : SmallInt;
property iUnits2 : SmallInt read getiUnits2 write setiUnits2;
procedure setiOffset(const val : Word);
function getiOffset : Word;
property iOffset : Word read getiOffset write setiOffset;
procedure setiLen(const val : LongWord);
function getiLen : LongWord;
property iLen : LongWord read getiLen write setiLen;
procedure setiNullOffset(const val : Word);
function getiNullOffset : Word;
property iNullOffset : Word read getiNullOffset write setiNullOffset;
procedure setefldvVchk(const val : FLDVchk);
function getefldvVchk : FLDVchk;
property efldvVchk : FLDVchk read getefldvVchk write setefldvVchk;
procedure setefldrRights(const val : FLDRights);
function getefldrRights : FLDRights;
property efldrRights : FLDRights read getefldrRights write setefldrRights;
procedure setbCalcField(const val : WordBool);
function getbCalcField : WordBool;
property bCalcField : WordBool read getbCalcField write setbCalcField;
end;
type __ObjAttrDesc__Wrapper = class(TDCRecordWrapper)
private
fR : ObjAttrDesc;
public
function GetRecordPtr : pointer; override;
published
procedure setiFldNum(const val : Word);
function getiFldNum : Word;
property iFldNum : Word read getiFldNum write setiFldNum;
end;
type __ObjParentDesc__Wrapper = class(TDCRecordWrapper)
private
fR : ObjParentDesc;
public
function GetRecordPtr : pointer; override;
published
procedure setiFldNum(const val : Word);
function getiFldNum : Word;
property iFldNum : Word read getiFldNum write setiFldNum;
procedure setiParentFldNum(const val : Word);
function getiParentFldNum : Word;
property iParentFldNum : Word read getiParentFldNum write setiParentFldNum;
end;
type __ObjTypeDesc__Wrapper = class(TDCRecordWrapper)
private
fR : ObjTypeDesc;
public
function GetRecordPtr : pointer; override;
published
procedure setiFldNum(const val : Word);
function getiFldNum : Word;
property iFldNum : Word read getiFldNum write setiFldNum;
end;
type __SPParamDesc__Wrapper = class(TDCRecordWrapper)
private
fR : SPParamDesc;
public
function GetRecordPtr : pointer; override;
published
procedure setiParamNum(const val : Word);
function getiParamNum : Word;
property iParamNum : Word read getiParamNum write setiParamNum;
procedure setszName(const val : AnsiString);
function getszName : AnsiString;
property szName : AnsiString read getszName write setszName;
procedure setiArgType(const val : TParamType);
function getiArgType : TParamType;
property iArgType : TParamType read getiArgType write setiArgType;
procedure setiDataType(const val : TFieldType);
function getiDataType : TFieldType;
property iDataType : TFieldType read getiDataType write setiDataType;
procedure setiUnits1(const val : SmallInt);
function getiUnits1 : SmallInt;
property iUnits1 : SmallInt read getiUnits1 write setiUnits1;
procedure setiUnits2(const val : SmallInt);
function getiUnits2 : SmallInt;
property iUnits2 : SmallInt read getiUnits2 write setiUnits2;
procedure setiLen(const val : LongWord);
function getiLen : LongWord;
property iLen : LongWord read getiLen write setiLen;
end;
type __TTransactionDesc__Wrapper = class(TDCRecordWrapper)
private
fR : TTransactionDesc;
public
function GetRecordPtr : pointer; override;
published
procedure setTransactionID(const val : LongWord);
function getTransactionID : LongWord;
property TransactionID : LongWord read getTransactionID write setTransactionID;
procedure setGlobalID(const val : LongWord);
function getGlobalID : LongWord;
property GlobalID : LongWord read getGlobalID write setGlobalID;
procedure setIsolationLevel(const val : TTransIsolationLevel);
function getIsolationLevel : TTransIsolationLevel;
property IsolationLevel : TTransIsolationLevel read getIsolationLevel write setIsolationLevel;
procedure setCustomIsolation(const val : LongWord);
function getCustomIsolation : LongWord;
property CustomIsolation : LongWord read getCustomIsolation write setCustomIsolation;
end;
function __FLDDesc__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __FLDDesc__Wrapper.setiFldNum(const val : Word);
begin
FLDDesc(GetRecordPtr^).iFldNum := val;
end;
function __FLDDesc__Wrapper.getiFldNum : Word;
begin
result := FLDDesc(GetRecordPtr^).iFldNum;
end;
procedure __FLDDesc__Wrapper.setiFldType(const val : Word);
begin
FLDDesc(GetRecordPtr^).iFldType := val;
end;
function __FLDDesc__Wrapper.getiFldType : Word;
begin
result := FLDDesc(GetRecordPtr^).iFldType;
end;
procedure __FLDDesc__Wrapper.setiSubType(const val : Word);
begin
FLDDesc(GetRecordPtr^).iSubType := val;
end;
function __FLDDesc__Wrapper.getiSubType : Word;
begin
result := FLDDesc(GetRecordPtr^).iSubType;
end;
procedure __FLDDesc__Wrapper.setiUnits1(const val : SmallInt);
begin
FLDDesc(GetRecordPtr^).iUnits1 := val;
end;
function __FLDDesc__Wrapper.getiUnits1 : SmallInt;
begin
result := FLDDesc(GetRecordPtr^).iUnits1;
end;
procedure __FLDDesc__Wrapper.setiUnits2(const val : SmallInt);
begin
FLDDesc(GetRecordPtr^).iUnits2 := val;
end;
function __FLDDesc__Wrapper.getiUnits2 : SmallInt;
begin
result := FLDDesc(GetRecordPtr^).iUnits2;
end;
procedure __FLDDesc__Wrapper.setiOffset(const val : Word);
begin
FLDDesc(GetRecordPtr^).iOffset := val;
end;
function __FLDDesc__Wrapper.getiOffset : Word;
begin
result := FLDDesc(GetRecordPtr^).iOffset;
end;
procedure __FLDDesc__Wrapper.setiLen(const val : LongWord);
begin
FLDDesc(GetRecordPtr^).iLen := val;
end;
function __FLDDesc__Wrapper.getiLen : LongWord;
begin
result := FLDDesc(GetRecordPtr^).iLen;
end;
procedure __FLDDesc__Wrapper.setiNullOffset(const val : Word);
begin
FLDDesc(GetRecordPtr^).iNullOffset := val;
end;
function __FLDDesc__Wrapper.getiNullOffset : Word;
begin
result := FLDDesc(GetRecordPtr^).iNullOffset;
end;
procedure __FLDDesc__Wrapper.setefldvVchk(const val : FLDVchk);
begin
FLDDesc(GetRecordPtr^).efldvVchk := val;
end;
function __FLDDesc__Wrapper.getefldvVchk : FLDVchk;
begin
result := FLDDesc(GetRecordPtr^).efldvVchk;
end;
procedure __FLDDesc__Wrapper.setefldrRights(const val : FLDRights);
begin
FLDDesc(GetRecordPtr^).efldrRights := val;
end;
function __FLDDesc__Wrapper.getefldrRights : FLDRights;
begin
result := FLDDesc(GetRecordPtr^).efldrRights;
end;
procedure __FLDDesc__Wrapper.setbCalcField(const val : WordBool);
begin
FLDDesc(GetRecordPtr^).bCalcField := val;
end;
function __FLDDesc__Wrapper.getbCalcField : WordBool;
begin
result := FLDDesc(GetRecordPtr^).bCalcField;
end;
function __ObjAttrDesc__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __ObjAttrDesc__Wrapper.setiFldNum(const val : Word);
begin
ObjAttrDesc(GetRecordPtr^).iFldNum := val;
end;
function __ObjAttrDesc__Wrapper.getiFldNum : Word;
begin
result := ObjAttrDesc(GetRecordPtr^).iFldNum;
end;
function __ObjParentDesc__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __ObjParentDesc__Wrapper.setiFldNum(const val : Word);
begin
ObjParentDesc(GetRecordPtr^).iFldNum := val;
end;
function __ObjParentDesc__Wrapper.getiFldNum : Word;
begin
result := ObjParentDesc(GetRecordPtr^).iFldNum;
end;
procedure __ObjParentDesc__Wrapper.setiParentFldNum(const val : Word);
begin
ObjParentDesc(GetRecordPtr^).iParentFldNum := val;
end;
function __ObjParentDesc__Wrapper.getiParentFldNum : Word;
begin
result := ObjParentDesc(GetRecordPtr^).iParentFldNum;
end;
function __ObjTypeDesc__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __ObjTypeDesc__Wrapper.setiFldNum(const val : Word);
begin
ObjTypeDesc(GetRecordPtr^).iFldNum := val;
end;
function __ObjTypeDesc__Wrapper.getiFldNum : Word;
begin
result := ObjTypeDesc(GetRecordPtr^).iFldNum;
end;
function __SPParamDesc__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __SPParamDesc__Wrapper.setiParamNum(const val : Word);
begin
SPParamDesc(GetRecordPtr^).iParamNum := val;
end;
function __SPParamDesc__Wrapper.getiParamNum : Word;
begin
result := SPParamDesc(GetRecordPtr^).iParamNum;
end;
procedure __SPParamDesc__Wrapper.setszName(const val : AnsiString);
begin
SPParamDesc(GetRecordPtr^).szName := val;
end;
function __SPParamDesc__Wrapper.getszName : AnsiString;
begin
result := SPParamDesc(GetRecordPtr^).szName;
end;
procedure __SPParamDesc__Wrapper.setiArgType(const val : TParamType);
begin
SPParamDesc(GetRecordPtr^).iArgType := val;
end;
function __SPParamDesc__Wrapper.getiArgType : TParamType;
begin
result := SPParamDesc(GetRecordPtr^).iArgType;
end;
procedure __SPParamDesc__Wrapper.setiDataType(const val : TFieldType);
begin
SPParamDesc(GetRecordPtr^).iDataType := val;
end;
function __SPParamDesc__Wrapper.getiDataType : TFieldType;
begin
result := SPParamDesc(GetRecordPtr^).iDataType;
end;
procedure __SPParamDesc__Wrapper.setiUnits1(const val : SmallInt);
begin
SPParamDesc(GetRecordPtr^).iUnits1 := val;
end;
function __SPParamDesc__Wrapper.getiUnits1 : SmallInt;
begin
result := SPParamDesc(GetRecordPtr^).iUnits1;
end;
procedure __SPParamDesc__Wrapper.setiUnits2(const val : SmallInt);
begin
SPParamDesc(GetRecordPtr^).iUnits2 := val;
end;
function __SPParamDesc__Wrapper.getiUnits2 : SmallInt;
begin
result := SPParamDesc(GetRecordPtr^).iUnits2;
end;
procedure __SPParamDesc__Wrapper.setiLen(const val : LongWord);
begin
SPParamDesc(GetRecordPtr^).iLen := val;
end;
function __SPParamDesc__Wrapper.getiLen : LongWord;
begin
result := SPParamDesc(GetRecordPtr^).iLen;
end;
function __TTransactionDesc__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TTransactionDesc__Wrapper.setTransactionID(const val : LongWord);
begin
TTransactionDesc(GetRecordPtr^).TransactionID := val;
end;
function __TTransactionDesc__Wrapper.getTransactionID : LongWord;
begin
result := TTransactionDesc(GetRecordPtr^).TransactionID;
end;
procedure __TTransactionDesc__Wrapper.setGlobalID(const val : LongWord);
begin
TTransactionDesc(GetRecordPtr^).GlobalID := val;
end;
function __TTransactionDesc__Wrapper.getGlobalID : LongWord;
begin
result := TTransactionDesc(GetRecordPtr^).GlobalID;
end;
procedure __TTransactionDesc__Wrapper.setIsolationLevel(const val : TTransIsolationLevel);
begin
TTransactionDesc(GetRecordPtr^).IsolationLevel := val;
end;
function __TTransactionDesc__Wrapper.getIsolationLevel : TTransIsolationLevel;
begin
result := TTransactionDesc(GetRecordPtr^).IsolationLevel;
end;
procedure __TTransactionDesc__Wrapper.setCustomIsolation(const val : LongWord);
begin
TTransactionDesc(GetRecordPtr^).CustomIsolation := val;
end;
function __TTransactionDesc__Wrapper.getCustomIsolation : LongWord;
begin
result := TTransactionDesc(GetRecordPtr^).CustomIsolation;
end;
function _FLDDesc_ : IDispatch;
begin
  result := __FLDDesc__Wrapper.Create;
end;
function _ObjAttrDesc_ : IDispatch;
begin
  result := __ObjAttrDesc__Wrapper.Create;
end;
function _ObjParentDesc_ : IDispatch;
begin
  result := __ObjParentDesc__Wrapper.Create;
end;
function _ObjTypeDesc_ : IDispatch;
begin
  result := __ObjTypeDesc__Wrapper.Create;
end;
function _SPParamDesc_ : IDispatch;
begin
  result := __SPParamDesc__Wrapper.Create;
end;
function _TTransactionDesc_ : IDispatch;
begin
  result := __TTransactionDesc__Wrapper.Create;
end;

type __FLDDesc__Wrapper__ = class(__FLDDesc__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __FLDDesc__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertFLDDescToVariant(var R : FLDDesc) : OleVariant;
var
__rw : __FLDDesc__Wrapper__;
begin
__rw := __FLDDesc__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToFLDDesc(const V : OleVariant) : FLDDesc;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := FLDDesc((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;

type __ObjAttrDesc__Wrapper__ = class(__ObjAttrDesc__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __ObjAttrDesc__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertObjAttrDescToVariant(var R : ObjAttrDesc) : OleVariant;
var
__rw : __ObjAttrDesc__Wrapper__;
begin
__rw := __ObjAttrDesc__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToObjAttrDesc(const V : OleVariant) : ObjAttrDesc;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := ObjAttrDesc((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;

type __ObjParentDesc__Wrapper__ = class(__ObjParentDesc__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __ObjParentDesc__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertObjParentDescToVariant(var R : ObjParentDesc) : OleVariant;
var
__rw : __ObjParentDesc__Wrapper__;
begin
__rw := __ObjParentDesc__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToObjParentDesc(const V : OleVariant) : ObjParentDesc;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := ObjParentDesc((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;

type __ObjTypeDesc__Wrapper__ = class(__ObjTypeDesc__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __ObjTypeDesc__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertObjTypeDescToVariant(var R : ObjTypeDesc) : OleVariant;
var
__rw : __ObjTypeDesc__Wrapper__;
begin
__rw := __ObjTypeDesc__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToObjTypeDesc(const V : OleVariant) : ObjTypeDesc;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := ObjTypeDesc((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;

type __SPParamDesc__Wrapper__ = class(__SPParamDesc__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __SPParamDesc__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertSPParamDescToVariant(var R : SPParamDesc) : OleVariant;
var
__rw : __SPParamDesc__Wrapper__;
begin
__rw := __SPParamDesc__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToSPParamDesc(const V : OleVariant) : SPParamDesc;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := SPParamDesc((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;

type __TTransactionDesc__Wrapper__ = class(__TTransactionDesc__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TTransactionDesc__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTTransactionDescToVariant(var R : TTransactionDesc) : OleVariant;
var
__rw : __TTransactionDesc__Wrapper__;
begin
__rw := __TTransactionDesc__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTTransactionDesc(const V : OleVariant) : TTransactionDesc;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TTransactionDesc((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..212] of string = (
'MAXNAMELEN'
,'SQL_ERROR'
,'SQL_NULL_DATA'
,'SQL_ERROR_EOF'
,'SQL_SUCCESS'
,'DBXERR_NOMEMORY'
,'DBXERR_INVALIDFLDTYPE'
,'DBXERR_INVALIDHNDL'
,'DBXERR_INVALIDTIME'
,'DBXERR_NOTSUPPORTED'
,'DBXERR_INVALIDXLATION'
,'DBXERR_INVALIDPARAM'
,'DBXERR_OUTOFRANGE'
,'DBXERR_SQLPARAMNOTSET'
,'DBXERR_EOF'
,'DBXERR_INVALIDUSRPASS'
,'DBXERR_INVALIDPRECISION'
,'DBXERR_INVALIDLEN'
,'DBXERR_INVALIDXISOLEVEL'
,'DBXERR_INVALIDXTXNID'
,'DBXERR_DUPLICATETXNID'
,'DBXERR_DRIVERRESTRICTED'
,'DBX_MAXSTATICERRORS'
,'MaxReservedStaticErrors'
,'trUNKNOWN'
,'trQPREPARE'
,'trQEXECUTE'
,'trERROR'
,'trSTMT'
,'trCONNECT'
,'trTRANSACT'
,'trBLOB'
,'trMISC'
,'trVENDOR'
,'trDATAIN'
,'trDATAOUT'
,'eSQLTable'
,'eSQLView'
,'eSQLSystemTable'
,'eSQLSynonym'
,'eSQLTempTable'
,'eSQLLocal'
,'eSQLProcedure'
,'eSQLFunction'
,'eSQLPackage'
,'eSQLSysProcedure'
,'eSQLRowId'
,'eSQLRowVersion'
,'eSQLAutoIncr'
,'eSQLDefault'
,'eSQLNonUnique'
,'eSQLUnique'
,'eSQLPrimaryKey'
,'fldUNKNOWN'
,'fldZSTRING'
,'fldDATE'
,'fldBLOB'
,'fldBOOL'
,'fldINT16'
,'fldINT32'
,'fldFLOAT'
,'fldBCD'
,'fldBYTES'
,'fldTIME'
,'fldTIMESTAMP'
,'fldUINT16'
,'fldUINT32'
,'fldFLOATIEEE'
,'fldVARBYTES'
,'fldLOCKINFO'
,'fldCURSOR'
,'fldINT64'
,'fldUINT64'
,'fldADT'
,'fldARRAY'
,'fldREF'
,'fldTABLE'
,'fldDATETIME'
,'fldFMTBCD'
,'MAXLOGFLDTYPES'
,'fldstMONEY'
,'fldstMEMO'
,'fldstBINARY'
,'fldstFMTMEMO'
,'fldstOLEOBJ'
,'fldstGRAPHIC'
,'fldstDBSOLEOBJ'
,'fldstTYPEDBINARY'
,'fldstACCOLEOBJ'
,'fldstHMEMO'
,'fldstHBINARY'
,'fldstBFILE'
,'fldstPASSWORD'
,'fldstFIXED'
,'fldstUNICODE'
,'fldstAUTOINC'
,'fldstADTNestedTable'
,'fldstADTDATE'
,'fldvNOCHECKS'
,'fldvHASCHECKS'
,'fldvUNKNOWN'
,'fldrREADWRITE'
,'fldrREADONLY'
,'fldrNONE'
,'fldrUNKNOWN'
,'cbGENERAL'
,'cbRESERVED1'
,'cbRESERVED2'
,'cbINPUTREQ'
,'cbRESERVED4'
,'cbRESERVED5'
,'cbBATCHRESULT'
,'cbRESERVED7'
,'cbRESTRUCTURE'
,'cbRESERVED9'
,'cbRESERVED10'
,'cbRESERVED11'
,'cbRESERVED12'
,'cbRESERVED13'
,'cbRESERVED14'
,'cbRESERVED15'
,'cbRESERVED16'
,'cbRESERVED17'
,'cbTABLECHANGED'
,'cbRESERVED19'
,'cbCANCELQRY'
,'cbSERVERCALL'
,'cbRESERVED22'
,'cbGENPROGRESS'
,'cbDBASELOGIN'
,'cbDELAYEDUPD'
,'cbFIELDRECALC'
,'cbTRACE'
,'cbDBLOGIN'
,'cbDETACHNOTIFY'
,'cbNBROFCBS'
,'eDrvBlobSize'
,'eDrvCallBack'
,'eDrvCallBackInfo'
,'eDrvRestrict'
,'eConnAutoCommit'
,'eConnBlockingMode'
,'eConnBlobSize'
,'eConnRoleName'
,'eConnWaitOnLocks'
,'eConnCommitRetain'
,'eConnTxnIsoLevel'
,'eConnNativeHandle'
,'eConnServerVersion'
,'eConnCallBack'
,'eConnHostName'
,'eConnDatabaseName'
,'eConnCallBackInfo'
,'eConnObjectMode'
,'eConnMaxActiveConnection'
,'eConnServerCharSet'
,'eConnSqlDialect'
,'eCommRowsetSize'
,'eCommBlobSize'
,'eCommBlockRead'
,'eCommBlockWrite'
,'eCommParamCount'
,'eCommNativeHandle'
,'eCommCursorName'
,'eCommStoredProc'
,'eCommSQLDialect'
,'eCommTransactionID'
,'eCurObjectAttrName'
,'eCurObjectTypeName'
,'eCurParentFieldID'
,'cbrUSEDEF'
,'cbrCONTINUE'
,'cbrABORT'
,'cbrCHKINPUT'
,'cbrYES'
,'cbrNO'
,'cbrPARTIALASSIST'
,'cbrSKIP'
,'cbrRETRY'
,'eMetaCatalogName'
,'eMetaSchemaName'
,'eMetaDatabaseName'
,'eMetaDatabaseVersion'
,'eMetaTransactionIsoLevel'
,'eMetaSupportsTransaction'
,'eMetaMaxObjectNameLength'
,'eMetaMaxColumnsInTable'
,'eMetaMaxColumnsInSelect'
,'eMetaMaxRowSize'
,'eMetaMaxSQLLength'
,'eMetaObjectQuoteChar'
,'eMetaSQLEscapeChar'
,'eMetaProcSupportsCursor'
,'eMetaProcSupportsCursors'
,'eMetaSupportsTransactions'
,'eObjTypeDatabase'
,'eObjTypeDataType'
,'eObjTypeTable'
,'eObjTypeView'
,'eObjTypeSynonym'
,'eObjTypeProcedure'
,'eObjTypeUser'
,'eObjTypeRole'
,'eObjTypeUDT'
,'xilREADCOMMITTED'
,'xilREPEATABLEREAD'
,'xilDIRTYREAD'
,'xilCUSTOM'
,'paramUNKNOWN'
,'paramIN'
,'paramOUT'
,'paramINOUT'
,'paramRET'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,MAXNAMELEN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,SQL_ERROR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,SQL_NULL_DATA));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,SQL_ERROR_EOF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,SQL_SUCCESS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,DBXERR_NOMEMORY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,DBXERR_INVALIDFLDTYPE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,DBXERR_INVALIDHNDL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,DBXERR_INVALIDTIME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,DBXERR_NOTSUPPORTED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,DBXERR_INVALIDXLATION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,DBXERR_INVALIDPARAM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,DBXERR_OUTOFRANGE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,DBXERR_SQLPARAMNOTSET));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,DBXERR_EOF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,DBXERR_INVALIDUSRPASS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,DBXERR_INVALIDPRECISION));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,DBXERR_INVALIDLEN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[18] ,DBXERR_INVALIDXISOLEVEL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[19] ,DBXERR_INVALIDXTXNID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[20] ,DBXERR_DUPLICATETXNID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[21] ,DBXERR_DRIVERRESTRICTED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[22] ,DBX_MAXSTATICERRORS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[23] ,MaxReservedStaticErrors));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[24] ,trUNKNOWN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[25] ,trQPREPARE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[26] ,trQEXECUTE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[27] ,trERROR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[28] ,trSTMT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[29] ,trCONNECT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[30] ,trTRANSACT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[31] ,trBLOB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[32] ,trMISC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[33] ,trVENDOR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[34] ,trDATAIN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[35] ,trDATAOUT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[36] ,eSQLTable));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[37] ,eSQLView));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[38] ,eSQLSystemTable));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[39] ,eSQLSynonym));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[40] ,eSQLTempTable));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[41] ,eSQLLocal));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[42] ,eSQLProcedure));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[43] ,eSQLFunction));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[44] ,eSQLPackage));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[45] ,eSQLSysProcedure));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[46] ,eSQLRowId));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[47] ,eSQLRowVersion));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[48] ,eSQLAutoIncr));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[49] ,eSQLDefault));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[50] ,eSQLNonUnique));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[51] ,eSQLUnique));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[52] ,eSQLPrimaryKey));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[53] ,fldUNKNOWN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[54] ,fldZSTRING));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[55] ,fldDATE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[56] ,fldBLOB));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[57] ,fldBOOL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[58] ,fldINT16));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[59] ,fldINT32));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[60] ,fldFLOAT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[61] ,fldBCD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[62] ,fldBYTES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[63] ,fldTIME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[64] ,fldTIMESTAMP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[65] ,fldUINT16));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[66] ,fldUINT32));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[67] ,fldFLOATIEEE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[68] ,fldVARBYTES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[69] ,fldLOCKINFO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[70] ,fldCURSOR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[71] ,fldINT64));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[72] ,fldUINT64));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[73] ,fldADT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[74] ,fldARRAY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[75] ,fldREF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[76] ,fldTABLE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[77] ,fldDATETIME));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[78] ,fldFMTBCD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[79] ,MAXLOGFLDTYPES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[80] ,fldstMONEY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[81] ,fldstMEMO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[82] ,fldstBINARY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[83] ,fldstFMTMEMO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[84] ,fldstOLEOBJ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[85] ,fldstGRAPHIC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[86] ,fldstDBSOLEOBJ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[87] ,fldstTYPEDBINARY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[88] ,fldstACCOLEOBJ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[89] ,fldstHMEMO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[90] ,fldstHBINARY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[91] ,fldstBFILE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[92] ,fldstPASSWORD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[93] ,fldstFIXED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[94] ,fldstUNICODE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[95] ,fldstAUTOINC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[96] ,fldstADTNestedTable));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[97] ,fldstADTDATE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[98] ,fldvNOCHECKS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[99] ,fldvHASCHECKS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[100] ,fldvUNKNOWN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[101] ,fldrREADWRITE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[102] ,fldrREADONLY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[103] ,fldrNONE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[104] ,fldrUNKNOWN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[105] ,cbGENERAL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[106] ,cbRESERVED1));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[107] ,cbRESERVED2));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[108] ,cbINPUTREQ));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[109] ,cbRESERVED4));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[110] ,cbRESERVED5));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[111] ,cbBATCHRESULT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[112] ,cbRESERVED7));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[113] ,cbRESTRUCTURE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[114] ,cbRESERVED9));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[115] ,cbRESERVED10));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[116] ,cbRESERVED11));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[117] ,cbRESERVED12));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[118] ,cbRESERVED13));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[119] ,cbRESERVED14));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[120] ,cbRESERVED15));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[121] ,cbRESERVED16));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[122] ,cbRESERVED17));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[123] ,cbTABLECHANGED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[124] ,cbRESERVED19));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[125] ,cbCANCELQRY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[126] ,cbSERVERCALL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[127] ,cbRESERVED22));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[128] ,cbGENPROGRESS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[129] ,cbDBASELOGIN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[130] ,cbDELAYEDUPD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[131] ,cbFIELDRECALC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[132] ,cbTRACE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[133] ,cbDBLOGIN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[134] ,cbDETACHNOTIFY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[135] ,cbNBROFCBS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[136] ,eDrvBlobSize));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[137] ,eDrvCallBack));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[138] ,eDrvCallBackInfo));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[139] ,eDrvRestrict));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[140] ,eConnAutoCommit));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[141] ,eConnBlockingMode));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[142] ,eConnBlobSize));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[143] ,eConnRoleName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[144] ,eConnWaitOnLocks));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[145] ,eConnCommitRetain));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[146] ,eConnTxnIsoLevel));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[147] ,eConnNativeHandle));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[148] ,eConnServerVersion));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[149] ,eConnCallBack));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[150] ,eConnHostName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[151] ,eConnDatabaseName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[152] ,eConnCallBackInfo));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[153] ,eConnObjectMode));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[154] ,eConnMaxActiveConnection));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[155] ,eConnServerCharSet));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[156] ,eConnSqlDialect));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[157] ,eCommRowsetSize));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[158] ,eCommBlobSize));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[159] ,eCommBlockRead));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[160] ,eCommBlockWrite));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[161] ,eCommParamCount));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[162] ,eCommNativeHandle));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[163] ,eCommCursorName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[164] ,eCommStoredProc));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[165] ,eCommSQLDialect));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[166] ,eCommTransactionID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[167] ,eCurObjectAttrName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[168] ,eCurObjectTypeName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[169] ,eCurParentFieldID));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[170] ,cbrUSEDEF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[171] ,cbrCONTINUE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[172] ,cbrABORT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[173] ,cbrCHKINPUT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[174] ,cbrYES));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[175] ,cbrNO));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[176] ,cbrPARTIALASSIST));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[177] ,cbrSKIP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[178] ,cbrRETRY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[179] ,eMetaCatalogName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[180] ,eMetaSchemaName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[181] ,eMetaDatabaseName));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[182] ,eMetaDatabaseVersion));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[183] ,eMetaTransactionIsoLevel));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[184] ,eMetaSupportsTransaction));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[185] ,eMetaMaxObjectNameLength));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[186] ,eMetaMaxColumnsInTable));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[187] ,eMetaMaxColumnsInSelect));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[188] ,eMetaMaxRowSize));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[189] ,eMetaMaxSQLLength));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[190] ,eMetaObjectQuoteChar));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[191] ,eMetaSQLEscapeChar));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[192] ,eMetaProcSupportsCursor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[193] ,eMetaProcSupportsCursors));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[194] ,eMetaSupportsTransactions));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[195] ,eObjTypeDatabase));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[196] ,eObjTypeDataType));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[197] ,eObjTypeTable));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[198] ,eObjTypeView));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[199] ,eObjTypeSynonym));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[200] ,eObjTypeProcedure));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[201] ,eObjTypeUser));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[202] ,eObjTypeRole));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[203] ,eObjTypeUDT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[204] ,xilREADCOMMITTED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[205] ,xilREPEATABLEREAD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[206] ,xilDIRTYREAD));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[207] ,xilCUSTOM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[208] ,paramUNKNOWN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[209] ,paramIN));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[210] ,paramOUT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[211] ,paramINOUT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[212] ,paramRET));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..5] of string = (
'FLDDesc'
,'ObjAttrDesc'
,'ObjParentDesc'
,'ObjTypeDesc'
,'SPParamDesc'
,'TTransactionDesc'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
__RegisteredMethods.Add(RegisterRWProc(MethodNames[0],Addr(_FLDDesc_)));
__RegisteredMethods.Add(RegisterRWProc(MethodNames[1],Addr(_ObjAttrDesc_)));
__RegisteredMethods.Add(RegisterRWProc(MethodNames[2],Addr(_ObjParentDesc_)));
__RegisteredMethods.Add(RegisterRWProc(MethodNames[3],Addr(_ObjTypeDesc_)));
__RegisteredMethods.Add(RegisterRWProc(MethodNames[4],Addr(_SPParamDesc_)));
__RegisteredMethods.Add(RegisterRWProc(MethodNames[5],Addr(_TTransactionDesc_)));
end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
