{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit dccalculator_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  StdCtrls,
  Buttons,
  dcCalculator;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function : string of object;

_T1 = procedure (p0 : string) of object;

_T2 = procedure (p0 : TObject) of object;

_T3 = procedure (p0 : TDCBtnKind) of object;

_T4 = procedure (var p0 : Integer;
var p1 : Integer) of object;

_T5 = procedure (p0 : Extended) of object;

_T6 = procedure  of object;

function __DC__GetTDCCustomCalculator__Status(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TDCCustomCalculator(Instance).Status;
end;

procedure __DC__SetTDCCustomCalculator__Status(Instance : TObject; Params : PVariantArgList);
begin
TDCCustomCalculator(Instance).Status:=OleVariant(Params^[0]);
end;

function __DC__GetTDCCustomCalculator__OperandA(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TDCCustomCalculator(Instance).OperandA;
end;

procedure __DC__SetTDCCustomCalculator__OperandA(Instance : TObject; Params : PVariantArgList);
begin
TDCCustomCalculator(Instance).OperandA:=OleVariant(Params^[0]);
end;

function __DC__GetTDCCustomCalculator__OperandB(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TDCCustomCalculator(Instance).OperandB;
end;

procedure __DC__SetTDCCustomCalculator__OperandB(Instance : TObject; Params : PVariantArgList);
begin
TDCCustomCalculator(Instance).OperandB:=OleVariant(Params^[0]);
end;

function __DC__GetTDCCustomCalculator__Operator(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TDCCustomCalculator(Instance).Operator;
end;

procedure __DC__SetTDCCustomCalculator__Operator(Instance : TObject; Params : PVariantArgList);
begin
TDCCustomCalculator(Instance).Operator:=OleVariant(Params^[0]);
end;

function __DC__GetTDCCustomCalculator__Memory(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TDCCustomCalculator(Instance).Memory;
end;

function __DC__GetTDCCustomCalculator__Precision(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TDCCustomCalculator(Instance).Precision;
end;

procedure __DC__SetTDCCustomCalculator__Precision(Instance : TObject; Params : PVariantArgList);
begin
TDCCustomCalculator(Instance).Precision:=OleVariant(Params^[0]);
end;

procedure __RegisterProps;
begin
RegisterProperty(TDCCustomCalculator,'Status',__DC__GetTDCCustomCalculator__Status,__DC__SetTDCCustomCalculator__Status);
RegisterProperty(TDCCustomCalculator,'OperandA',__DC__GetTDCCustomCalculator__OperandA,__DC__SetTDCCustomCalculator__OperandA);
RegisterProperty(TDCCustomCalculator,'OperandB',__DC__GetTDCCustomCalculator__OperandB,__DC__SetTDCCustomCalculator__OperandB);
RegisterProperty(TDCCustomCalculator,'Operator',__DC__GetTDCCustomCalculator__Operator,__DC__SetTDCCustomCalculator__Operator);
RegisterProperty(TDCCustomCalculator,'Memory',__DC__GetTDCCustomCalculator__Memory,nil);
RegisterProperty(TDCCustomCalculator,'Precision',__DC__GetTDCCustomCalculator__Precision,__DC__SetTDCCustomCalculator__Precision);
end;

const __ConstNames0 : array[0..30] of string = (
'bBack'
,'bCancel'
,'bClear'
,'bMC'
,'bMR'
,'bMS'
,'bMP'
,'bNum0'
,'bNum1'
,'bNum2'
,'bNum3'
,'bNum4'
,'bNum5'
,'bNum6'
,'bNum7'
,'bNum8'
,'bNum9'
,'bSign'
,'bDecimal'
,'bDiv'
,'bMul'
,'bSub'
,'bAdd'
,'bSqrt'
,'bPercent'
,'bRev'
,'bEqual'
,'bNone'
,'stFirst'
,'stSecond'
,'stError'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,bBack));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,bCancel));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,bClear));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,bMC));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,bMR));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,bMS));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,bMP));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,bNum0));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,bNum1));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,bNum2));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,bNum3));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,bNum4));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,bNum5));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,bNum6));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,bNum7));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,bNum8));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,bNum9));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,bSign));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[18] ,bDecimal));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[19] ,bDiv));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[20] ,bMul));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[21] ,bSub));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[22] ,bAdd));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[23] ,bSqrt));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[24] ,bPercent));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[25] ,bRev));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[26] ,bEqual));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[27] ,bNone));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[28] ,stFirst));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[29] ,stSecond));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[30] ,stError));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..2] of TClass = (
TCalcBtn,
TDCCalculator,
TDCCustomCalculator
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TDCCustomCalculator,'GetValueText',TypeInfo(_T0),[TypeInfo(string)], pointer(196));

RegRegisterMethod(TDCCustomCalculator,'SetValueText',TypeInfo(_T1),[
TypeInfo(string)], pointer(200));

RegRegisterMethod(TDCCustomCalculator,'DoBtnClick',TypeInfo(_T2),[
TypeInfo(TObject)], pointer(204));

RegRegisterMethod(TDCCustomCalculator,'BtnClick',TypeInfo(_T3),[
TypeInfo(TDCBtnKind)], pointer(208));

RegRegisterMethod(TDCCustomCalculator,'CalculateSize',TypeInfo(_T4),[
TypeInfo(Integer),
TypeInfo(Integer)], pointer(212));

RegRegisterMethod(TDCCustomCalculator,'InitValue',TypeInfo(_T5),[
TypeInfo(Extended)],Addr(TDCCustomCalculator.InitValue));

RegRegisterMethod(TDCCustomCalculator,'_Reset',TypeInfo(_T6),NoParams,Addr(TDCCustomCalculator._Reset));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
