{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit dcfieldsselectdlg_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  StdCtrls,
  Controls,
  Buttons,
  Classes,
  Forms,
  Dialogs,
  SysUtils,
  DCConsts,
  DCdreamLib,
  DCFieldsSelectDlg;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (const p0 : String;
var p1 : String;
p2 : TStrings): Boolean of object;

_T1 = procedure (p0 : TObject) of object;

_T2 = _T1;

_T3 = _T1;

_T4 = _T1;

_T5 = _T1;

_T6 = _T1;

_T7 = _T1;

_T8 = _T1;

_T9 = _T1;

_T10 = procedure (p0 : TCustomListBox;
p1 : TStrings) of object;

_T11 = procedure (p0 : TListBox;
p1 : Integer) of object;

_T12 = function (p0 : TCustomListBox): Integer of object;

_T13 = procedure  of object;

function __DC__GetTDCFieldsSelection__ChosenFields(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TDCFieldsSelection(Instance).ChosenFields;
end;

procedure __DC__SetTDCFieldsSelection__ChosenFields(Instance : TObject; Params : PVariantArgList);
begin
TDCFieldsSelection(Instance).ChosenFields:=OleVariant(Params^[0]);
end;

procedure __RegisterProps;
begin
RegisterProperty(TDCFieldsSelection,'ChosenFields',__DC__GetTDCFieldsSelection__ChosenFields,__DC__SetTDCFieldsSelection__ChosenFields);
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TDCFieldsSelection
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..0] of string = (
'DCShowFieldsDialog'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(String),
TypeInfo(String),
TypeInfo(TStrings),TypeInfo(Boolean)],Addr(DCShowFieldsDialog),cRegister);

RegRegisterMethod(TDCFieldsSelection,'IncludeBtnClick',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.IncludeBtnClick));

RegRegisterMethod(TDCFieldsSelection,'ExcludeBtnClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.ExcludeBtnClick));

RegRegisterMethod(TDCFieldsSelection,'IncAllBtnClick',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.IncAllBtnClick));

RegRegisterMethod(TDCFieldsSelection,'ExcAllBtnClick',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.ExcAllBtnClick));

RegRegisterMethod(TDCFieldsSelection,'MoveUpBtnClick',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.MoveUpBtnClick));

RegRegisterMethod(TDCFieldsSelection,'MoveDownBtnClick',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.MoveDownBtnClick));

RegRegisterMethod(TDCFieldsSelection,'DstListClick',TypeInfo(_T7),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.DstListClick));

RegRegisterMethod(TDCFieldsSelection,'DstListDblClick',TypeInfo(_T8),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.DstListDblClick));

RegRegisterMethod(TDCFieldsSelection,'SrcListDblClick',TypeInfo(_T9),[
TypeInfo(TObject)],Addr(TDCFieldsSelection.SrcListDblClick));

RegRegisterMethod(TDCFieldsSelection,'MoveSelected',TypeInfo(_T10),[
TypeInfo(TCustomListBox),
TypeInfo(TStrings)],Addr(TDCFieldsSelection.MoveSelected));

RegRegisterMethod(TDCFieldsSelection,'SetItem',TypeInfo(_T11),[
TypeInfo(TListBox),
TypeInfo(Integer)],Addr(TDCFieldsSelection.SetItem));

RegRegisterMethod(TDCFieldsSelection,'GetFirstSelection',TypeInfo(_T12),[
TypeInfo(TCustomListBox),TypeInfo(Integer)],Addr(TDCFieldsSelection.GetFirstSelection));

RegRegisterMethod(TDCFieldsSelection,'SetButtons',TypeInfo(_T13),NoParams,Addr(TDCFieldsSelection.SetButtons));

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
