{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit dcinfotree_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Controls,
  ComCtrls,
  commctrl,
  dcconsts,
  dcInfoLib,
  dchook,
  dcdreamlib,
  dcdtree,
  extctrls,
  dcnTree,
  imglist,
  dcinfotree;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (p0 : TBaseInfoNode;
const p1 : string): Variant of object;

_T1 = function (p0 : TListItem;
const p1 : string): Variant of object;

_T2 = procedure  of object;

_T3 = function (const p0 : TDCBookMark): TListItem of object;

_T4 = procedure (p0 : TListItem) of object;

_T5 = _T2;

_T6 = _T2;

_T7 = _T2;

_T8 = function (p0 : TListItem): Boolean of object;

_T9 = _T4;

_T10 = _T2;

_T11 = procedure (p0 : TBaseInfoNode) of object;

_T12 = _T11;

_T13 = _T2;

_T14 = function (p0 : TBaseInfoNode): Boolean of object;

_T15 = _T11;

_T16 = function : TBaseInfoNode of object;

_T17 = function (p0 : TBaseInfoNode;
p1 : TBaseInfoNode): TBaseInfoNode of object;

_T18 = _T2;

_T19 = _T2;

{_T20 = function (p0 : TBaseInfoNode): IDCRowSet of object;}

_T21 = procedure (p0 : TListItems) of object;

function __DC__GetTCustomDCInfoListView__CheckField(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoListView(Instance).CheckField;
end;

procedure __DC__SetTCustomDCInfoListView__CheckField(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).CheckField:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomDCInfoListView__Fields(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoListView(Instance).Fields);
end;

procedure __DC__SetTCustomDCInfoListView__Fields(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).Fields:=TStrings(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoListView__UsedFields(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoListView(Instance).UsedFields);
end;

function __DC__GetTCustomDCInfoListView__InfoSet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoListView(Instance).InfoSet);
end;

procedure __DC__SetTCustomDCInfoListView__InfoSet(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).InfoSet:=TComponent(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoListView__ImageField(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoListView(Instance).ImageField;
end;

procedure __DC__SetTCustomDCInfoListView__ImageField(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).ImageField:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomDCInfoListView__StateImageField(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoListView(Instance).StateImageField;
end;

procedure __DC__SetTCustomDCInfoListView__StateImageField(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).StateImageField:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomDCInfoListView__Options(Instance : TObject; Params : PVariantArgList) : OleVariant;
var
  tmp : TInfoListOptions;
begin
tmp := TCustomDCInfoListView(Instance).Options;
result := VarFromSet(tmp, sizeof(tmp));
end;

procedure __DC__SetTCustomDCInfoListView__Options(Instance : TObject; Params : PVariantArgList);
var
  tmp : TInfoListOptions;
begin
VarToSet(tmp, sizeof(tmp), Variant(Params^[0]));
TCustomDCInfoListView(Instance).Options:=tmp;
end;

function __DC__GetTCustomDCInfoListView__LargeImages(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoListView(Instance).LargeImages);
end;

procedure __DC__SetTCustomDCInfoListView__LargeImages(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).LargeImages:=TCustomImageList(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoListView__SmallImages(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoListView(Instance).SmallImages);
end;

procedure __DC__SetTCustomDCInfoListView__SmallImages(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).SmallImages:=TCustomImageList(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoListView__StateImages(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoListView(Instance).StateImages);
end;

procedure __DC__SetTCustomDCInfoListView__StateImages(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).StateImages:=TCustomImageList(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoListView__MasterControl(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoListView(Instance).MasterControl);
end;

procedure __DC__SetTCustomDCInfoListView__MasterControl(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).MasterControl:=TComponent(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoListView__UseInfoImages(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoListView(Instance).UseInfoImages;
end;

procedure __DC__SetTCustomDCInfoListView__UseInfoImages(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).UseInfoImages:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomDCInfoListView__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoListView(Instance).Items);
end;

function __DC__GetTCustomDCInfoListView__AutoUpdateColumns(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoListView(Instance).AutoUpdateColumns;
end;

procedure __DC__SetTCustomDCInfoListView__AutoUpdateColumns(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoListView(Instance).AutoUpdateColumns:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomDCInfoTree__LargeImages(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoTree(Instance).LargeImages);
end;

procedure __DC__SetTCustomDCInfoTree__LargeImages(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoTree(Instance).LargeImages:=TCustomImageList(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoTree__StateImages(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoTree(Instance).StateImages);
end;

procedure __DC__SetTCustomDCInfoTree__StateImages(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoTree(Instance).StateImages:=TCustomImageList(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoTree__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoTree(Instance).Items);
end;

function __DC__GetTCustomDCInfoTree__InfoSet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCInfoTree(Instance).InfoSet);
end;

procedure __DC__SetTCustomDCInfoTree__InfoSet(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoTree(Instance).InfoSet:=TComponent(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTCustomDCInfoTree__InfoField(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoTree(Instance).InfoField;
end;

procedure __DC__SetTCustomDCInfoTree__InfoField(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoTree(Instance).InfoField:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomDCInfoTree__Options(Instance : TObject; Params : PVariantArgList) : OleVariant;
var
  tmp : TInfoTreeOptions;
begin
tmp := TCustomDCInfoTree(Instance).Options;
result := VarFromSet(tmp, sizeof(tmp));
end;

procedure __DC__SetTCustomDCInfoTree__Options(Instance : TObject; Params : PVariantArgList);
var
  tmp : TInfoTreeOptions;
begin
VarToSet(tmp, sizeof(tmp), Variant(Params^[0]));
TCustomDCInfoTree(Instance).Options:=tmp;
end;

function __DC__GetTCustomDCInfoTree__ImageField(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoTree(Instance).ImageField;
end;

procedure __DC__SetTCustomDCInfoTree__ImageField(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoTree(Instance).ImageField:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomDCInfoTree__StateImageField(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoTree(Instance).StateImageField;
end;

procedure __DC__SetTCustomDCInfoTree__StateImageField(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoTree(Instance).StateImageField:=OleVariant(Params^[0]);
end;

function __DC__GetTCustomDCInfoTree__UseInfoImages(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TCustomDCInfoTree(Instance).UseInfoImages;
end;

procedure __DC__SetTCustomDCInfoTree__UseInfoImages(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCInfoTree(Instance).UseInfoImages:=OleVariant(Params^[0]);
end;

function __DC__GetTDCInfoListItems__ListView(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TDCInfoListItems(Instance).ListView);
end;

function __DC__GetTDCInfoTreeNodes__Tree(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TDCInfoTreeNodes(Instance).Tree);
end;

function __DC__GetTInfoListItem__BookMark(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TInfoListItem(Instance).BookMark;
end;

procedure __DC__SetTInfoListItem__BookMark(Instance : TObject; Params : PVariantArgList);
begin
TInfoListItem(Instance).BookMark:=OleVariant(Params^[0]);
end;

function __DC__GetTInfoListItem__FieldCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TInfoListItem(Instance).FieldCount;
end;

function __DC__GetTInfoNode__BookMark(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TInfoNode(Instance).BookMark;
end;

procedure __DC__SetTInfoNode__BookMark(Instance : TObject; Params : PVariantArgList);
begin
TInfoNode(Instance).BookMark:=OleVariant(Params^[0]);
end;

function __DC__GetTInfoNode__Loaded(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TInfoNode(Instance).Loaded;
end;

procedure __DC__SetTInfoNode__Loaded(Instance : TObject; Params : PVariantArgList);
begin
TInfoNode(Instance).Loaded:=OleVariant(Params^[0]);
end;

procedure __RegisterProps;
begin
RegisterProperty(TCustomDCInfoListView,'CheckField',__DC__GetTCustomDCInfoListView__CheckField,__DC__SetTCustomDCInfoListView__CheckField);
RegisterProperty(TCustomDCInfoListView,'Fields',__DC__GetTCustomDCInfoListView__Fields,__DC__SetTCustomDCInfoListView__Fields);
RegisterProperty(TCustomDCInfoListView,'UsedFields',__DC__GetTCustomDCInfoListView__UsedFields,nil);
RegisterProperty(TCustomDCInfoListView,'InfoSet',__DC__GetTCustomDCInfoListView__InfoSet,__DC__SetTCustomDCInfoListView__InfoSet);
RegisterProperty(TCustomDCInfoListView,'ImageField',__DC__GetTCustomDCInfoListView__ImageField,__DC__SetTCustomDCInfoListView__ImageField);
RegisterProperty(TCustomDCInfoListView,'StateImageField',__DC__GetTCustomDCInfoListView__StateImageField,__DC__SetTCustomDCInfoListView__StateImageField);
RegisterProperty(TCustomDCInfoListView,'Options',__DC__GetTCustomDCInfoListView__Options,__DC__SetTCustomDCInfoListView__Options);
RegisterProperty(TCustomDCInfoListView,'LargeImages',__DC__GetTCustomDCInfoListView__LargeImages,__DC__SetTCustomDCInfoListView__LargeImages);
RegisterProperty(TCustomDCInfoListView,'SmallImages',__DC__GetTCustomDCInfoListView__SmallImages,__DC__SetTCustomDCInfoListView__SmallImages);
RegisterProperty(TCustomDCInfoListView,'StateImages',__DC__GetTCustomDCInfoListView__StateImages,__DC__SetTCustomDCInfoListView__StateImages);
RegisterProperty(TCustomDCInfoListView,'MasterControl',__DC__GetTCustomDCInfoListView__MasterControl,__DC__SetTCustomDCInfoListView__MasterControl);
RegisterProperty(TCustomDCInfoListView,'UseInfoImages',__DC__GetTCustomDCInfoListView__UseInfoImages,__DC__SetTCustomDCInfoListView__UseInfoImages);
RegisterProperty(TCustomDCInfoListView,'Items',__DC__GetTCustomDCInfoListView__Items,nil);
RegisterProperty(TCustomDCInfoListView,'AutoUpdateColumns',__DC__GetTCustomDCInfoListView__AutoUpdateColumns,__DC__SetTCustomDCInfoListView__AutoUpdateColumns);
RegisterProperty(TCustomDCInfoTree,'LargeImages',__DC__GetTCustomDCInfoTree__LargeImages,__DC__SetTCustomDCInfoTree__LargeImages);
RegisterProperty(TCustomDCInfoTree,'StateImages',__DC__GetTCustomDCInfoTree__StateImages,__DC__SetTCustomDCInfoTree__StateImages);
RegisterProperty(TCustomDCInfoTree,'Items',__DC__GetTCustomDCInfoTree__Items,nil);
RegisterProperty(TCustomDCInfoTree,'InfoSet',__DC__GetTCustomDCInfoTree__InfoSet,__DC__SetTCustomDCInfoTree__InfoSet);
RegisterProperty(TCustomDCInfoTree,'InfoField',__DC__GetTCustomDCInfoTree__InfoField,__DC__SetTCustomDCInfoTree__InfoField);
RegisterProperty(TCustomDCInfoTree,'Options',__DC__GetTCustomDCInfoTree__Options,__DC__SetTCustomDCInfoTree__Options);
RegisterProperty(TCustomDCInfoTree,'ImageField',__DC__GetTCustomDCInfoTree__ImageField,__DC__SetTCustomDCInfoTree__ImageField);
RegisterProperty(TCustomDCInfoTree,'StateImageField',__DC__GetTCustomDCInfoTree__StateImageField,__DC__SetTCustomDCInfoTree__StateImageField);
RegisterProperty(TCustomDCInfoTree,'UseInfoImages',__DC__GetTCustomDCInfoTree__UseInfoImages,__DC__SetTCustomDCInfoTree__UseInfoImages);
RegisterProperty(TDCInfoListItems,'ListView',__DC__GetTDCInfoListItems__ListView,nil);
RegisterProperty(TDCInfoTreeNodes,'Tree',__DC__GetTDCInfoTreeNodes__Tree,nil);
RegisterProperty(TInfoListItem,'BookMark',__DC__GetTInfoListItem__BookMark,__DC__SetTInfoListItem__BookMark);
RegisterProperty(TInfoListItem,'FieldCount',__DC__GetTInfoListItem__FieldCount,nil);
RegisterProperty(TInfoNode,'BookMark',__DC__GetTInfoNode__BookMark,__DC__SetTInfoNode__BookMark);
RegisterProperty(TInfoNode,'Loaded',__DC__GetTInfoNode__Loaded,__DC__SetTInfoNode__Loaded);
end;

const __ConstNames0 : array[0..11] of string = (
'itoTrackRow'
,'itoConfirmDelete'
,'itoOnlyFolders'
,'itoCheckChilds'
,'itoSmartLoad'
,'itoLocateParent'
,'iloTrackRow'
,'iloConfirmDelete'
,'DefaultTreeOptions'
,'DefaultListOptions'
,'RescanTreeOptions'
,'TreeUpdateInterval'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,itoTrackRow));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,itoConfirmDelete));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,itoOnlyFolders));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,itoCheckChilds));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,itoSmartLoad));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,itoLocateParent));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,iloTrackRow));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,iloConfirmDelete));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,VarFromSet(DefaultTreeOptions, sizeof(DefaultTreeOptions))));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,VarFromSet(DefaultListOptions, sizeof(DefaultListOptions))));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,VarFromSet(RescanTreeOptions, sizeof(RescanTreeOptions))));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,TreeUpdateInterval));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..10] of TClass = (
TBaseInfoNode,
TCustomDCInfoListView,
TCustomDCInfoTree,
TDCInfoListItems,
TDCInfoListView,
TDCInfoTree,
TDCInfoTreeNodes,
TInfoListItem,
TInfoNode,
TSortedItemList,
TSortedNodeList
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..1] of string = (
'GetNodeFieldValue'
,'GetItemFieldValue'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TBaseInfoNode),
TypeInfo(string),TypeInfo(Variant)],Addr(GetNodeFieldValue),cRegister);

RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(TListItem),
TypeInfo(string),TypeInfo(Variant)],Addr(GetItemFieldValue),cRegister);

RegRegisterMethod(TCustomDCInfoListView,'RefreshData',TypeInfo(_T2),NoParams,Addr(TCustomDCInfoListView.RefreshData));

RegRegisterMethod(TCustomDCInfoListView,'BookMarkToItem',TypeInfo(_T3),[
TypeInfo(TDCBookMark),TypeInfo(TListItem)],Addr(TCustomDCInfoListView.BookMarkToItem));

RegRegisterMethod(TCustomDCInfoListView,'ReReadItem',TypeInfo(_T4),[
TypeInfo(TListItem)],Addr(TCustomDCInfoListView.ReReadItem));

RegRegisterMethod(TCustomDCInfoListView,'DeleteSelectedItems',TypeInfo(_T5),NoParams,Addr(TCustomDCInfoListView.DeleteSelectedItems));

RegRegisterMethod(TCustomDCInfoListView,'InsertNewItem',TypeInfo(_T6),NoParams,Addr(TCustomDCInfoListView.InsertNewItem));

RegRegisterMethod(TCustomDCInfoListView,'EditSelected',TypeInfo(_T7),NoParams,Addr(TCustomDCInfoListView.EditSelected));

RegRegisterMethod(TCustomDCInfoListView,'SetToItem',TypeInfo(_T8),[
TypeInfo(TListItem),TypeInfo(Boolean)],Addr(TCustomDCInfoListView.SetToItem));

RegRegisterMethod(TCustomDCInfoListView,'SetToItemAndSelect',TypeInfo(_T9),[
TypeInfo(TListItem)],Addr(TCustomDCInfoListView.SetToItemAndSelect));

RegRegisterMethod(TCustomDCInfoTree,'UpdateSelection',TypeInfo(_T10),NoParams,Addr(TCustomDCInfoTree.UpdateSelection));

RegRegisterMethod(TCustomDCInfoTree,'RescanItems',TypeInfo(_T11),[
TypeInfo(TBaseInfoNode)],Addr(TCustomDCInfoTree.RescanItems));

RegRegisterMethod(TCustomDCInfoTree,'RescanNodeWithChildren',TypeInfo(_T12),[
TypeInfo(TBaseInfoNode)],Addr(TCustomDCInfoTree.RescanNodeWithChildren));

RegRegisterMethod(TCustomDCInfoTree,'RefreshData',TypeInfo(_T13),NoParams,Addr(TCustomDCInfoTree.RefreshData));

RegRegisterMethod(TCustomDCInfoTree,'SetToNode',TypeInfo(_T14),[
TypeInfo(TBaseInfoNode),TypeInfo(Boolean)],Addr(TCustomDCInfoTree.SetToNode));

RegRegisterMethod(TCustomDCInfoTree,'SetToNodeAndSelect',TypeInfo(_T15),[
TypeInfo(TBaseInfoNode)],Addr(TCustomDCInfoTree.SetToNodeAndSelect));

RegRegisterMethod(TCustomDCInfoTree,'InsertNewNode',TypeInfo(_T16),[TypeInfo(TBaseInfoNode)],Addr(TCustomDCInfoTree.InsertNewNode));

RegRegisterMethod(TCustomDCInfoTree,'InsertNewSubNode',TypeInfo(_T17),[
TypeInfo(TBaseInfoNode),
TypeInfo(TBaseInfoNode),TypeInfo(TBaseInfoNode)],Addr(TCustomDCInfoTree.InsertNewSubNode));

RegRegisterMethod(TCustomDCInfoTree,'DeleteSelectedNodes',TypeInfo(_T18),NoParams,Addr(TCustomDCInfoTree.DeleteSelectedNodes));

RegRegisterMethod(TCustomDCInfoTree,'EditSelected',TypeInfo(_T19),NoParams,Addr(TCustomDCInfoTree.EditSelected));

RegisterProc(TInfoListItem,'Create',mtConstructor,TypeInfo(_T21),[
TypeInfo(TListItems)],Addr(TInfoListItem.Create),cRegister);

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
{RegRegisterMethod(TCustomDCInfoTree,'GetRowSet',TypeInfo(_T20),[
TypeInfo(TBaseInfoNode),TypeInfo(IDCRowSet)],Addr(TCustomDCInfoTree.GetRowSet))}

{RegisterEvent(TypeInfo(TGetItemParams),[
TypeInfo(TObject),
TypeInfo(TInfoListItem),
TypeInfo(IUnknown)]);}

{RegisterEvent(TypeInfo(TGetNodeParams),[
TypeInfo(TObject),
TypeInfo(TInfoNode),
TypeInfo(IUnknown)]);}

RegisterEvent(TypeInfo(TInfoInsertEvent),[
TypeInfo(TObject),
TypeInfo(TBaseInfoNode),
TypeInfo(Boolean),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TLevelLoadingEvent),[
TypeInfo(TObject),
TypeInfo(TBaseInfoNode)]);

RegisterEvent(TypeInfo(TLInfoInsertEvent),[
TypeInfo(TObject),
TypeInfo(TInfoListItem),
TypeInfo(Boolean),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TLModifyFieldEvent),[
TypeInfo(TObject),
TypeInfo(TInfoListItem),
TypeInfo(string),
TypeInfo(string),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TLModifyInfoEvent),[
TypeInfo(TObject),
TypeInfo(TInfoListItem),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TModifyFieldEvent),[
TypeInfo(TObject),
TypeInfo(TBaseInfoNode),
TypeInfo(string),
TypeInfo(string),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TModifyInfoEvent),[
TypeInfo(TObject),
TypeInfo(TBaseInfoNode),
TypeInfo(Boolean)]);

RegisterEvent(TypeInfo(TNodeLoadedEvent),[
TypeInfo(TObject),
TypeInfo(TBaseInfoNode)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
