{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit dcjoininfoset_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  Windows,
  Classes,
  SysUtils,
  dcInfoDB,
  dcConsts,
  dcdreamLib,
  dcInfoLib,
  dcJoinInfoSet;
function ConvertTGUIDToVariant(var R : TGUID) : OleVariant;
function ConvertVariantToTGUID(const V : OleVariant) : TGUID;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TGUID__Wrapper = class(TDCRecordWrapper)
private
fR : TGUID;
public
function GetRecordPtr : pointer; override;
published
procedure setD1(const val : LongWord);
function getD1 : LongWord;
property D1 : LongWord read getD1 write setD1;
procedure setD2(const val : Word);
function getD2 : Word;
property D2 : Word read getD2 write setD2;
procedure setD3(const val : Word);
function getD3 : Word;
property D3 : Word read getD3 write setD3;
end;
type __TCustomDCJoinRelation__ = class(TCustomDCJoinRelation);
type
_T0 = function (const p0 : IDispatch;
out p1): HResult of object;

{_T1 = procedure (const p0 : PEventRec) of object;}

_T2 = procedure  of object;

_T3 = function : TDCJoinRelations of object;

{_T4 = procedure (const p0 : PEventRec) of object;}

_T5 = procedure (p0 : TComponent) of object;

_T6 = procedure (p0 : TJoinInfoSet) of object;

function __TGUID__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TGUID__Wrapper.setD1(const val : LongWord);
begin
TGUID(GetRecordPtr^).D1 := val;
end;
function __TGUID__Wrapper.getD1 : LongWord;
begin
result := TGUID(GetRecordPtr^).D1;
end;
procedure __TGUID__Wrapper.setD2(const val : Word);
begin
TGUID(GetRecordPtr^).D2 := val;
end;
function __TGUID__Wrapper.getD2 : Word;
begin
result := TGUID(GetRecordPtr^).D2;
end;
procedure __TGUID__Wrapper.setD3(const val : Word);
begin
TGUID(GetRecordPtr^).D3 := val;
end;
function __TGUID__Wrapper.getD3 : Word;
begin
result := TGUID(GetRecordPtr^).D3;
end;
function __TCustomDCJoinRelation__QueryInterface__Wrapper(__Instance : TCustomDCJoinRelation;
const p0 : IDispatch;
out p1): HResult;
var
__p0 : ^TGUID;
__i0 : IDispatch;
begin
if p0 = nil then exit;
__p0 := (p0 as IDCRecordWrapper).GetRecordPtr;
result := __TCustomDCJoinRelation__(__Instance).QueryInterface(__p0^,p1);
end;


type __TGUID__Wrapper__ = class(__TGUID__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TGUID__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTGUIDToVariant(var R : TGUID) : OleVariant;
var
__rw : __TGUID__Wrapper__;
begin
__rw := __TGUID__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTGUID(const V : OleVariant) : TGUID;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TGUID((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
function __DC__GetTCustomDCJoinRelation__InfoSet(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TCustomDCJoinRelation(Instance).InfoSet);
end;

procedure __DC__SetTCustomDCJoinRelation__InfoSet(Instance : TObject; Params : PVariantArgList);
begin
TCustomDCJoinRelation(Instance).InfoSet:=TComponent(VarToObject(OleVariant(Params^[0])));
end;

function __DC__GetTDBJoinRelations__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TDBJoinRelations(Instance).Items[OleVariant(Params^[0])]);
end;

function __DC__GetTDCJoinRelations__Items(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TDCJoinRelations(Instance).Items[OleVariant(Params^[0])]);
end;

function __DC__GetTJoinInfoSet__Relations(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(TJoinInfoSet(Instance).Relations);
end;

procedure __DC__SetTJoinInfoSet__Relations(Instance : TObject; Params : PVariantArgList);
begin
TJoinInfoSet(Instance).Relations:=TDCJoinRelations(VarToObject(OleVariant(Params^[0])));
end;

procedure __RegisterProps;
begin
RegisterProperty(TCustomDCJoinRelation,'InfoSet',__DC__GetTCustomDCJoinRelation__InfoSet,__DC__SetTCustomDCJoinRelation__InfoSet);
RegisterIndexedProperty(TDBJoinRelations,'Items',1,True,__DC__GetTDBJoinRelations__Items,nil);
RegisterIndexedProperty(TDCJoinRelations,'Items',1,True,__DC__GetTDCJoinRelations__Items,nil);
RegisterProperty(TJoinInfoSet,'Relations',__DC__GetTJoinInfoSet__Relations,__DC__SetTJoinInfoSet__Relations);
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..8] of TClass = (
TCustomDCJoinInfoSet,
TCustomDCJoinRelation,
TDBJoinRelation,
TDBJoinRelations,
TDCDBJoinInfoSet,
TDCJoinRelation,
TDCJoinRelations,
TJoinInfoSet,
TNavigationWrapper
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegisterProc(TCustomDCJoinRelation,'QueryInterface',mtMethod,TypeInfo(_T0),[
TypeInfo(IDispatch),
TypeInfoUntyped,TypeInfo(HResult)], pointer(36),cRegister);

RegRegisterMethod(TDCJoinRelations,'Updated',TypeInfo(_T2),NoParams, pointer(44));

RegRegisterMethod(TJoinInfoSet,'CreateRelations',TypeInfo(_T3),[TypeInfo(TDCJoinRelations)], pointer(4));

RegisterProc(TJoinInfoSet,'Create',mtConstructor,TypeInfo(_T5),[
TypeInfo(TComponent)], pointer(12),cRegister);

RegisterProc(TNavigationWrapper,'Create',mtConstructor,TypeInfo(_T6),[
TypeInfo(TJoinInfoSet)],Addr(TNavigationWrapper.Create),cRegister);

end;
initialization
_mreg_0;
{RegRegisterMethod(TCustomDCJoinRelation,'HandleEvent',TypeInfo(_T1),[
TypeInfoPointer], pointer(40))}

{RegRegisterMethod(TJoinInfoSet,'HandleEvent',TypeInfo(_T4),[
TypeInfoPointer], pointer(8))}

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
