{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit dctred_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Types,
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Graphics,
  dcntree,
  Forms,
  Dialogs,
  StdCtrls,
  Controls,
  Classes,
  ExtCtrls,
  DCColorCombo,
  dcTrEd;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TRect__Wrapper = class(TDCRecordWrapper)
private
fR : TRect;
public
function GetRecordPtr : pointer; override;
published
procedure setLeft(const val : Longint);
function getLeft : Longint;
property Left : Longint read getLeft write setLeft;
procedure setTop(const val : Longint);
function getTop : Longint;
property Top : Longint read getTop write setTop;
procedure setRight(const val : Longint);
function getRight : Longint;
property Right : Longint read getRight write setRight;
procedure setBottom(const val : Longint);
function getBottom : Longint;
property Bottom : Longint read getBottom write setBottom;
end;
type
_T0 = function (p0 : TDCTree): Boolean of object;

{_T1 = function (p0 : TDCCustomTreeView;
p1 : TfrmTreeNodesEditorClass): Boolean of object;}

_T2 = procedure (p0 : TObject) of object;

_T3 = _T2;

_T4 = _T2;

_T5 = _T2;

_T6 = _T2;

_T7 = _T2;

_T8 = _T2;

_T9 = _T2;

_T10 = _T2;

_T11 = _T2;

_T12 = procedure (p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState) of object;

_T13 = procedure (p0 : TObject;
p1 : TMouseButton;
p2 : TShiftState;
p3 : Integer;
p4 : Integer) of object;

_T14 = _T2;

_T15 = _T2;

_T16 = _T2;

_T17 = _T2;

_T18 = _T2;

_T19 = _T2;

_T20 = _T2;

_T21 = _T2;

_T22 = _T2;

_T23 = _T2;

_T24 = _T2;

_T25 = _T2;

_T26 = procedure (p0 : TObject;
var p1 : Word;
p2 : TShiftState) of object;

_T27 = _T2;

_T28 = _T2;

_T29 = _T2;

_T30 = _T2;

_T31 = procedure (p0 : TObject;
var p1 : Char) of object;

_T32 = _T2;

_T33 = procedure (p0 : Boolean) of object;

_T34 = function (p0 : TDCCustomTreeView;
p1 : TDCTreeNode): string of object;

_T35 = procedure  of object;

_T36 = procedure (const p0 : string) of object;

{_T37 = procedure (p0 : TComponent;
p1 : TDCCustomTreeViewClass) of object;}

_T38 = function (p0 : TDCCustomTreeView): Boolean of object;

_T39 = procedure (p0 : TDCCustomTreeView;
p1 : TDCCustomTreeView) of object;

_T40 = _T39;

function __TRect__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TRect__Wrapper.setLeft(const val : Longint);
begin
TRect(GetRecordPtr^).Left := val;
end;
function __TRect__Wrapper.getLeft : Longint;
begin
result := TRect(GetRecordPtr^).Left;
end;
procedure __TRect__Wrapper.setTop(const val : Longint);
begin
TRect(GetRecordPtr^).Top := val;
end;
function __TRect__Wrapper.getTop : Longint;
begin
result := TRect(GetRecordPtr^).Top;
end;
procedure __TRect__Wrapper.setRight(const val : Longint);
begin
TRect(GetRecordPtr^).Right := val;
end;
function __TRect__Wrapper.getRight : Longint;
begin
result := TRect(GetRecordPtr^).Right;
end;
procedure __TRect__Wrapper.setBottom(const val : Longint);
begin
TRect(GetRecordPtr^).Bottom := val;
end;
function __TRect__Wrapper.getBottom : Longint;
begin
result := TRect(GetRecordPtr^).Bottom;
end;
procedure __TfrmTreeNodesEditor__lbxImagesDrawItem__Wrapper(__Instance : TfrmTreeNodesEditor;
p0 : TWinControl;
p1 : Integer;
const p2 : IDispatch;
p3 : TOwnerDrawState);
var
__p2 : ^TRect;
__i2 : IDispatch;
begin
if p2 = nil then exit;
__p2 := (p2 as IDCRecordWrapper).GetRecordPtr;
TfrmTreeNodesEditor(__Instance).lbxImagesDrawItem(p0,p1,__p2^,p3);
end;


type __TRect__Wrapper__ = class(__TRect__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TRect__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
var
__rw : __TRect__Wrapper__;
begin
__rw := __TRect__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TRect((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

function __DC__GetdcTrEd__frmTreeNodesEditor(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(dcTrEd.frmTreeNodesEditor);
end;

procedure __DC__SetdcTrEd__frmTreeNodesEditor(Instance : TObject; Params : PVariantArgList);
begin
TObject(dcTrEd.frmTreeNodesEditor):=(VarToObject(OleVariant(Params^[0])));
end;

var __RegisteredVars : TList;
procedure __RegisterVars;
begin
__RegisteredVars := TList.Create;
__RegisteredVars.Add(RegisterVar('frmTreeNodesEditor',__DC__GetdcTrEd__frmTreeNodesEditor,__DC__SetdcTrEd__frmTreeNodesEditor));
end;

procedure __UnregisterVars;
begin
__RegisteredVars.Free;
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TfrmTreeNodesEditor
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..0] of string = (
'EditItems'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TDCTree),TypeInfo(Boolean)],Addr(EditItems),cRegister);

RegRegisterMethod(TfrmTreeNodesEditor,'btnSelectFontClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnSelectFontClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnNewItemClick',TypeInfo(_T3),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnNewItemClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnNewSubItemClick',TypeInfo(_T4),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnNewSubItemClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnDeleteClick',TypeInfo(_T5),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnDeleteClick));

RegRegisterMethod(TfrmTreeNodesEditor,'chkParentFontClick',TypeInfo(_T6),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.chkParentFontClick));

RegRegisterMethod(TfrmTreeNodesEditor,'chkAllowGrayedClick',TypeInfo(_T7),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.chkAllowGrayedClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnApplyClick',TypeInfo(_T8),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnApplyClick));

RegRegisterMethod(TfrmTreeNodesEditor,'chkReadOnlyClick',TypeInfo(_T9),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.chkReadOnlyClick));

RegRegisterMethod(TfrmTreeNodesEditor,'chkParentColorClick',TypeInfo(_T10),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.chkParentColorClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnIndexClick',TypeInfo(_T11),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnIndexClick));

RegRegisterMethod(TfrmTreeNodesEditor,'lbxImagesDrawItem',TypeInfo(_T12),[
TypeInfo(TWinControl),
TypeInfo(Integer),
TypeInfo(IDispatch),
TypeInfo(TOwnerDrawState)],Addr(__TfrmTreeNodesEditor__lbxImagesDrawItem__Wrapper));

RegRegisterMethod(TfrmTreeNodesEditor,'lbxImagesMouseUp',TypeInfo(_T13),[
TypeInfo(TObject),
TypeInfo(TMouseButton),
TypeInfo(TShiftState),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrmTreeNodesEditor.lbxImagesMouseUp));

RegRegisterMethod(TfrmTreeNodesEditor,'btnMoveUpClick',TypeInfo(_T14),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnMoveUpClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnMoveDnClick',TypeInfo(_T15),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnMoveDnClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnClearClick',TypeInfo(_T16),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnClearClick));

RegRegisterMethod(TfrmTreeNodesEditor,'txtTextChange',TypeInfo(_T17),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.txtTextChange));

RegRegisterMethod(TfrmTreeNodesEditor,'txtImageIndexChange',TypeInfo(_T18),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.txtImageIndexChange));

RegRegisterMethod(TfrmTreeNodesEditor,'txtSelectedIndexChange',TypeInfo(_T19),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.txtSelectedIndexChange));

RegRegisterMethod(TfrmTreeNodesEditor,'txtStateIndexChange',TypeInfo(_T20),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.txtStateIndexChange));

RegRegisterMethod(TfrmTreeNodesEditor,'txtOverlayIndexChange',TypeInfo(_T21),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.txtOverlayIndexChange));

RegRegisterMethod(TfrmTreeNodesEditor,'cbxNodeTypeChange',TypeInfo(_T22),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.cbxNodeTypeChange));

RegRegisterMethod(TfrmTreeNodesEditor,'cbxStateChange',TypeInfo(_T23),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.cbxStateChange));

RegRegisterMethod(TfrmTreeNodesEditor,'btnLoadClick',TypeInfo(_T24),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnLoadClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnSaveClick',TypeInfo(_T25),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnSaveClick));

RegRegisterMethod(TfrmTreeNodesEditor,'FormKeyDown',TypeInfo(_T26),[
TypeInfo(TObject),
TypeInfo(Word),
TypeInfo(TShiftState)],Addr(TfrmTreeNodesEditor.FormKeyDown));

RegRegisterMethod(TfrmTreeNodesEditor,'cbxFontColorChange',TypeInfo(_T27),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.cbxFontColorChange));

RegRegisterMethod(TfrmTreeNodesEditor,'cbxColorChange',TypeInfo(_T28),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.cbxColorChange));

RegRegisterMethod(TfrmTreeNodesEditor,'btnFontColorClick',TypeInfo(_T29),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnFontColorClick));

RegRegisterMethod(TfrmTreeNodesEditor,'btnColorClick',TypeInfo(_T30),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.btnColorClick));

RegRegisterMethod(TfrmTreeNodesEditor,'txtIndexKeyPress',TypeInfo(_T31),[
TypeInfo(TObject),
TypeInfo(Char)],Addr(TfrmTreeNodesEditor.txtIndexKeyPress));

RegRegisterMethod(TfrmTreeNodesEditor,'FormCreate',TypeInfo(_T32),[
TypeInfo(TObject)],Addr(TfrmTreeNodesEditor.FormCreate));

RegRegisterMethod(TfrmTreeNodesEditor,'SetControlsEnabled',TypeInfo(_T33),[
TypeInfo(Boolean)], pointer(240));

RegRegisterMethod(TfrmTreeNodesEditor,'GetNodeText',TypeInfo(_T34),[
TypeInfo(TDCCustomTreeView),
TypeInfo(TDCTreeNode),TypeInfo(string)], pointer(244));

RegRegisterMethod(TfrmTreeNodesEditor,'GetItemProps',TypeInfo(_T35),NoParams, pointer(248));

RegRegisterMethod(TfrmTreeNodesEditor,'UpdateTextEdit',TypeInfo(_T36),[
TypeInfo(string)], pointer(252));

RegRegisterMethod(TfrmTreeNodesEditor,'Execute',TypeInfo(_T38),[
TypeInfo(TDCCustomTreeView),TypeInfo(Boolean)],Addr(TfrmTreeNodesEditor.Execute));

RegRegisterMethod(TfrmTreeNodesEditor,'AssignBefore',TypeInfo(_T39),[
TypeInfo(TDCCustomTreeView),
TypeInfo(TDCCustomTreeView)], pointer(256));

RegRegisterMethod(TfrmTreeNodesEditor,'AssignAfter',TypeInfo(_T40),[
TypeInfo(TDCCustomTreeView),
TypeInfo(TDCCustomTreeView)], pointer(260));

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
{RegisterProc(nil,'_EditItems',mtProc,TypeInfo(_T1),[
TypeInfo(TDCCustomTreeView),
TypeInfo(TfrmTreeNodesEditorClass),TypeInfo(Boolean)],Addr(_EditItems),cRegister)}

{RegisterProc(TfrmTreeNodesEditor,'Create2',mtConstructor,TypeInfo(_T37),[
TypeInfo(TComponent),
TypeInfo(TDCCustomTreeViewClass)],Addr(TfrmTreeNodesEditor.Create2),cRegister)}

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
__RegisterVars;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnRegisterVars;
__UnregisterProcs;
end.
