{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit dctreegrideditorsreg_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Classes,
  Controls,
  dctreegrid,
  dcTreeGridEditorsReg;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..6] of string = (
'CBooleanEditor'
,'CCalculatorEditor'
,'CCurrencyEditor'
,'CDateEditor'
,'CDateTimeEditor'
,'CMemoEditor'
,'CPickListEditor'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,CBooleanEditor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,CCalculatorEditor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,CCurrencyEditor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,CDateEditor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,CDateTimeEditor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,CMemoEditor));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,CPickListEditor));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

procedure _mreg_0;
begin
end;
initialization
_mreg_0;
{RegisterProc(nil,'RegisterTreeGridEditor',mtProc,TypeInfo(_T0),[
TypeInfo(TControlClass),
TypeInfo(string)],Addr(RegisterTreeGridEditor),cRegister)}

{RegisterProc(nil,'GetTreeGridEditorByName',mtProc,TypeInfo(_T1),[
TypeInfo(string),TypeInfo(TControlClass)],Addr(GetTreeGridEditorByName),cRegister)}

{RegisterProc(nil,'EnumTreeGridEditors',mtProc,TypeInfo(_T2),[
TypeInfo(TGetStrProc)],Addr(EnumTreeGridEditors),cRegister)}

{RegisterProc(nil,'RegisterEditorPropsClass',mtProc,TypeInfo(_T3),[
TypeInfo(string),
TypeInfo(TEditorPropsClass)],Addr(RegisterEditorPropsClass),cRegister)}

{RegisterProc(nil,'GetEditorPropsClass',mtProc,TypeInfo(_T4),[
TypeInfo(string),TypeInfo(TEditorPropsClass)],Addr(GetEditorPropsClass),cRegister)}

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
