{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit OleAuto_d6;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  classes,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Ole2,
  OleCtl,
  SysUtils,
  OleAuto;
function ConvertTAutoClassInfoToVariant(var R : TAutoClassInfo) : OleVariant;
function ConvertVariantToTAutoClassInfo(const V : OleVariant) : TAutoClassInfo;
function ConvertTExcepInfoToVariant(var R : TExcepInfo) : OleVariant;
function ConvertVariantToTExcepInfo(const V : OleVariant) : TExcepInfo;
implementation
{$IFDEF D3}
{$ELSE}
type
  OleVariant = Variant;
{$ENDIF}
type __TAutoClassInfo__Wrapper = class(TDCRecordWrapper)
private
fR : TAutoClassInfo;
public
function GetRecordPtr : pointer; override;
published
procedure setProgID(const val : AnsiString);
function getProgID : AnsiString;
property ProgID : AnsiString read getProgID write setProgID;
procedure setClassID(const val : AnsiString);
function getClassID : AnsiString;
property ClassID : AnsiString read getClassID write setClassID;
procedure setDescription(const val : AnsiString);
function getDescription : AnsiString;
property Description : AnsiString read getDescription write setDescription;
procedure setInstancing(const val : TAutoClassInstancing);
function getInstancing : TAutoClassInstancing;
property Instancing : TAutoClassInstancing read getInstancing write setInstancing;
end;
type __TExcepInfo__Wrapper = class(TDCRecordWrapper)
private
fR : TExcepInfo;
public
function GetRecordPtr : pointer; override;
published
procedure setwCode(const val : Word);
function getwCode : Word;
property wCode : Word read getwCode write setwCode;
procedure setwReserved(const val : Word);
function getwReserved : Word;
property wReserved : Word read getwReserved write setwReserved;
procedure setdwHelpContext(const val : Longint);
function getdwHelpContext : Longint;
property dwHelpContext : Longint read getdwHelpContext write setdwHelpContext;
end;
type __TAutoObject__ = class(TAutoObject);
type
_T0 = function (const p0 : string): Variant of object;

_T1 = _T0;

_T3 = function : HResult of object;

_T4 = _T3;

_T5 = _T3;

_T6 = function (p0 : IUnknown): Variant of object;

_T7 = function (const p0 : Variant): IDispatch of object;

_T8 = function (const p0 : Variant): TAutoObject of object;

{_T9 = procedure (p0 : IDispatch;
p1 : PCallDesc;
p2 : PDispIDList;
p3 : Pointer;
p4 : PVariant) of object;}

_T10 = procedure (p0 : HResult;
const p1 : IDispatch) of object;

_T11 = procedure (p0 : HResult) of object;

_T12 = _T11;

_T17 = procedure  of object;

_T18 = procedure (const p0 : IDispatch) of object;

_T19 = procedure (p0 : Boolean) of object;

{_T20 = function : TAutoDispatch of object;}

_T21 = procedure (p0 : TObject;
const p1 : IDispatch) of object;

_T22 = _T17;

_T23 = function : Integer of object;

_T24 = _T23;

_T25 = _T18;

_T26 = _T19;

function __TAutoClassInfo__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TAutoClassInfo__Wrapper.setProgID(const val : AnsiString);
begin
TAutoClassInfo(GetRecordPtr^).ProgID := val;
end;
function __TAutoClassInfo__Wrapper.getProgID : AnsiString;
begin
result := TAutoClassInfo(GetRecordPtr^).ProgID;
end;
procedure __TAutoClassInfo__Wrapper.setClassID(const val : AnsiString);
begin
TAutoClassInfo(GetRecordPtr^).ClassID := val;
end;
function __TAutoClassInfo__Wrapper.getClassID : AnsiString;
begin
result := TAutoClassInfo(GetRecordPtr^).ClassID;
end;
procedure __TAutoClassInfo__Wrapper.setDescription(const val : AnsiString);
begin
TAutoClassInfo(GetRecordPtr^).Description := val;
end;
function __TAutoClassInfo__Wrapper.getDescription : AnsiString;
begin
result := TAutoClassInfo(GetRecordPtr^).Description;
end;
procedure __TAutoClassInfo__Wrapper.setInstancing(const val : TAutoClassInstancing);
begin
TAutoClassInfo(GetRecordPtr^).Instancing := val;
end;
function __TAutoClassInfo__Wrapper.getInstancing : TAutoClassInstancing;
begin
result := TAutoClassInfo(GetRecordPtr^).Instancing;
end;
function _TAutoClassInfo_ : IDispatch;
begin
  result := __TAutoClassInfo__Wrapper.Create;
end;
function __TExcepInfo__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TExcepInfo__Wrapper.setwCode(const val : Word);
begin
TExcepInfo(GetRecordPtr^).wCode := val;
end;
function __TExcepInfo__Wrapper.getwCode : Word;
begin
result := TExcepInfo(GetRecordPtr^).wCode;
end;
procedure __TExcepInfo__Wrapper.setwReserved(const val : Word);
begin
TExcepInfo(GetRecordPtr^).wReserved := val;
end;
function __TExcepInfo__Wrapper.getwReserved : Word;
begin
result := TExcepInfo(GetRecordPtr^).wReserved;
end;
procedure __TExcepInfo__Wrapper.setdwHelpContext(const val : Longint);
begin
TExcepInfo(GetRecordPtr^).dwHelpContext := val;
end;
function __TExcepInfo__Wrapper.getdwHelpContext : Longint;
begin
result := TExcepInfo(GetRecordPtr^).dwHelpContext;
end;
procedure ____DispInvokeError__Wrapper(p0 : HResult;
const p1 : IDispatch);
var
__p1 : ^TExcepInfo;
__i1 : IDispatch;
begin
if p1 = nil then exit;
__p1 := (p1 as IDCRecordWrapper).GetRecordPtr;
DispInvokeError(p0,__p1^);
end;

procedure __TAutomation__RegisterClass__Wrapper(__Instance : TAutomation;
const p0 : IDispatch);
var
__p0 : ^TAutoClassInfo;
__i0 : IDispatch;
begin
if p0 = nil then exit;
__p0 := (p0 as IDCRecordWrapper).GetRecordPtr;
TAutomation(__Instance).RegisterClass(__p0^);
end;

procedure __TAutoObject__GetExceptionInfo__Wrapper(__Instance : TAutoObject;
p0 : TObject;
const p1 : IDispatch);
var
__p1 : ^TExcepInfo;
__i1 : IDispatch;
begin
if p1 = nil then exit;
__p1 := (p1 as IDCRecordWrapper).GetRecordPtr;
__TAutoObject__(__Instance).GetExceptionInfo(p0,__p1^);
end;

procedure __TRegistryClass__Create__Wrapper(__Instance : TRegistryClass;
const p0 : IDispatch);
var
__p0 : ^TAutoClassInfo;
__i0 : IDispatch;
begin
if p0 = nil then exit;
__p0 := (p0 as IDCRecordWrapper).GetRecordPtr;
TRegistryClass(__Instance).Create(__p0^);
end;


type __TAutoClassInfo__Wrapper__ = class(__TAutoClassInfo__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TAutoClassInfo__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTAutoClassInfoToVariant(var R : TAutoClassInfo) : OleVariant;
var
__rw : __TAutoClassInfo__Wrapper__;
begin
__rw := __TAutoClassInfo__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTAutoClassInfo(const V : OleVariant) : TAutoClassInfo;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TAutoClassInfo((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;

type __TExcepInfo__Wrapper__ = class(__TExcepInfo__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TExcepInfo__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTExcepInfoToVariant(var R : TExcepInfo) : OleVariant;
var
__rw : __TExcepInfo__Wrapper__;
begin
__rw := __TExcepInfo__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTExcepInfo(const V : OleVariant) : TExcepInfo;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TExcepInfo((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
function __DC__GetTAutomation__AutoObjectCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TAutomation(Instance).AutoObjectCount;
end;

function __DC__GetTAutomation__IsInprocServer(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TAutomation(Instance).IsInprocServer;
end;

procedure __DC__SetTAutomation__IsInprocServer(Instance : TObject; Params : PVariantArgList);
begin
TAutomation(Instance).IsInprocServer:=OleVariant(Params^[0]);
end;

function __DC__GetTAutomation__StartMode(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TAutomation(Instance).StartMode;
end;

function __DC__GetTAutoObject__OleObject(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TAutoObject(Instance).OleObject;
end;

function __DC__GetTAutoObject__RefCount(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := TAutoObject(Instance).RefCount;
end;

procedure __RegisterProps;
begin
RegisterProperty(TAutomation,'AutoObjectCount',__DC__GetTAutomation__AutoObjectCount,nil);
RegisterProperty(TAutomation,'IsInprocServer',__DC__GetTAutomation__IsInprocServer,__DC__SetTAutomation__IsInprocServer);
RegisterProperty(TAutomation,'StartMode',__DC__GetTAutomation__StartMode,nil);
RegisterProperty(TAutoObject,'OleObject',__DC__GetTAutoObject__OleObject,nil);
RegisterProperty(TAutoObject,'RefCount',__DC__GetTAutoObject__RefCount,nil);
end;

function __DC__GetOleAuto__Automation(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := VarFromObject(OleAuto.Automation);
end;

procedure __DC__SetOleAuto__Automation(Instance : TObject; Params : PVariantArgList);
begin
TObject(OleAuto.Automation):=(VarToObject(OleVariant(Params^[0])));
end;

var __RegisteredVars : TList;
procedure __RegisterVars;
begin
__RegisteredVars := TList.Create;
__RegisteredVars.Add(RegisterVar('Automation',__DC__GetOleAuto__Automation,__DC__SetOleAuto__Automation));
end;

procedure __UnregisterVars;
begin
__RegisteredVars.Free;
end;

const __ConstNames0 : array[0..7] of string = (
'MaxDispArgs'
,'acInternal'
,'acSingleInstance'
,'acMultiInstance'
,'smStandalone'
,'smAutomation'
,'smRegServer'
,'smUnregServer'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,MaxDispArgs));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,acInternal));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,acSingleInstance));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,acMultiInstance));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,smStandalone));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,smAutomation));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,smRegServer));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,smUnregServer));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..3] of TClass = (
EOleError,
TAutomation,
TAutoObject,
TRegistryClass
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..11] of string = (
'TAutoClassInfo'
,'CreateOleObject'
,'GetActiveOleObject'
,'DllCanUnloadNow'
,'DllRegisterServer'
,'DllUnregisterServer'
,'VarFromInterface'
,'VarToInterface'
,'VarToAutoObject'
,'DispInvokeError'
,'OleError'
,'OleCheck'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
__RegisteredMethods.Add(RegisterRWProc(MethodNames[0],Addr(_TAutoClassInfo_)));
RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T0),[
TypeInfo(string),TypeInfo(Variant)],Addr(CreateOleObject),cRegister);

RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T1),[
TypeInfo(string),TypeInfo(Variant)],Addr(GetActiveOleObject),cRegister);

RegisterProc(nil,MethodNames[3],mtProc,TypeInfo(_T3),[TypeInfo(HResult)],Addr(DllCanUnloadNow),cStdCall);

RegisterProc(nil,MethodNames[4],mtProc,TypeInfo(_T4),[TypeInfo(HResult)],Addr(DllRegisterServer),cStdCall);

RegisterProc(nil,MethodNames[5],mtProc,TypeInfo(_T5),[TypeInfo(HResult)],Addr(DllUnregisterServer),cStdCall);

RegisterProc(nil,MethodNames[6],mtProc,TypeInfo(_T6),[
TypeInfo(IUnknown),TypeInfo(Variant)],Addr(VarFromInterface),cRegister);

RegisterProc(nil,MethodNames[7],mtProc,TypeInfo(_T7),[
TypeInfo(Variant),TypeInfo(IDispatch)],Addr(VarToInterface),cRegister);

RegisterProc(nil,MethodNames[8],mtProc,TypeInfo(_T8),[
TypeInfo(Variant),TypeInfo(TAutoObject)],Addr(VarToAutoObject),cRegister);

RegisterProc(nil,MethodNames[9],mtProc,TypeInfo(_T10),[
TypeInfo(HResult),
TypeInfo(IDispatch)],Addr(____DispInvokeError__Wrapper),cRegister);

RegisterProc(nil,MethodNames[10],mtProc,TypeInfo(_T11),[
TypeInfo(HResult)],Addr(OleError),cRegister);

RegisterProc(nil,MethodNames[11],mtProc,TypeInfo(_T12),[
TypeInfo(HResult)],Addr(OleCheck),cRegister);

RegisterProc(TAutomation,'Create',mtConstructor,TypeInfo(_T17),NoParams,Addr(TAutomation.Create),cRegister);

RegRegisterMethod(TAutomation,'RegisterClass',TypeInfo(_T18),[
TypeInfo(IDispatch)],Addr(__TAutomation__RegisterClass__Wrapper));

RegRegisterMethod(TAutomation,'UpdateRegistry',TypeInfo(_T19),[
TypeInfo(Boolean)],Addr(TAutomation.UpdateRegistry));

RegRegisterMethod(TAutoObject,'GetExceptionInfo',TypeInfo(_T21),[
TypeInfo(TObject),
TypeInfo(IDispatch)], pointer(4));

RegisterProc(TAutoObject,'Create',mtConstructor,TypeInfo(_T22),NoParams, pointer(8),cRegister);

RegRegisterMethod(TAutoObject,'AddRef',TypeInfo(_T23),[TypeInfo(Integer)],Addr(TAutoObject.AddRef));

RegRegisterMethod(TAutoObject,'Release',TypeInfo(_T24),[TypeInfo(Integer)],Addr(TAutoObject.Release));

RegisterProc(TRegistryClass,'Create',mtConstructor,TypeInfo(_T25),[
TypeInfo(IDispatch)],Addr(__TRegistryClass__Create__Wrapper),cRegister);

RegRegisterMethod(TRegistryClass,'UpdateRegistry',TypeInfo(_T26),[
TypeInfo(Boolean)],Addr(TRegistryClass.UpdateRegistry));

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
{RegisterProc(nil,'DispInvoke',mtProc,TypeInfo(_T9),[
TypeInfo(IDispatch),
TypeInfoPointer,
TypeInfoPointer,
TypeInfoPointer,
TypeInfoPointer],Addr(DispInvoke),cRegister)}

{RegRegisterMethod(TAutoObject,'CreateAutoDispatch',TypeInfo(_T20),[TypeInfo(TAutoDispatch)], pointer(0))}

RegisterEvent(TypeInfo(TLastReleaseEvent),[
TypeInfo(Boolean)]);

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;
__RegisterVars;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnRegisterVars;
__UnregisterProcs;
end.
