{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit MyShellAPI_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  classes,
  dcscript,
  dcsystem,
  dcdreamlib,
  ShellAPI,
  MyShellAPI;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = function (const p0 : string;
const p1 : string;
const p2 : string;
const p3 : string;
p4 : Integer): Integer of object;

procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..27] of string = (
'SW_HIDE'
,'SW_SHOWNORMAL'
,'SW_NORMAL'
,'SW_SHOWMINIMIZED'
,'SW_SHOWMAXIMIZED'
,'SW_MAXIMIZE'
,'SW_SHOWNOACTIVATE'
,'SW_SHOW'
,'SW_MINIMIZE'
,'SW_SHOWMINNOACTIVE'
,'SW_SHOWNA'
,'SW_RESTORE'
,'SW_SHOWDEFAULT'
,'SW_MAX'
,'ERROR_FILE_NOT_FOUND'
,'ERROR_PATH_NOT_FOUND'
,'ERROR_BAD_FORMAT'
,'SE_ERR_FNF'
,'SE_ERR_PNF'
,'SE_ERR_ACCESSDENIED'
,'SE_ERR_OOM'
,'SE_ERR_DLLNOTFOUND'
,'SE_ERR_SHARE'
,'SE_ERR_ASSOCINCOMPLETE'
,'SE_ERR_DDETIMEOUT'
,'SE_ERR_DDEFAIL'
,'SE_ERR_DDEBUSY'
,'SE_ERR_NOASSOC'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,SW_HIDE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,SW_SHOWNORMAL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,SW_NORMAL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,SW_SHOWMINIMIZED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,SW_SHOWMAXIMIZED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,SW_MAXIMIZE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,SW_SHOWNOACTIVATE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,SW_SHOW));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,SW_MINIMIZE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,SW_SHOWMINNOACTIVE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,SW_SHOWNA));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,SW_RESTORE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,SW_SHOWDEFAULT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,SW_MAX));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,ERROR_FILE_NOT_FOUND));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,ERROR_PATH_NOT_FOUND));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,ERROR_BAD_FORMAT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,SE_ERR_FNF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[18] ,SE_ERR_PNF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[19] ,SE_ERR_ACCESSDENIED));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[20] ,SE_ERR_OOM));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[21] ,SE_ERR_DLLNOTFOUND));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[22] ,SE_ERR_SHARE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[23] ,SE_ERR_ASSOCINCOMPLETE));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[24] ,SE_ERR_DDETIMEOUT));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[25] ,SE_ERR_DDEFAIL));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[26] ,SE_ERR_DDEBUSY));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[27] ,SE_ERR_NOASSOC));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..0] of string = (
'ExecuteFile'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

procedure _mreg_0;
begin
RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(string),
TypeInfo(string),
TypeInfo(string),
TypeInfo(string),
TypeInfo(Integer),TypeInfo(Integer)],Addr(ExecuteFile),cRegister);

end;
initialization
__RegisteredMethods := TList.Create;
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
