{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit fr_arg_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  Controls,
  Forms,
  Dialogs,
  FR_Ctrls,
  ExtCtrls,
  StdCtrls,
  Buttons,
  FR_Arg;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TfrFuncArgForm
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrFuncArgForm,'ExprBtn1Click',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrFuncArgForm.ExprBtn1Click));

RegRegisterMethod(TfrFuncArgForm,'FormShow',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrFuncArgForm.FormShow));

RegRegisterMethod(TfrFuncArgForm,'FormHide',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrFuncArgForm.FormHide));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
