{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit fr_e_html2_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  SysUtils,
  Windows,
  Messages,
  Classes,
  Graphics,
  Forms,
  StdCtrls,
  FR_Class,
  Controls,
  Contnrs,
  FR_E_HTML2;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure (p0 : TObject) of object;

_T1 = _T0;

_T2 = _T0;

_T3 = function (const p0 : Integer;
const p1 : Integer): string of object;

_T4 = function : string of object;

_T5 = function : Integer of object;

_T6 = _T5;

_T7 = procedure  of object;

_T8 = procedure (p0 : string) of object;

_T9 = _T7;

_T10 = procedure (p0 : TfrHTML2Export) of object;

_T11 = function (const p0 : Integer;
const p1 : Integer;
const p2 : Integer;
const p3 : Integer;
const p4 : Boolean): string of object;

_T12 = function (p0 : Boolean): string of object;

_T13 = _T4;

_T14 = _T5;

_T15 = procedure (p0 : Integer) of object;

_T16 = procedure (const p0 : TfrHTML2Export;
const p1 : TfrPage;
const p2 : Integer) of object;

_T17 = procedure (const p0 : THFrame) of object;

_T18 = function (p0 : Integer;
p1 : Integer): string of object;

_T19 = _T4;

_T20 = function (const p0 : TFont): string of object;

_T21 = _T20;

_T22 = _T20;

_T23 = function (const p0 : THAlign): string of object;

_T24 = function (const p0 : TColor): string of object;

_T25 = function (p0 : TColor): TColor of object;

_T26 = procedure (const p0 : TfrView;
const p1 : Integer;
const p2 : Double) of object;

_T27 = function (const p0 : THStyle): Boolean of object;

_T28 = _T4;

_T29 = _T7;

_T30 = _T7;

_T31 = function (const p0 : string): Integer of object;

_T32 = _T26;

_T33 = _T26;

_T34 = function : Boolean of object;

_T35 = _T26;

function __DC__GetTHPage__Height(Instance : TObject; Params : PVariantArgList) : OleVariant;
begin
result := THPage(Instance).Height;
end;

procedure __RegisterProps;
begin
RegisterProperty(THPage,'Height',__DC__GetTHPage__Height,nil);
end;

const __ConstNames0 : array[0..20] of string = (
'haLeft'
,'haCenter'
,'haRight'
,'vtFrame'
,'vtText'
,'vtFramedText'
,'gtBmp'
,'gtJpg'
,'npTop'
,'npBottom'
,'hbRight'
,'hbBottom'
,'hbLeft'
,'hbTop'
,'LF'
,'HTMLHeader'
,'HTMLFooter'
,'PageFrame'
,'NavigatorFilePostfix'
,'sLeftArrow'
,'sRightArrow'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,haLeft));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,haCenter));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,haRight));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,vtFrame));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,vtText));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,vtFramedText));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,gtBmp));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,gtJpg));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,npTop));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,npBottom));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,hbRight));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,hbBottom));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,hbLeft));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,hbTop));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,LF));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,HTMLHeader));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[16] ,HTMLFooter));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[17] ,PageFrame));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[18] ,NavigatorFilePostfix));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[19] ,sLeftArrow));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[20] ,sRightArrow));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..12] of TClass = (
TfrHTML2Export,
TfrHTML2ExportForm,
THFrame,
THFramedText,
THGraphic,
THNavigator,
THPage,
THStyle,
THStyleFrame,
THStyleFramedText,
THStyleText,
THText,
TNavigatorItem
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegRegisterMethod(TfrHTML2ExportForm,'FormCreate',TypeInfo(_T0),[
TypeInfo(TObject)],Addr(TfrHTML2ExportForm.FormCreate));

RegRegisterMethod(TfrHTML2ExportForm,'cbImagesClick',TypeInfo(_T1),[
TypeInfo(TObject)],Addr(TfrHTML2ExportForm.cbImagesClick));

RegRegisterMethod(TfrHTML2ExportForm,'cbMultiPageClick',TypeInfo(_T2),[
TypeInfo(TObject)],Addr(TfrHTML2ExportForm.cbMultiPageClick));

RegRegisterMethod(THFrame,'GetHTML',TypeInfo(_T3),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(string)], pointer(0));

RegRegisterMethod(THFrame,'GetContent',TypeInfo(_T4),[TypeInfo(string)], pointer(4));

RegRegisterMethod(THFrame,'GetWidth',TypeInfo(_T5),[TypeInfo(Integer)], pointer(8));

RegRegisterMethod(THFrame,'GetHeight',TypeInfo(_T6),[TypeInfo(Integer)], pointer(12));

RegisterProc(THFramedText,'Create',mtConstructor,TypeInfo(_T7),NoParams,Addr(THFramedText.Create),cRegister);

RegRegisterMethod(THFramedText,'AddString',TypeInfo(_T8),[
TypeInfo(string)],Addr(THFramedText.AddString));

RegisterProc(THGraphic,'Create',mtConstructor,TypeInfo(_T9),NoParams,Addr(THGraphic.Create),cRegister);

RegisterProc(THNavigator,'Create',mtConstructor,TypeInfo(_T10),[
TypeInfo(TfrHTML2Export)],Addr(THNavigator.Create),cRegister);

RegRegisterMethod(THNavigator,'GetHTML',TypeInfo(_T11),[
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Boolean),TypeInfo(string)],Addr(THNavigator.GetHTML));

RegRegisterMethod(THNavigator,'GetStyleHTML',TypeInfo(_T12),[
TypeInfo(Boolean),TypeInfo(string)],Addr(THNavigator.GetStyleHTML));

RegRegisterMethod(THNavigator,'GetStyleName',TypeInfo(_T13),[TypeInfo(string)],Addr(THNavigator.GetStyleName));

RegRegisterMethod(THNavigator,'GetHeight',TypeInfo(_T14),[TypeInfo(Integer)],Addr(THNavigator.GetHeight));

RegRegisterMethod(THNavigator,'BuildItems',TypeInfo(_T15),[
TypeInfo(Integer)],Addr(THNavigator.BuildItems));

RegisterProc(THPage,'Create',mtConstructor,TypeInfo(_T16),[
TypeInfo(TfrHTML2Export),
TypeInfo(TfrPage),
TypeInfo(Integer)],Addr(THPage.Create),cRegister);

RegRegisterMethod(THPage,'AddItem',TypeInfo(_T17),[
TypeInfo(THFrame)],Addr(THPage.AddItem));

RegRegisterMethod(THPage,'GetHTML',TypeInfo(_T18),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(string)],Addr(THPage.GetHTML));

RegRegisterMethod(THPage,'GetName',TypeInfo(_T19),[TypeInfo(string)],Addr(THPage.GetName));

RegisterProc(THStyle,'TextDecorName',mtClassMethod,TypeInfo(_T20),[
TypeInfo(TFont),TypeInfo(string)],Addr(THStyle.TextDecorName),cRegister);

RegisterProc(THStyle,'FontStyleName',mtClassMethod,TypeInfo(_T21),[
TypeInfo(TFont),TypeInfo(string)],Addr(THStyle.FontStyleName),cRegister);

RegisterProc(THStyle,'FontWeightName',mtClassMethod,TypeInfo(_T22),[
TypeInfo(TFont),TypeInfo(string)],Addr(THStyle.FontWeightName),cRegister);

RegisterProc(THStyle,'TextAlignName',mtClassMethod,TypeInfo(_T23),[
TypeInfo(THAlign),TypeInfo(string)],Addr(THStyle.TextAlignName),cRegister);

RegisterProc(THStyle,'GetHtmlColor',mtClassMethod,TypeInfo(_T24),[
TypeInfo(TColor),TypeInfo(string)],Addr(THStyle.GetHtmlColor),cRegister);

RegisterProc(THStyle,'CorrectColor',mtClassMethod,TypeInfo(_T25),[
TypeInfo(TColor),TypeInfo(TColor)],Addr(THStyle.CorrectColor),cRegister);

RegisterProc(THStyle,'Create',mtConstructor,TypeInfo(_T26),[
TypeInfo(TfrView),
TypeInfo(Integer),
TypeInfo(Double)],Addr(THStyle.Create),cRegister);

RegRegisterMethod(THStyle,'Equals',TypeInfo(_T27),[
TypeInfo(THStyle),TypeInfo(Boolean)], pointer(0));

RegRegisterMethod(THStyle,'GetHTML',TypeInfo(_T28),[TypeInfo(string)], pointer(4));

RegRegisterMethod(THStyle,'IncrementCount',TypeInfo(_T29),NoParams,Addr(THStyle.IncrementCount));

RegRegisterMethod(THStyle,'SetDefault',TypeInfo(_T30),NoParams,Addr(THStyle.SetDefault));

RegRegisterMethod(THStyle,'TextWidth',TypeInfo(_T31),[
TypeInfo(string),TypeInfo(Integer)],Addr(THStyle.TextWidth));

RegisterProc(THStyleFrame,'Create',mtConstructor,TypeInfo(_T32),[
TypeInfo(TfrView),
TypeInfo(Integer),
TypeInfo(Double)],Addr(THStyleFrame.Create),cRegister);

RegisterProc(THStyleFramedText,'Create',mtConstructor,TypeInfo(_T33),[
TypeInfo(TfrView),
TypeInfo(Integer),
TypeInfo(Double)],Addr(THStyleFramedText.Create),cRegister);

RegRegisterMethod(THStyleFramedText,'IsTextJustify',TypeInfo(_T34),[TypeInfo(Boolean)],Addr(THStyleFramedText.IsTextJustify));

RegisterProc(THStyleText,'Create',mtConstructor,TypeInfo(_T35),[
TypeInfo(TfrView),
TypeInfo(Integer),
TypeInfo(Double)],Addr(THStyleText.Create),cRegister);

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
