{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit fr_intrp_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Classes,
  SysUtils,
  FR_Pars,
  FR_Intrp;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = procedure (const p0 : String;
var p1 : Variant) of object;

_T2 = procedure (const p0 : String;
p1 : Variant) of object;

_T3 = procedure (const p0 : String;
p1 : Variant;
p2 : Variant;
p3 : Variant;
var p4 : Variant) of object;

_T4 = procedure (p0 : TStrings;
p1 : TStrings;
p2 : TStrings) of object;

_T5 = procedure (p0 : TStrings) of object;

_T6 = procedure (p0 : TStrings;
p1 : TStrings;
p2 : TStrings;
p3 : TfrVariables) of object;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..0] of TClass = (
TfrInterpretator
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegisterProc(TfrInterpretator,'Create',mtConstructor,TypeInfo(_T0),NoParams,Addr(TfrInterpretator.Create),cRegister);

RegRegisterMethod(TfrInterpretator,'GetValue',TypeInfo(_T1),[
TypeInfo(String),
TypeInfo(Variant)], pointer(0));

RegRegisterMethod(TfrInterpretator,'SetValue',TypeInfo(_T2),[
TypeInfo(String),
TypeInfo(Variant)], pointer(4));

RegRegisterMethod(TfrInterpretator,'DoFunction',TypeInfo(_T3),[
TypeInfo(String),
TypeInfo(Variant),
TypeInfo(Variant),
TypeInfo(Variant),
TypeInfo(Variant)], pointer(8));

RegRegisterMethod(TfrInterpretator,'PrepareScript',TypeInfo(_T4),[
TypeInfo(TStrings),
TypeInfo(TStrings),
TypeInfo(TStrings)], pointer(12));

RegRegisterMethod(TfrInterpretator,'DoScript',TypeInfo(_T5),[
TypeInfo(TStrings)], pointer(16));

RegRegisterMethod(TfrInterpretator,'SplitExpressions',TypeInfo(_T6),[
TypeInfo(TStrings),
TypeInfo(TStrings),
TypeInfo(TStrings),
TypeInfo(TfrVariables)],Addr(TfrInterpretator.SplitExpressions));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
