{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit fr_shape_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  Graphics,
  FR_Class,
  StdCtrls,
  Controls,
  Forms,
  ExtCtrls,
  Menus,
  FR_Shape;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..5] of string = (
'skRectangle'
,'skRoundRectangle'
,'skEllipse'
,'skTriangle'
,'skDiagonal1'
,'skDiagonal2'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,skRectangle));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,skRoundRectangle));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,skEllipse));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,skTriangle));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,skDiagonal1));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,skDiagonal2));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

const ClassList : array[0..1] of TClass = (
TfrShapeObject,
TfrShapeView
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

procedure _mreg_0;
begin
end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
