{*******************************************************}
{                                                       }
{ Import unit generated by UNITIMPORTER program         }
{                                                       }
{*******************************************************}

Unit frIEMatrix_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  activex,
  dcscript,
  dcsystem,
  dcdreamlib,
  Windows,
  Messages,
  SysUtils,
  Classes,
  graphics,
  fr_Class,
  fr_utils,
  frProgr,
  frIEMatrix;
implementation
{$IFDEF D3}
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type
_T0 = procedure  of object;

_T1 = function (p0 : Integer;
p1 : Integer): Integer of object;

_T2 = function (p0 : Integer): TfrIEMObject of object;

_T3 = function (p0 : Integer): TfrIEMStyle of object;

_T4 = function (p0 : Integer): Extended of object;

_T5 = _T4;

_T6 = function (p0 : Integer;
p1 : Integer): TfrIEMObject of object;

_T7 = function (p0 : Integer;
p1 : Integer): TfrIEMStyle of object;

_T8 = _T4;

_T9 = _T4;

_T10 = _T4;

_T11 = function : Integer of object;

_T12 = _T11;

_T13 = _T11;

_T14 = _T0;

_T15 = procedure (p0 : TfrView) of object;

_T16 = _T0;

_T17 = procedure (p0 : Integer;
var p1 : Integer;
var p2 : Integer;
var p3 : Integer;
var p4 : Integer) of object;

_T18 = _T0;

_T19 = _T0;

_T20 = _T0;

_T21 = _T0;

_T22 = procedure (p0 : TfrIEMStyle) of object;

procedure __RegisterProps;
begin
end;

procedure __RegisterConsts0;
begin
end;

procedure __UnregisterConsts0;
begin
end;

const ClassList : array[0..4] of TClass = (
TfrIEMatrix,
TfrIEMObject,
TfrIEMObjectList,
TfrIEMPos,
TfrIEMStyle
);
procedure __RegisterClasses;
begin
RegisterClassesInScript(ClassList);
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
procedure _mreg_0;
begin
RegisterProc(TfrIEMatrix,'Create',mtConstructor,TypeInfo(_T0),NoParams,Addr(TfrIEMatrix.Create),cRegister);

RegRegisterMethod(TfrIEMatrix,'GetCell',TypeInfo(_T1),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(Integer)],Addr(TfrIEMatrix.GetCell));

RegRegisterMethod(TfrIEMatrix,'GetObjectById',TypeInfo(_T2),[
TypeInfo(Integer),TypeInfo(TfrIEMObject)],Addr(TfrIEMatrix.GetObjectById));

RegRegisterMethod(TfrIEMatrix,'GetStyleById',TypeInfo(_T3),[
TypeInfo(Integer),TypeInfo(TfrIEMStyle)],Addr(TfrIEMatrix.GetStyleById));

RegRegisterMethod(TfrIEMatrix,'GetXPosById',TypeInfo(_T4),[
TypeInfo(Integer),TypeInfo(Extended)],Addr(TfrIEMatrix.GetXPosById));

RegRegisterMethod(TfrIEMatrix,'GetYPosById',TypeInfo(_T5),[
TypeInfo(Integer),TypeInfo(Extended)],Addr(TfrIEMatrix.GetYPosById));

RegRegisterMethod(TfrIEMatrix,'GetObject',TypeInfo(_T6),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(TfrIEMObject)],Addr(TfrIEMatrix.GetObject));

RegRegisterMethod(TfrIEMatrix,'GetStyle',TypeInfo(_T7),[
TypeInfo(Integer),
TypeInfo(Integer),TypeInfo(TfrIEMStyle)],Addr(TfrIEMatrix.GetStyle));

RegRegisterMethod(TfrIEMatrix,'GetCellXPos',TypeInfo(_T8),[
TypeInfo(Integer),TypeInfo(Extended)],Addr(TfrIEMatrix.GetCellXPos));

RegRegisterMethod(TfrIEMatrix,'GetCellYPos',TypeInfo(_T9),[
TypeInfo(Integer),TypeInfo(Extended)],Addr(TfrIEMatrix.GetCellYPos));

RegRegisterMethod(TfrIEMatrix,'GetPageBreak',TypeInfo(_T10),[
TypeInfo(Integer),TypeInfo(Extended)],Addr(TfrIEMatrix.GetPageBreak));

RegRegisterMethod(TfrIEMatrix,'GetStylesCount',TypeInfo(_T11),[TypeInfo(Integer)],Addr(TfrIEMatrix.GetStylesCount));

RegRegisterMethod(TfrIEMatrix,'GetPagesCount',TypeInfo(_T12),[TypeInfo(Integer)],Addr(TfrIEMatrix.GetPagesCount));

RegRegisterMethod(TfrIEMatrix,'GetObjectsCount',TypeInfo(_T13),[TypeInfo(Integer)],Addr(TfrIEMatrix.GetObjectsCount));

RegRegisterMethod(TfrIEMatrix,'Clear',TypeInfo(_T14),NoParams,Addr(TfrIEMatrix.Clear));

RegRegisterMethod(TfrIEMatrix,'AddObject',TypeInfo(_T15),[
TypeInfo(TfrView)],Addr(TfrIEMatrix.AddObject));

RegRegisterMethod(TfrIEMatrix,'Prepare',TypeInfo(_T16),NoParams,Addr(TfrIEMatrix.Prepare));

RegRegisterMethod(TfrIEMatrix,'GetObjectPos',TypeInfo(_T17),[
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Integer),
TypeInfo(Integer)],Addr(TfrIEMatrix.GetObjectPos));

RegRegisterMethod(TfrIEMatrix,'EndPage',TypeInfo(_T18),NoParams,Addr(TfrIEMatrix.EndPage));

RegisterProc(TfrIEMObject,'Create',mtConstructor,TypeInfo(_T19),NoParams,Addr(TfrIEMObject.Create),cRegister);

RegisterProc(TfrIEMObjectList,'Create',mtConstructor,TypeInfo(_T20),NoParams,Addr(TfrIEMObjectList.Create),cRegister);

RegisterProc(TfrIEMStyle,'Create',mtConstructor,TypeInfo(_T21),NoParams,Addr(TfrIEMStyle.Create),cRegister);

RegRegisterMethod(TfrIEMStyle,'Assign',TypeInfo(_T22),[
TypeInfo(TfrIEMStyle)],Addr(TfrIEMStyle.Assign));

end;
initialization
_mreg_0;
__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
end.
