{*******************************************************}
{                                                       }
{ Import unit generated by ImpGen program               }
{                                                       }
{     Copyright (c) 1997-2000 Dream Company             }
{                                                       }
{*******************************************************}

Unit KCommon_imp;
interface
{$I dc.inc}
{$D-,L-,Y-}
{$HINTS OFF}
{$WARNINGS OFF}
uses
  Controls,
  Graphics,
  Windows,
  classes,
  dcscript,
  dcsystem,
  KCommon;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
implementation
{$IFDEF D3}
uses activex;
{$ELSE}
uses ole2;
type
  OleVariant = Variant;
{$ENDIF}
type __TRect__Wrapper = class(TDCRecordWrapper)
private
fR : TRect;
public
function GetRecordPtr : pointer; override;
published
procedure setLeft(const val : Integer);
function getLeft : Integer;
property Left : Integer read getLeft write setLeft;
procedure setTop(const val : Integer);
function getTop : Integer;
property Top : Integer read getTop write setTop;
procedure setRight(const val : Integer);
function getRight : Integer;
property Right : Integer read getRight write setRight;
procedure setBottom(const val : Integer);
function getBottom : Integer;
property Bottom : Integer read getBottom write setBottom;
end;
type
_T0 = function (p0 : TCanvas;
const p1 : IDispatch;
p2 : TColor;
p3 : TColor;
p4 : TBevelEdges): IDispatch of object;

_T1 = function (p0 : TCanvas;
const p1 : IDispatch;
p2 : TKFrameStyle;
p3 : TBevelEdges): IDispatch of object;

_T2 = procedure (p0 : TCanvas;
p1 : TGraphic;
const p2 : IDispatch;
p3 : TKImageAlignment;
p4 : TKImageLayout) of object;

function __TRect__Wrapper.GetRecordPtr : pointer;
begin
result := @fR;
end;
procedure __TRect__Wrapper.setLeft(const val : Integer);
begin
TRect(GetRecordPtr^).Left := val;
end;
function __TRect__Wrapper.getLeft : Integer;
begin
result := TRect(GetRecordPtr^).Left;
end;
procedure __TRect__Wrapper.setTop(const val : Integer);
begin
TRect(GetRecordPtr^).Top := val;
end;
function __TRect__Wrapper.getTop : Integer;
begin
result := TRect(GetRecordPtr^).Top;
end;
procedure __TRect__Wrapper.setRight(const val : Integer);
begin
TRect(GetRecordPtr^).Right := val;
end;
function __TRect__Wrapper.getRight : Integer;
begin
result := TRect(GetRecordPtr^).Right;
end;
procedure __TRect__Wrapper.setBottom(const val : Integer);
begin
TRect(GetRecordPtr^).Bottom := val;
end;
function __TRect__Wrapper.getBottom : Integer;
begin
result := TRect(GetRecordPtr^).Bottom;
end;
function ____KDrawEdges__Wrapper(p0 : TCanvas;
const p1 : IDispatch;
p2 : TColor;
p3 : TColor;
p4 : TBevelEdges): IDispatch;
var
__result : TRect;
__wrapper : __TRect__Wrapper;
__p1 : ^TRect;
__i1 : IDispatch;
begin
if p1 = nil then exit;
__p1 := (p1 as IDCRecordWrapper).GetRecordPtr;
__result := KDrawEdges(p0,__p1^,p2,p3,p4);
__wrapper := __TRect__Wrapper.Create;
__wrapper.fR := __result;
result := __wrapper;
end;

function ____KDrawBorderEdges__Wrapper(p0 : TCanvas;
const p1 : IDispatch;
p2 : TKFrameStyle;
p3 : TBevelEdges): IDispatch;
var
__result : TRect;
__wrapper : __TRect__Wrapper;
__p1 : ^TRect;
__i1 : IDispatch;
begin
if p1 = nil then exit;
__p1 := (p1 as IDCRecordWrapper).GetRecordPtr;
__result := KDrawBorderEdges(p0,__p1^,p2,p3);
__wrapper := __TRect__Wrapper.Create;
__wrapper.fR := __result;
result := __wrapper;
end;

procedure ____KDrawImage__Wrapper(p0 : TCanvas;
p1 : TGraphic;
const p2 : IDispatch;
p3 : TKImageAlignment;
p4 : TKImageLayout);
var
__p2 : ^TRect;
__i2 : IDispatch;
begin
if p2 = nil then exit;
__p2 := (p2 as IDCRecordWrapper).GetRecordPtr;
KDrawImage(p0,p1,__p2^,p3,p4);
end;


type __TRect__Wrapper__ = class(__TRect__Wrapper)
private
fRPtr : pointer;
function GetRecordPtr : pointer; override;
end;
function __TRect__Wrapper__.GetRecordPtr : pointer;
begin
result := fRPtr;
end;
function ConvertTRectToVariant(var R : TRect) : OleVariant;
var
__rw : __TRect__Wrapper__;
begin
__rw := __TRect__Wrapper__.Create;
__rw.fRPtr := @R;
result := IDispatch(__rw);
end;
function ConvertVariantToTRect(const V : OleVariant) : TRect;
var
_idisp : IDispatch;
begin
_idisp := VarToInterface(v);
if _idisp = nil then exit;
result := TRect((_idisp as IDCRecordWrapper).GetRecordPtr^);
end;
procedure __RegisterProps;
begin
end;

const __ConstNames0 : array[0..15] of string = (
'fsWindows'
,'fsNone'
,'fsFlat'
,'fsGroove'
,'fsBump'
,'fsLowered'
,'fsRaised'
,'iaLeft'
,'iaRight'
,'iaCenter'
,'iaStretch'
,'ilTop'
,'ilBottom'
,'ilCenter'
,'ilStretch'
,'beAllEdges'
);
var __RegisteredConstsList0 : TList;
procedure __RegisterConsts0;
begin
__RegisteredConstsList0 := TList.Create;
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[0] ,fsWindows));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[1] ,fsNone));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[2] ,fsFlat));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[3] ,fsGroove));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[4] ,fsBump));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[5] ,fsLowered));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[6] ,fsRaised));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[7] ,iaLeft));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[8] ,iaRight));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[9] ,iaCenter));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[10] ,iaStretch));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[11] ,ilTop));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[12] ,ilBottom));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[13] ,ilCenter));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[14] ,ilStretch));
__RegisteredConstsList0.Add(RegisterConst(__ConstNames0[15] ,VarFromSet(beAllEdges, sizeof(beAllEdges))));
end;

procedure __UnregisterConsts0;
var i : integer;
begin
__RegisteredConstsList0.Free
end;

procedure __RegisterClasses;
begin
end;

procedure __UnRegisterClasses;
begin
end;

var __RegisteredMethods : TList;
const MethodNames : array[0..2] of string = (
'KDrawEdges'
,'KDrawBorderEdges'
,'KDrawImage'
);

procedure __UnregisterProcs;
var i : integer;
begin
__RegisteredMethods.Free;
end;

initialization
__RegisteredMethods := TList.Create;
__RegisteredMethods.Add(RegisterProc(nil,MethodNames[0],mtProc,TypeInfo(_T0),[
TypeInfo(TCanvas),
TypeInfo(IDispatch),
TypeInfo(TColor),
TypeInfo(TColor),
TypeInfo(TBevelEdges),TypeInfo(IDispatch)],Addr(____KDrawEdges__Wrapper),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[1],mtProc,TypeInfo(_T1),[
TypeInfo(TCanvas),
TypeInfo(IDispatch),
TypeInfo(TKFrameStyle),
TypeInfo(TBevelEdges),TypeInfo(IDispatch)],Addr(____KDrawBorderEdges__Wrapper),cRegister));

__RegisteredMethods.Add(RegisterProc(nil,MethodNames[2],mtProc,TypeInfo(_T2),[
TypeInfo(TCanvas),
TypeInfo(TGraphic),
TypeInfo(IDispatch),
TypeInfo(TKImageAlignment),
TypeInfo(TKImageLayout)],Addr(____KDrawImage__Wrapper),cRegister));

__RegisterClasses;
__RegisterConsts0;
__RegisterProps;

finalization
__UnRegisterClasses;
__UnregisterConsts0;
__UnregisterProcs;
end.
